/**
 * Zugzwang Project
 * SQL updates for default module
 *
 * http://www.zugzwang.org/modules/default
 *
 * @author Gustaf Mossakowski <gustaf@koenige.org>
 * @copyright Copyright © 2019-2020 Gustaf Mossakowski
 * @license http://opensource.org/licenses/lgpl-3.0.html LGPL-3.0
 */

/* 2019-11-19-1 */	ALTER TABLE `categories` CHANGE `path` `path` varchar(100) COLLATE 'latin1_general_ci' NOT NULL AFTER `main_category_id`;
/* 2020-02-25-1 */	ALTER TABLE `webpages` ADD INDEX `mother_page_id` (`mother_page_id`);
/* 2020-02-25-2 */	ALTER TABLE `redirects` CHANGE `old_url` `old_url` varchar(127) COLLATE 'latin1_general_ci' NOT NULL AFTER `redirect_id`, CHANGE `new_url` `new_url` varchar(127) COLLATE 'latin1_general_ci' NOT NULL AFTER `old_url`;
/* 2020-02-25-3 */	ALTER TABLE `_settings` CHANGE `setting_value` `setting_value` varchar(750) COLLATE 'utf8mb4_unicode_ci' NOT NULL AFTER `setting_key`;
/* 2020-02-25-4 */	ALTER TABLE `_settings` DROP `login_id`;
/* 2020-02-25-5 */	ALTER TABLE `_settings` ADD UNIQUE (`setting_key`);
/* 2020-02-25-6 */	DELETE FROM _relations WHERE master_table = "logins" AND detail_table = "_settings";
/* 2020-02-25-7 */	ALTER TABLE `webpages` ADD UNIQUE `identifier` (`identifier`);
/* 2020-04-07-1 */	ALTER TABLE `countries` ADD `country_code3` char(3) COLLATE 'latin1_general_ci' NOT NULL AFTER `country_code`;
/* 2020-04-07-2 */	UPDATE `countries` SET `country_code3` = 'AFG' WHERE `country_code` = 'AF';
/* 2020-04-07-3 */	UPDATE `countries` SET `country_code3` = 'ALB' WHERE `country_code` = 'AL';
/* 2020-04-07-4 */	UPDATE `countries` SET `country_code3` = 'DZA' WHERE `country_code` = 'DZ';
/* 2020-04-07-5 */	UPDATE `countries` SET `country_code3` = 'ASM' WHERE `country_code` = 'AS';
/* 2020-04-07-6 */	UPDATE `countries` SET `country_code3` = 'AND' WHERE `country_code` = 'AD';
/* 2020-04-07-7 */	UPDATE `countries` SET `country_code3` = 'AGO' WHERE `country_code` = 'AO';
/* 2020-04-07-8 */	UPDATE `countries` SET `country_code3` = 'AIA' WHERE `country_code` = 'AI';
/* 2020-04-07-9 */	UPDATE `countries` SET `country_code3` = 'ATA' WHERE `country_code` = 'AQ';
/* 2020-04-07-10 */	UPDATE `countries` SET `country_code3` = 'ATG' WHERE `country_code` = 'AG';
/* 2020-04-07-11 */	UPDATE `countries` SET `country_code3` = 'ARG' WHERE `country_code` = 'AR';
/* 2020-04-07-12 */	UPDATE `countries` SET `country_code3` = 'ARM' WHERE `country_code` = 'AM';
/* 2020-04-07-13 */	UPDATE `countries` SET `country_code3` = 'ABW' WHERE `country_code` = 'AW';
/* 2020-04-07-14 */	UPDATE `countries` SET `country_code3` = 'AUS' WHERE `country_code` = 'AU';
/* 2020-04-07-15 */	UPDATE `countries` SET `country_code3` = 'AUT' WHERE `country_code` = 'AT';
/* 2020-04-07-16 */	UPDATE `countries` SET `country_code3` = 'AZE' WHERE `country_code` = 'AZ';
/* 2020-04-07-17 */	UPDATE `countries` SET `country_code3` = 'BHS' WHERE `country_code` = 'BS';
/* 2020-04-07-18 */	UPDATE `countries` SET `country_code3` = 'BHR' WHERE `country_code` = 'BH';
/* 2020-04-07-19 */	UPDATE `countries` SET `country_code3` = 'BGD' WHERE `country_code` = 'BD';
/* 2020-04-07-20 */	UPDATE `countries` SET `country_code3` = 'BRB' WHERE `country_code` = 'BB';
/* 2020-04-07-21 */	UPDATE `countries` SET `country_code3` = 'BLR' WHERE `country_code` = 'BY';
/* 2020-04-07-22 */	UPDATE `countries` SET `country_code3` = 'BEL' WHERE `country_code` = 'BE';
/* 2020-04-07-23 */	UPDATE `countries` SET `country_code3` = 'BLZ' WHERE `country_code` = 'BZ';
/* 2020-04-07-24 */	UPDATE `countries` SET `country_code3` = 'BEN' WHERE `country_code` = 'BJ';
/* 2020-04-07-25 */	UPDATE `countries` SET `country_code3` = 'BMU' WHERE `country_code` = 'BM';
/* 2020-04-07-26 */	UPDATE `countries` SET `country_code3` = 'BTN' WHERE `country_code` = 'BT';
/* 2020-04-07-27 */	UPDATE `countries` SET `country_code3` = 'BOL' WHERE `country_code` = 'BO';
/* 2020-04-07-28 */	UPDATE `countries` SET `country_code3` = 'BIH' WHERE `country_code` = 'BA';
/* 2020-04-07-29 */	UPDATE `countries` SET `country_code3` = 'BWA' WHERE `country_code` = 'BW';
/* 2020-04-07-30 */	UPDATE `countries` SET `country_code3` = 'BVT' WHERE `country_code` = 'BV';
/* 2020-04-07-31 */	UPDATE `countries` SET `country_code3` = 'BRA' WHERE `country_code` = 'BR';
/* 2020-04-07-32 */	UPDATE `countries` SET `country_code3` = 'IOT' WHERE `country_code` = 'IO';
/* 2020-04-07-33 */	UPDATE `countries` SET `country_code3` = 'BRN' WHERE `country_code` = 'BN';
/* 2020-04-07-34 */	UPDATE `countries` SET `country_code3` = 'BGR' WHERE `country_code` = 'BG';
/* 2020-04-07-35 */	UPDATE `countries` SET `country_code3` = 'BFA' WHERE `country_code` = 'BF';
/* 2020-04-07-36 */	UPDATE `countries` SET `country_code3` = 'BDI' WHERE `country_code` = 'BI';
/* 2020-04-07-37 */	UPDATE `countries` SET `country_code3` = 'KHM' WHERE `country_code` = 'KH';
/* 2020-04-07-38 */	UPDATE `countries` SET `country_code3` = 'CMR' WHERE `country_code` = 'CM';
/* 2020-04-07-39 */	UPDATE `countries` SET `country_code3` = 'CAN' WHERE `country_code` = 'CA';
/* 2020-04-07-40 */	UPDATE `countries` SET `country_code3` = 'CPV' WHERE `country_code` = 'CV';
/* 2020-04-07-41 */	UPDATE `countries` SET `country_code3` = 'CYM' WHERE `country_code` = 'KY';
/* 2020-04-07-42 */	UPDATE `countries` SET `country_code3` = 'CAF' WHERE `country_code` = 'CF';
/* 2020-04-07-43 */	UPDATE `countries` SET `country_code3` = 'TCD' WHERE `country_code` = 'TD';
/* 2020-04-07-44 */	UPDATE `countries` SET `country_code3` = 'CHL' WHERE `country_code` = 'CL';
/* 2020-04-07-45 */	UPDATE `countries` SET `country_code3` = 'CHN' WHERE `country_code` = 'CN';
/* 2020-04-07-46 */	UPDATE `countries` SET `country_code3` = 'CXR' WHERE `country_code` = 'CX';
/* 2020-04-07-47 */	UPDATE `countries` SET `country_code3` = 'CCK' WHERE `country_code` = 'CC';
/* 2020-04-07-48 */	UPDATE `countries` SET `country_code3` = 'COL' WHERE `country_code` = 'CO';
/* 2020-04-07-49 */	UPDATE `countries` SET `country_code3` = 'COM' WHERE `country_code` = 'KM';
/* 2020-04-07-50 */	UPDATE `countries` SET `country_code3` = 'COG' WHERE `country_code` = 'CG';
/* 2020-04-07-51 */	UPDATE `countries` SET `country_code3` = 'COD' WHERE `country_code` = 'CD';
/* 2020-04-07-52 */	UPDATE `countries` SET `country_code3` = 'COK' WHERE `country_code` = 'CK';
/* 2020-04-07-53 */	UPDATE `countries` SET `country_code3` = 'CRI' WHERE `country_code` = 'CR';
/* 2020-04-07-54 */	UPDATE `countries` SET `country_code3` = 'CIV' WHERE `country_code` = 'CI';
/* 2020-04-07-55 */	UPDATE `countries` SET `country_code3` = 'HRV' WHERE `country_code` = 'HR';
/* 2020-04-07-56 */	UPDATE `countries` SET `country_code3` = 'CUB' WHERE `country_code` = 'CU';
/* 2020-04-07-57 */	UPDATE `countries` SET `country_code3` = 'CYP' WHERE `country_code` = 'CY';
/* 2020-04-07-58 */	UPDATE `countries` SET `country_code3` = 'CZE', `country` = 'Czechia' WHERE `country_code` = 'CZ';
/* 2020-04-07-59 */	UPDATE `countries` SET `country_code3` = 'DNK' WHERE `country_code` = 'DK';
/* 2020-04-07-60 */	UPDATE `countries` SET `country_code3` = 'DJI' WHERE `country_code` = 'DJ';
/* 2020-04-07-61 */	UPDATE `countries` SET `country_code3` = 'DMA' WHERE `country_code` = 'DM';
/* 2020-04-07-62 */	UPDATE `countries` SET `country_code3` = 'DOM' WHERE `country_code` = 'DO';
/* 2020-04-07-63 */	UPDATE `countries` SET `country_code3` = 'ECU' WHERE `country_code` = 'EC';
/* 2020-04-07-64 */	UPDATE `countries` SET `country_code3` = 'EGY' WHERE `country_code` = 'EG';
/* 2020-04-07-65 */	UPDATE `countries` SET `country_code3` = 'SLV' WHERE `country_code` = 'SV';
/* 2020-04-07-66 */	UPDATE `countries` SET `country_code3` = 'GNQ' WHERE `country_code` = 'GQ';
/* 2020-04-07-67 */	UPDATE `countries` SET `country_code3` = 'ERI' WHERE `country_code` = 'ER';
/* 2020-04-07-68 */	UPDATE `countries` SET `country_code3` = 'EST' WHERE `country_code` = 'EE';
/* 2020-04-07-69 */	UPDATE `countries` SET `country_code3` = 'ETH' WHERE `country_code` = 'ET';
/* 2020-04-07-70 */	UPDATE `countries` SET `country_code3` = 'FLK' WHERE `country_code` = 'FK';
/* 2020-04-07-71 */	UPDATE `countries` SET `country_code3` = 'FRO' WHERE `country_code` = 'FO';
/* 2020-04-07-72 */	UPDATE `countries` SET `country_code3` = 'FJI' WHERE `country_code` = 'FJ';
/* 2020-04-07-73 */	UPDATE `countries` SET `country_code3` = 'FIN' WHERE `country_code` = 'FI';
/* 2020-04-07-74 */	UPDATE `countries` SET `country_code3` = 'FRA' WHERE `country_code` = 'FR';
/* 2020-04-07-75 */	UPDATE `countries` SET `country_code3` = 'GUF' WHERE `country_code` = 'GF';
/* 2020-04-07-76 */	UPDATE `countries` SET `country_code3` = 'PYF' WHERE `country_code` = 'PF';
/* 2020-04-07-77 */	UPDATE `countries` SET `country_code3` = 'ATF' WHERE `country_code` = 'TF';
/* 2020-04-07-78 */	UPDATE `countries` SET `country_code3` = 'GAB' WHERE `country_code` = 'GA';
/* 2020-04-07-79 */	UPDATE `countries` SET `country_code3` = 'GMB' WHERE `country_code` = 'GM';
/* 2020-04-07-80 */	UPDATE `countries` SET `country_code3` = 'GEO' WHERE `country_code` = 'GE';
/* 2020-04-07-81 */	UPDATE `countries` SET `country_code3` = 'DEU' WHERE `country_code` = 'DE';
/* 2020-04-07-82 */	UPDATE `countries` SET `country_code3` = 'GHA' WHERE `country_code` = 'GH';
/* 2020-04-07-83 */	UPDATE `countries` SET `country_code3` = 'GIB' WHERE `country_code` = 'GI';
/* 2020-04-07-84 */	UPDATE `countries` SET `country_code3` = 'GRC' WHERE `country_code` = 'GR';
/* 2020-04-07-85 */	UPDATE `countries` SET `country_code3` = 'GRL' WHERE `country_code` = 'GL';
/* 2020-04-07-86 */	UPDATE `countries` SET `country_code3` = 'GRD' WHERE `country_code` = 'GD';
/* 2020-04-07-87 */	UPDATE `countries` SET `country_code3` = 'GLP' WHERE `country_code` = 'GP';
/* 2020-04-07-88 */	UPDATE `countries` SET `country_code3` = 'GUM' WHERE `country_code` = 'GU';
/* 2020-04-07-89 */	UPDATE `countries` SET `country_code3` = 'GTM' WHERE `country_code` = 'GT';
/* 2020-04-07-90 */	UPDATE `countries` SET `country_code3` = 'GIN' WHERE `country_code` = 'GN';
/* 2020-04-07-91 */	UPDATE `countries` SET `country_code3` = 'GNB' WHERE `country_code` = 'GW';
/* 2020-04-07-92 */	UPDATE `countries` SET `country_code3` = 'GUY' WHERE `country_code` = 'GY';
/* 2020-04-07-93 */	UPDATE `countries` SET `country_code3` = 'HTI' WHERE `country_code` = 'HT';
/* 2020-04-07-94 */	UPDATE `countries` SET `country_code3` = 'HMD', `country` = 'Heard Island and McDonald Islands' WHERE `country_code` = 'HM';
/* 2020-04-07-95 */	UPDATE `countries` SET `country_code3` = 'VAT' WHERE `country_code` = 'VA';
/* 2020-04-07-96 */	UPDATE `countries` SET `country_code3` = 'HND' WHERE `country_code` = 'HN';
/* 2020-04-07-97 */	UPDATE `countries` SET `country_code3` = 'HKG' WHERE `country_code` = 'HK';
/* 2020-04-07-98 */	UPDATE `countries` SET `country_code3` = 'HUN' WHERE `country_code` = 'HU';
/* 2020-04-07-99 */	UPDATE `countries` SET `country_code3` = 'ISL' WHERE `country_code` = 'IS';
/* 2020-04-07-100 */	UPDATE `countries` SET `country_code3` = 'IND' WHERE `country_code` = 'IN';
/* 2020-04-07-101 */	UPDATE `countries` SET `country_code3` = 'IDN' WHERE `country_code` = 'ID';
/* 2020-04-07-102 */	UPDATE `countries` SET `country_code3` = 'IRN', `country` = 'Iran' WHERE `country_code` = 'IR';
/* 2020-04-07-103 */	UPDATE `countries` SET `country_code3` = 'IRQ' WHERE `country_code` = 'IQ';
/* 2020-04-07-104 */	UPDATE `countries` SET `country_code3` = 'IRL' WHERE `country_code` = 'IE';
/* 2020-04-07-105 */	UPDATE `countries` SET `country_code3` = 'ISR' WHERE `country_code` = 'IL';
/* 2020-04-07-106 */	UPDATE `countries` SET `country_code3` = 'ITA' WHERE `country_code` = 'IT';
/* 2020-04-07-107 */	UPDATE `countries` SET `country_code3` = 'JAM' WHERE `country_code` = 'JM';
/* 2020-04-07-108 */	UPDATE `countries` SET `country_code3` = 'JPN' WHERE `country_code` = 'JP';
/* 2020-04-07-109 */	UPDATE `countries` SET `country_code3` = 'JOR' WHERE `country_code` = 'JO';
/* 2020-04-07-110 */	UPDATE `countries` SET `country_code3` = 'KAZ' WHERE `country_code` = 'KZ';
/* 2020-04-07-111 */	UPDATE `countries` SET `country_code3` = 'KEN' WHERE `country_code` = 'KE';
/* 2020-04-07-112 */	UPDATE `countries` SET `country_code3` = 'KIR' WHERE `country_code` = 'KI';
/* 2020-04-07-113 */	UPDATE `countries` SET `country_code3` = 'PRK' WHERE `country_code` = 'KP';
/* 2020-04-07-114 */	UPDATE `countries` SET `country_code3` = 'KOR' WHERE `country_code` = 'KR';
/* 2020-04-07-115 */	UPDATE `countries` SET `country_code3` = 'KWT' WHERE `country_code` = 'KW';
/* 2020-04-07-116 */	UPDATE `countries` SET `country_code3` = 'KGZ' WHERE `country_code` = 'KG';
/* 2020-04-07-117 */	UPDATE `countries` SET `country_code3` = 'LAO', `country` = 'Laos' WHERE `country_code` = 'LA';
/* 2020-04-07-118 */	UPDATE `countries` SET `country_code3` = 'LVA' WHERE `country_code` = 'LV';
/* 2020-04-07-119 */	UPDATE `countries` SET `country_code3` = 'LBN' WHERE `country_code` = 'LB';
/* 2020-04-07-120 */	UPDATE `countries` SET `country_code3` = 'LSO' WHERE `country_code` = 'LS';
/* 2020-04-07-121 */	UPDATE `countries` SET `country_code3` = 'LBR' WHERE `country_code` = 'LR';
/* 2020-04-07-122 */	UPDATE `countries` SET `country_code3` = 'LBY', `country` = 'Libya' WHERE `country_code` = 'LY';
/* 2020-04-07-123 */	UPDATE `countries` SET `country_code3` = 'LIE' WHERE `country_code` = 'LI';
/* 2020-04-07-124 */	UPDATE `countries` SET `country_code3` = 'LTU' WHERE `country_code` = 'LT';
/* 2020-04-07-125 */	UPDATE `countries` SET `country_code3` = 'LUX' WHERE `country_code` = 'LU';
/* 2020-04-07-126 */	UPDATE `countries` SET `country_code3` = 'MAC' WHERE `country_code` = 'MO';
/* 2020-04-07-127 */	UPDATE `countries` SET `country_code3` = 'MKD', `country` = 'North Macedonia' WHERE `country_code` = 'MK';
/* 2020-04-07-128 */	UPDATE `countries` SET `country_code3` = 'MDG' WHERE `country_code` = 'MG';
/* 2020-04-07-129 */	UPDATE `countries` SET `country_code3` = 'MWI' WHERE `country_code` = 'MW';
/* 2020-04-07-130 */	UPDATE `countries` SET `country_code3` = 'MYS' WHERE `country_code` = 'MY';
/* 2020-04-07-131 */	UPDATE `countries` SET `country_code3` = 'MDV' WHERE `country_code` = 'MV';
/* 2020-04-07-132 */	UPDATE `countries` SET `country_code3` = 'MLI' WHERE `country_code` = 'ML';
/* 2020-04-07-133 */	UPDATE `countries` SET `country_code3` = 'MLT' WHERE `country_code` = 'MT';
/* 2020-04-07-134 */	UPDATE `countries` SET `country_code3` = 'MHL' WHERE `country_code` = 'MH';
/* 2020-04-07-135 */	UPDATE `countries` SET `country_code3` = 'MTQ' WHERE `country_code` = 'MQ';
/* 2020-04-07-136 */	UPDATE `countries` SET `country_code3` = 'MRT' WHERE `country_code` = 'MR';
/* 2020-04-07-137 */	UPDATE `countries` SET `country_code3` = 'MUS' WHERE `country_code` = 'MU';
/* 2020-04-07-138 */	UPDATE `countries` SET `country_code3` = 'MYT' WHERE `country_code` = 'YT';
/* 2020-04-07-139 */	UPDATE `countries` SET `country_code3` = 'MEX' WHERE `country_code` = 'MX';
/* 2020-04-07-140 */	UPDATE `countries` SET `country_code3` = 'FSM' WHERE `country_code` = 'FM';
/* 2020-04-07-141 */	UPDATE `countries` SET `country_code3` = 'MDA', `country` = 'Moldova' WHERE `country_code` = 'MD';
/* 2020-04-07-142 */	UPDATE `countries` SET `country_code3` = 'MCO' WHERE `country_code` = 'MC';
/* 2020-04-07-143 */	UPDATE `countries` SET `country_code3` = 'MNG' WHERE `country_code` = 'MN';
/* 2020-04-07-144 */	UPDATE `countries` SET `country_code3` = 'MSR' WHERE `country_code` = 'MS';
/* 2020-04-07-145 */	UPDATE `countries` SET `country_code3` = 'MAR' WHERE `country_code` = 'MA';
/* 2020-04-07-146 */	UPDATE `countries` SET `country_code3` = 'MOZ' WHERE `country_code` = 'MZ';
/* 2020-04-07-147 */	UPDATE `countries` SET `country_code3` = 'MMR' WHERE `country_code` = 'MM';
/* 2020-04-07-148 */	UPDATE `countries` SET `country_code3` = 'NAM' WHERE `country_code` = 'NA';
/* 2020-04-07-149 */	UPDATE `countries` SET `country_code3` = 'NRU' WHERE `country_code` = 'NR';
/* 2020-04-07-150 */	UPDATE `countries` SET `country_code3` = 'NPL' WHERE `country_code` = 'NP';
/* 2020-04-07-151 */	UPDATE `countries` SET `country_code3` = 'NLD' WHERE `country_code` = 'NL';
/* 2020-04-07-152 */	DELETE FROM `countries` WHERE `country_code` = 'AN';
/* 2020-04-07-153 */	UPDATE `countries` SET `country_code3` = 'NCL' WHERE `country_code` = 'NC';
/* 2020-04-07-154 */	UPDATE `countries` SET `country_code3` = 'NZL' WHERE `country_code` = 'NZ';
/* 2020-04-07-155 */	UPDATE `countries` SET `country_code3` = 'NIC' WHERE `country_code` = 'NI';
/* 2020-04-07-156 */	UPDATE `countries` SET `country_code3` = 'NER' WHERE `country_code` = 'NE';
/* 2020-04-07-157 */	UPDATE `countries` SET `country_code3` = 'NGA' WHERE `country_code` = 'NG';
/* 2020-04-07-158 */	UPDATE `countries` SET `country_code3` = 'NIU' WHERE `country_code` = 'NU';
/* 2020-04-07-159 */	UPDATE `countries` SET `country_code3` = 'NFK' WHERE `country_code` = 'NF';
/* 2020-04-07-160 */	UPDATE `countries` SET `country_code3` = 'MNP' WHERE `country_code` = 'MP';
/* 2020-04-07-161 */	UPDATE `countries` SET `country_code3` = 'NOR' WHERE `country_code` = 'NO';
/* 2020-04-07-162 */	UPDATE `countries` SET `country_code3` = 'OMN' WHERE `country_code` = 'OM';
/* 2020-04-07-163 */	UPDATE `countries` SET `country_code3` = 'PAK' WHERE `country_code` = 'PK';
/* 2020-04-07-164 */	UPDATE `countries` SET `country_code3` = 'PLW' WHERE `country_code` = 'PW';
/* 2020-04-07-165 */	UPDATE `countries` SET `country_code3` = 'PSE', `country` = 'Palestine' WHERE `country_code` = 'PS';
/* 2020-04-07-166 */	UPDATE `countries` SET `country_code3` = 'PAN' WHERE `country_code` = 'PA';
/* 2020-04-07-167 */	UPDATE `countries` SET `country_code3` = 'PNG' WHERE `country_code` = 'PG';
/* 2020-04-07-168 */	UPDATE `countries` SET `country_code3` = 'PRY' WHERE `country_code` = 'PY';
/* 2020-04-07-169 */	UPDATE `countries` SET `country_code3` = 'PER' WHERE `country_code` = 'PE';
/* 2020-04-07-170 */	UPDATE `countries` SET `country_code3` = 'PHL' WHERE `country_code` = 'PH';
/* 2020-04-07-171 */	UPDATE `countries` SET `country_code3` = 'PCN' WHERE `country_code` = 'PN';
/* 2020-04-07-172 */	UPDATE `countries` SET `country_code3` = 'POL' WHERE `country_code` = 'PL';
/* 2020-04-07-173 */	UPDATE `countries` SET `country_code3` = 'PRT' WHERE `country_code` = 'PT';
/* 2020-04-07-174 */	UPDATE `countries` SET `country_code3` = 'PRI' WHERE `country_code` = 'PR';
/* 2020-04-07-175 */	UPDATE `countries` SET `country_code3` = 'QAT' WHERE `country_code` = 'QA';
/* 2020-04-07-176 */	UPDATE `countries` SET `country_code3` = 'REU', `country` = 'Réunion'  WHERE `country_code` = 'RE';
/* 2020-04-07-177 */	UPDATE `countries` SET `country_code3` = 'ROU' WHERE `country_code` = 'RO';
/* 2020-04-07-178 */	UPDATE `countries` SET `country_code3` = 'RUS' WHERE `country_code` = 'RU';
/* 2020-04-07-179 */	UPDATE `countries` SET `country_code3` = 'RWA' WHERE `country_code` = 'RW';
/* 2020-04-07-180 */	UPDATE `countries` SET `country_code3` = 'SHN' WHERE `country_code` = 'SH';
/* 2020-04-07-181 */	UPDATE `countries` SET `country_code3` = 'KNA' WHERE `country_code` = 'KN';
/* 2020-04-07-182 */	UPDATE `countries` SET `country_code3` = 'LCA' WHERE `country_code` = 'LC';
/* 2020-04-07-183 */	UPDATE `countries` SET `country_code3` = 'SPM' WHERE `country_code` = 'PM';
/* 2020-04-07-184 */	UPDATE `countries` SET `country_code3` = 'VCT', `country` = 'Saint Vincent and the Grenadines' WHERE `country_code` = 'VC';
/* 2020-04-07-185 */	UPDATE `countries` SET `country_code3` = 'WSM' WHERE `country_code` = 'WS';
/* 2020-04-07-186 */	UPDATE `countries` SET `country_code3` = 'SMR' WHERE `country_code` = 'SM';
/* 2020-04-07-187 */	UPDATE `countries` SET `country_code3` = 'STP', `country` = 'São Tomé and Príncipe' WHERE `country_code` = 'ST';
/* 2020-04-07-188 */	UPDATE `countries` SET `country_code3` = 'SAU' WHERE `country_code` = 'SA';
/* 2020-04-07-189 */	UPDATE `countries` SET `country_code3` = 'SEN' WHERE `country_code` = 'SN';
/* 2020-04-07-190 */	UPDATE `countries` SET `country_code3` = 'SRB', `country` = 'Serbia', `country_code` = 'RS' WHERE `country_code` = 'CS';
/* 2020-04-07-191 */	UPDATE `countries` SET `country_code3` = 'SYC' WHERE `country_code` = 'SC';
/* 2020-04-07-192 */	UPDATE `countries` SET `country_code3` = 'SLE' WHERE `country_code` = 'SL';
/* 2020-04-07-193 */	UPDATE `countries` SET `country_code3` = 'SGP' WHERE `country_code` = 'SG';
/* 2020-04-07-194 */	UPDATE `countries` SET `country_code3` = 'SVK' WHERE `country_code` = 'SK';
/* 2020-04-07-195 */	UPDATE `countries` SET `country_code3` = 'SVN' WHERE `country_code` = 'SI';
/* 2020-04-07-196 */	UPDATE `countries` SET `country_code3` = 'SLB' WHERE `country_code` = 'SB';
/* 2020-04-07-197 */	UPDATE `countries` SET `country_code3` = 'SOM' WHERE `country_code` = 'SO';
/* 2020-04-07-198 */	UPDATE `countries` SET `country_code3` = 'ZAF' WHERE `country_code` = 'ZA';
/* 2020-04-07-199 */	UPDATE `countries` SET `country_code3` = 'SGS' WHERE `country_code` = 'GS';
/* 2020-04-07-200 */	UPDATE `countries` SET `country_code3` = 'ESP' WHERE `country_code` = 'ES';
/* 2020-04-07-201 */	UPDATE `countries` SET `country_code3` = 'LKA' WHERE `country_code` = 'LK';
/* 2020-04-07-202 */	UPDATE `countries` SET `country_code3` = 'SDN' WHERE `country_code` = 'SD';
/* 2020-04-07-203 */	UPDATE `countries` SET `country_code3` = 'SUR' WHERE `country_code` = 'SR';
/* 2020-04-07-204 */	UPDATE `countries` SET `country_code3` = 'SJM' WHERE `country_code` = 'SJ';
/* 2020-04-07-205 */	UPDATE `countries` SET `country_code3` = 'SWZ', `country` = 'Eswatini' WHERE `country_code` = 'SZ';
/* 2020-04-07-206 */	UPDATE `countries` SET `country_code3` = 'SWE' WHERE `country_code` = 'SE';
/* 2020-04-07-207 */	UPDATE `countries` SET `country_code3` = 'CHE' WHERE `country_code` = 'CH';
/* 2020-04-07-208 */	UPDATE `countries` SET `country_code3` = 'SYR', `country` = 'Syria' WHERE `country_code` = 'SY';
/* 2020-04-07-209 */	UPDATE `countries` SET `country_code3` = 'TWN', `country` = 'Taiwan' WHERE `country_code` = 'TW';
/* 2020-04-07-210 */	UPDATE `countries` SET `country_code3` = 'TJK' WHERE `country_code` = 'TJ';
/* 2020-04-07-211 */	UPDATE `countries` SET `country_code3` = 'TZA', `country` = 'Tanzania' WHERE `country_code` = 'TZ';
/* 2020-04-07-212 */	UPDATE `countries` SET `country_code3` = 'THA' WHERE `country_code` = 'TH';
/* 2020-04-07-213 */	UPDATE `countries` SET `country_code3` = 'TLS' WHERE `country_code` = 'TL';
/* 2020-04-07-214 */	UPDATE `countries` SET `country_code3` = 'TGO' WHERE `country_code` = 'TG';
/* 2020-04-07-215 */	UPDATE `countries` SET `country_code3` = 'TKL' WHERE `country_code` = 'TK';
/* 2020-04-07-216 */	UPDATE `countries` SET `country_code3` = 'TON' WHERE `country_code` = 'TO';
/* 2020-04-07-217 */	UPDATE `countries` SET `country_code3` = 'TTO' WHERE `country_code` = 'TT';
/* 2020-04-07-218 */	UPDATE `countries` SET `country_code3` = 'TUN' WHERE `country_code` = 'TN';
/* 2020-04-07-219 */	UPDATE `countries` SET `country_code3` = 'TUR' WHERE `country_code` = 'TR';
/* 2020-04-07-220 */	UPDATE `countries` SET `country_code3` = 'TKM' WHERE `country_code` = 'TM';
/* 2020-04-07-221 */	UPDATE `countries` SET `country_code3` = 'TCA', `country` = 'Turks and Caicos Islands' WHERE `country_code` = 'TC';
/* 2020-04-07-222 */	UPDATE `countries` SET `country_code3` = 'TUV' WHERE `country_code` = 'TV';
/* 2020-04-07-223 */	UPDATE `countries` SET `country_code3` = 'UGA' WHERE `country_code` = 'UG';
/* 2020-04-07-224 */	UPDATE `countries` SET `country_code3` = 'UKR' WHERE `country_code` = 'UA';
/* 2020-04-07-225 */	UPDATE `countries` SET `country_code3` = 'ARE' WHERE `country_code` = 'AE';
/* 2020-04-07-226 */	UPDATE `countries` SET `country_code3` = 'GBR' WHERE `country_code` = 'GB';
/* 2020-04-07-227 */	UPDATE `countries` SET `country_code3` = 'USA' WHERE `country_code` = 'US';
/* 2020-04-07-228 */	UPDATE `countries` SET `country_code3` = 'UMI' WHERE `country_code` = 'UM';
/* 2020-04-07-229 */	UPDATE `countries` SET `country_code3` = 'URY' WHERE `country_code` = 'UY';
/* 2020-04-07-230 */	UPDATE `countries` SET `country_code3` = 'UZB' WHERE `country_code` = 'UZ';
/* 2020-04-07-231 */	UPDATE `countries` SET `country_code3` = 'VUT' WHERE `country_code` = 'VU';
/* 2020-04-07-232 */	UPDATE `countries` SET `country_code3` = 'VEN' WHERE `country_code` = 'VE';
/* 2020-04-07-233 */	UPDATE `countries` SET `country_code3` = 'VNM' WHERE `country_code` = 'VN';
/* 2020-04-07-234 */	UPDATE `countries` SET `country_code3` = 'VGB' WHERE `country_code` = 'VG';
/* 2020-04-07-235 */	UPDATE `countries` SET `country_code3` = 'VIR' WHERE `country_code` = 'VI';
/* 2020-04-07-236 */	UPDATE `countries` SET `country_code3` = 'WLF', `country` = 'Wallis and Futuna' WHERE `country_code` = 'WF';
/* 2020-04-07-237 */	UPDATE `countries` SET `country_code3` = 'ESH' WHERE `country_code` = 'EH';
/* 2020-04-07-238 */	UPDATE `countries` SET `country_code3` = 'YEM' WHERE `country_code` = 'YE';
/* 2020-04-07-239 */	UPDATE `countries` SET `country_code3` = 'ZMB' WHERE `country_code` = 'ZM';
/* 2020-04-07-240 */	UPDATE `countries` SET `country_code3` = 'ZWE' WHERE `country_code` = 'ZW';
/* 2020-04-07-241 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('ME', 'MNE', 'Montenegro');
/* 2020-04-07-242 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('SS', 'SSD', 'South Sudan');
/* 2020-04-07-243 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('AX', 'ALA', 'Åland Islands');
/* 2020-04-07-244 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba');
/* 2020-04-07-245 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('BL', 'BLM', 'Saint Barthélemy');
/* 2020-04-07-246 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('CW', 'CUW', 'Curaçao');
/* 2020-04-07-247 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('GG', 'GGY', 'Guernsey');
/* 2020-04-07-248 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('IM', 'IMN', 'Isle of Man');
/* 2020-04-07-249 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('JE', 'JEY', 'Jersey');
/* 2020-04-07-250 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('MF', 'MAF', 'Saint Martin (French part)');
/* 2020-04-07-251 */	INSERT INTO `countries` (`country_code`, `country_code3`, `country`) VALUES ('SX', 'SXM', 'Sint Maarten (Dutch part)');
/* 2020-04-07-252 */	INSERT INTO _translationfields (db_name, table_name, field_name, field_type) SELECT DATABASE(), 'countries', 'country', 'varchar';
/* 2020-04-07-253 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Vereinigte Arabische Emirate', 105 FROM countries WHERE country_code = 'AE';
/* 2020-04-07-254 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Antigua und Barbuda', 105 FROM countries WHERE country_code = 'AG';
/* 2020-04-07-255 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Albanien', 105 FROM countries WHERE country_code = 'AL';
/* 2020-04-07-256 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Armenien', 105 FROM countries WHERE country_code = 'AM';
/* 2020-04-07-257 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Åland', 105 FROM countries WHERE country_code = 'AX';
/* 2020-04-07-258 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Antarktis', 105 FROM countries WHERE country_code = 'AQ';
/* 2020-04-07-259 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Argentinien', 105 FROM countries WHERE country_code = 'AR';
/* 2020-04-07-260 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Amerikanisch-Samoa', 105 FROM countries WHERE country_code = 'AS';
/* 2020-04-07-261 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Österreich', 105 FROM countries WHERE country_code = 'AT';
/* 2020-04-07-262 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Australien', 105 FROM countries WHERE country_code = 'AU';
/* 2020-04-07-263 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Aserbeidschan', 105 FROM countries WHERE country_code = 'AZ';
/* 2020-04-07-264 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Bosnien und Herzegowina', 105 FROM countries WHERE country_code = 'BA';
/* 2020-04-07-265 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Bangladesch', 105 FROM countries WHERE country_code = 'BD';
/* 2020-04-07-266 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Belgien', 105 FROM countries WHERE country_code = 'BE';
/* 2020-04-07-267 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Bulgarien', 105 FROM countries WHERE country_code = 'BG';
/* 2020-04-07-268 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Bolivien', 105 FROM countries WHERE country_code = 'BO';
/* 2020-04-07-269 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Brasilien', 105 FROM countries WHERE country_code = 'BR';
/* 2020-04-07-270 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Bouvetinsel', 105 FROM countries WHERE country_code = 'BV';
/* 2020-04-07-271 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kanada', 105 FROM countries WHERE country_code = 'CA';
/* 2020-04-07-272 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kokosinseln', 105 FROM countries WHERE country_code = 'CC';
/* 2020-04-07-273 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kongo, Demokratische Republik', 105 FROM countries WHERE country_code = 'CD';
/* 2020-04-07-274 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Zentralafrikanische Republik', 105 FROM countries WHERE country_code = 'CF';
/* 2020-04-07-275 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kongo', 105 FROM countries WHERE country_code = 'CG';
/* 2020-04-07-276 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Schweiz', 105 FROM countries WHERE country_code = 'CH';
/* 2020-04-07-277 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Elfenbeinküste', 105 FROM countries WHERE country_code = 'CI';
/* 2020-04-07-278 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Cookinseln', 105 FROM countries WHERE country_code = 'CK';
/* 2020-04-07-279 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kamerun', 105 FROM countries WHERE country_code = 'CM';
/* 2020-04-07-280 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kolumbien', 105 FROM countries WHERE country_code = 'CO';
/* 2020-04-07-281 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Serbien', 105 FROM countries WHERE country_code = 'RS';
/* 2020-04-07-282 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kap Verde', 105 FROM countries WHERE country_code = 'CV';
/* 2020-04-07-283 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Weihnachtsinsel', 105 FROM countries WHERE country_code = 'CX';
/* 2020-04-07-284 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Zypern', 105 FROM countries WHERE country_code = 'CY';
/* 2020-04-07-285 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Tschechien', 105 FROM countries WHERE country_code = 'CZ';
/* 2020-04-07-286 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Deutschland', 105 FROM countries WHERE country_code = 'DE';
/* 2020-04-07-287 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Dschibuti', 105 FROM countries WHERE country_code = 'DJ';
/* 2020-04-07-288 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Dänemark', 105 FROM countries WHERE country_code = 'DK';
/* 2020-04-07-289 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Dominikanische Republik', 105 FROM countries WHERE country_code = 'DO';
/* 2020-04-07-290 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Algerien', 105 FROM countries WHERE country_code = 'DZ';
/* 2020-04-07-291 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Estland', 105 FROM countries WHERE country_code = 'EE';
/* 2020-04-07-292 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Ägypten', 105 FROM countries WHERE country_code = 'EG';
/* 2020-04-07-293 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Westsahara', 105 FROM countries WHERE country_code = 'EH';
/* 2020-04-07-294 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Spanien', 105 FROM countries WHERE country_code = 'ES';
/* 2020-04-07-295 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Äthiopien', 105 FROM countries WHERE country_code = 'ET';
/* 2020-04-07-296 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Finnland', 105 FROM countries WHERE country_code = 'FI';
/* 2020-04-07-297 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Falklandinseln', 105 FROM countries WHERE country_code = 'FK';
/* 2020-04-07-298 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Mikronesien, Föderierte Staaten von', 105 FROM countries WHERE country_code = 'FM';
/* 2020-04-07-299 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Färöer', 105 FROM countries WHERE country_code = 'FO';
/* 2020-04-07-300 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Frankreich', 105 FROM countries WHERE country_code = 'FR';
/* 2020-04-07-301 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Gabun', 105 FROM countries WHERE country_code = 'GA';
/* 2020-04-07-302 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Vereinigtes Königreich', 105 FROM countries WHERE country_code = 'GB';
/* 2020-04-07-303 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Georgien', 105 FROM countries WHERE country_code = 'GE';
/* 2020-04-07-304 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Französisch-Guayana', 105 FROM countries WHERE country_code = 'GF';
/* 2020-04-07-305 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Grönland', 105 FROM countries WHERE country_code = 'GL';
/* 2020-04-07-306 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Äquatorialguinea', 105 FROM countries WHERE country_code = 'GQ';
/* 2020-04-07-307 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Griechenland', 105 FROM countries WHERE country_code = 'GR';
/* 2020-04-07-308 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Südgeorgien und die Südlichen Sandwichinseln', 105 FROM countries WHERE country_code = 'GS';
/* 2020-04-07-309 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Heard und McDonaldinseln', 105 FROM countries WHERE country_code = 'HM';
/* 2020-04-07-310 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kroatien', 105 FROM countries WHERE country_code = 'HR';
/* 2020-04-07-311 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Ungarn', 105 FROM countries WHERE country_code = 'HU';
/* 2020-04-07-312 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Indonesien', 105 FROM countries WHERE country_code = 'ID';
/* 2020-04-07-313 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Irland', 105 FROM countries WHERE country_code = 'IE';
/* 2020-04-07-314 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Indien', 105 FROM countries WHERE country_code = 'IN';
/* 2020-04-07-315 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Britisches Territorium im Indischen Ozean', 105 FROM countries WHERE country_code = 'IO';
/* 2020-04-07-316 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Irak', 105 FROM countries WHERE country_code = 'IQ';
/* 2020-04-07-317 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Iran', 105 FROM countries WHERE country_code = 'IR';
/* 2020-04-07-318 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Island', 105 FROM countries WHERE country_code = 'IS';
/* 2020-04-07-319 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Italien', 105 FROM countries WHERE country_code = 'IT';
/* 2020-04-07-320 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Jordanien', 105 FROM countries WHERE country_code = 'JO';
/* 2020-04-07-321 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Jamaika', 105 FROM countries WHERE country_code = 'JM';
/* 2020-04-07-322 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kenia', 105 FROM countries WHERE country_code = 'KE';
/* 2020-04-07-323 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kirgistan', 105 FROM countries WHERE country_code = 'KG';
/* 2020-04-07-324 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kambodscha', 105 FROM countries WHERE country_code = 'KH';
/* 2020-04-07-325 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Komoren', 105 FROM countries WHERE country_code = 'KM';
/* 2020-04-07-326 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'St. Kitts und Nevis', 105 FROM countries WHERE country_code = 'KN';
/* 2020-04-07-327 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Korea, Demokratische Volksrepublik', 105 FROM countries WHERE country_code = 'KP';
/* 2020-04-07-328 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Korea, Republik', 105 FROM countries WHERE country_code = 'KR';
/* 2020-04-07-329 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Kasachstan', 105 FROM countries WHERE country_code = 'KZ';
/* 2020-04-07-330 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Libanon', 105 FROM countries WHERE country_code = 'LB';
/* 2020-04-07-331 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Lettland', 105 FROM countries WHERE country_code = 'LV';
/* 2020-04-07-332 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Luxemburg', 105 FROM countries WHERE country_code = 'LU';
/* 2020-04-07-333 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Litauen', 105 FROM countries WHERE country_code = 'LT';
/* 2020-04-07-334 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Libyen', 105 FROM countries WHERE country_code = 'LY';
/* 2020-04-07-335 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Marokko', 105 FROM countries WHERE country_code = 'MA';
/* 2020-04-07-336 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Moldau', 105 FROM countries WHERE country_code = 'MD';
/* 2020-04-07-337 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Madagaskar', 105 FROM countries WHERE country_code = 'MG';
/* 2020-04-07-338 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Marshallinseln', 105 FROM countries WHERE country_code = 'MH';
/* 2020-04-07-339 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Nordmazedonien', 105 FROM countries WHERE country_code = 'MK';
/* 2020-04-07-340 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Mongolei', 105 FROM countries WHERE country_code = 'MN';
/* 2020-04-07-341 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Nördliche Marianen', 105 FROM countries WHERE country_code = 'MP';
/* 2020-04-07-342 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Mauretanien', 105 FROM countries WHERE country_code = 'MR';
/* 2020-04-07-343 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Malediven', 105 FROM countries WHERE country_code = 'MV';
/* 2020-04-07-344 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Mexiko', 105 FROM countries WHERE country_code = 'MX';
/* 2020-04-07-345 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Mosambik', 105 FROM countries WHERE country_code = 'MZ';
/* 2020-04-07-346 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Neukaledonien', 105 FROM countries WHERE country_code = 'NC';
/* 2020-04-07-347 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Norfolkinsel', 105 FROM countries WHERE country_code = 'NF';
/* 2020-04-07-348 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Niederlande', 105 FROM countries WHERE country_code = 'NL';
/* 2020-04-07-349 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Norwegen', 105 FROM countries WHERE country_code = 'NO';
/* 2020-04-07-350 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Neuseeland', 105 FROM countries WHERE country_code = 'NZ';
/* 2020-04-07-351 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Französisch-Polynesien', 105 FROM countries WHERE country_code = 'PF';
/* 2020-04-07-352 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Papua-Neuguinea', 105 FROM countries WHERE country_code = 'PG';
/* 2020-04-07-353 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Philippinen', 105 FROM countries WHERE country_code = 'PH';
/* 2020-04-07-354 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Polen', 105 FROM countries WHERE country_code = 'PL';
/* 2020-04-07-355 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Saint-Pierre und Miquelon', 105 FROM countries WHERE country_code = 'PM';
/* 2020-04-07-356 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Palästina', 105 FROM countries WHERE country_code = 'PS';
/* 2020-04-07-357 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Katar', 105 FROM countries WHERE country_code = 'QA';
/* 2020-04-07-358 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Rumänien', 105 FROM countries WHERE country_code = 'RO';
/* 2020-04-07-359 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Russland', 105 FROM countries WHERE country_code = 'RU';
/* 2020-04-07-360 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Ruanda', 105 FROM countries WHERE country_code = 'RW';
/* 2020-04-07-361 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Saudi-Arabien', 105 FROM countries WHERE country_code = 'SA';
/* 2020-04-07-362 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Salomonen', 105 FROM countries WHERE country_code = 'SB';
/* 2020-04-07-363 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Seychellen', 105 FROM countries WHERE country_code = 'SC';
/* 2020-04-07-364 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Schweden', 105 FROM countries WHERE country_code = 'SE';
/* 2020-04-07-365 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Singapur', 105 FROM countries WHERE country_code = 'SG';
/* 2020-04-07-366 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'St. Helena', 105 FROM countries WHERE country_code = 'SH';
/* 2020-04-07-367 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Slowenien', 105 FROM countries WHERE country_code = 'SI';
/* 2020-04-07-368 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Spitzbergen und Jan Mayen', 105 FROM countries WHERE country_code = 'SJ';
/* 2020-04-07-369 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Slowakei', 105 FROM countries WHERE country_code = 'SK';
/* 2020-04-07-370 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Surinam', 105 FROM countries WHERE country_code = 'SR';
/* 2020-04-07-371 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Südsudan', 105 FROM countries WHERE country_code = 'SS';
/* 2020-04-07-372 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'São Tomé und Príncipe', 105 FROM countries WHERE country_code = 'ST';
/* 2020-04-07-373 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Syrien', 105 FROM countries WHERE country_code = 'SY';
/* 2020-04-07-374 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Swasiland', 105 FROM countries WHERE country_code = 'SZ';
/* 2020-04-07-375 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Turks- und Caicosinseln', 105 FROM countries WHERE country_code = 'TC';
/* 2020-04-07-376 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Tschad', 105 FROM countries WHERE country_code = 'TD';
/* 2020-04-07-377 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Französische Südgebiete', 105 FROM countries WHERE country_code = 'TF';
/* 2020-04-07-378 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Tadschikistan', 105 FROM countries WHERE country_code = 'TJ';
/* 2020-04-07-379 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Osttimor', 105 FROM countries WHERE country_code = 'TL';
/* 2020-04-07-380 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Tunesien', 105 FROM countries WHERE country_code = 'TN';
/* 2020-04-07-381 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Türkei', 105 FROM countries WHERE country_code = 'TR';
/* 2020-04-07-382 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Trinidad und Tobago', 105 FROM countries WHERE country_code = 'TT';
/* 2020-04-07-383 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Tansania', 105 FROM countries WHERE country_code = 'TZ';
/* 2020-04-07-384 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Vereinigte Staaten', 105 FROM countries WHERE country_code = 'US';
/* 2020-04-07-385 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Usbekistan', 105 FROM countries WHERE country_code = 'UZ';
/* 2020-04-07-386 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Vatikanstadt', 105 FROM countries WHERE country_code = 'VA';
/* 2020-04-07-387 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'St. Vincent und die Grenadinen', 105 FROM countries WHERE country_code = 'VC';
/* 2020-04-07-388 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Britische Jungferninseln', 105 FROM countries WHERE country_code = 'VG';
/* 2020-04-07-389 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Amerikanische Jungferninseln', 105 FROM countries WHERE country_code = 'VI';
/* 2020-04-07-390 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Vietnam', 105 FROM countries WHERE country_code = 'VN';
/* 2020-04-07-391 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Wallis und Futuna', 105 FROM countries WHERE country_code = 'WF';
/* 2020-04-07-392 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Jemen', 105 FROM countries WHERE country_code = 'YE';
/* 2020-04-07-393 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Südafrika', 105 FROM countries WHERE country_code = 'ZA';
/* 2020-04-07-394 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Sambia', 105 FROM countries WHERE country_code = 'ZM';
/* 2020-04-07-395 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Simbabwe', 105 FROM countries WHERE country_code = 'ZW';
/* 2020-04-07-396 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Karibische Niederlande', 105 FROM countries WHERE country_code = 'BQ';
/* 2020-04-07-397 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Saint Martin (Französischer Teil)', 105 FROM countries WHERE country_code = 'MF';
/* 2020-04-07-398 */	INSERT INTO _translations_varchar (translationfield_id, field_id, translation, language_id) SELECT (SELECT translationfield_id FROM _translationfields WHERE table_name = 'countries' AND field_name = 'country' AND field_type = "varchar"), country_id, 'Sint Maarten (Holländischer Teil)', 105 FROM countries WHERE country_code = 'SX';
/* 2020-04-10-1 */	ALTER TABLE `_logging` ADD INDEX `last_update` (`last_update`);
