/**
 * default module
 * SQL for installation
 *
 * Part of »Zugzwang Project«
 * https://www.zugzwang.org/modules/default
 *
 * @author Gustaf Mossakowski <gustaf@koenige.org>
 * @copyright Copyright © 2020-2026 Gustaf Mossakowski
 * @license http://opensource.org/licenses/lgpl-3.0.html LGPL-3.0
 */


-- _logging --
CREATE TABLE `_logging` (
  `log_id` int unsigned NOT NULL AUTO_INCREMENT,
  `query` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `record_id` int unsigned DEFAULT NULL,
  `user` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `record_id` (`record_id`),
  KEY `last_update` (`last_update`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- _cronjobs --
CREATE TABLE `_cronjobs` (
  `cronjob_id` int unsigned NOT NULL AUTO_INCREMENT,
  `cronjob` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `url` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `active` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'yes',
  `job_minute` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `job_hour` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `job_day` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `job_month` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `job_weekday` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `sequence` smallint unsigned DEFAULT NULL,
  PRIMARY KEY (`cronjob_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- _relations --
CREATE TABLE `_relations` (
  `rel_id` int unsigned NOT NULL AUTO_INCREMENT,
  `master_db` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `master_table` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `master_field` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `detail_db` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `detail_table` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `detail_field` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `delete` enum('delete','ask','no-delete','update') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no-delete',
  `detail_id_field` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `detail_url` varchar(63) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  PRIMARY KEY (`rel_id`),
  UNIQUE KEY `master_db` (`master_db`,`master_table`,`master_field`,`detail_db`,`detail_table`,`detail_field`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;


-- _settings --
CREATE TABLE `_settings` (
  `setting_id` int unsigned NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(100) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `setting_value` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `explanation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `website_id` int unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`setting_id`),
  UNIQUE KEY `setting_key_website_id` (`setting_key`,`website_id`),
  KEY `website_id` (`website_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'websites', 'website_id', (SELECT DATABASE()), '_settings', 'setting_id', 'website_id', 'delete');


-- _translationfields --
CREATE TABLE `_translationfields` (
  `translationfield_id` int unsigned NOT NULL AUTO_INCREMENT,
  `db_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `table_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `field_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `field_type` enum('varchar','text') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'varchar',
  PRIMARY KEY (`translationfield_id`),
  UNIQUE KEY `db_name` (`db_name`,`table_name`,`field_name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

INSERT INTO `_translationfields` (`translationfield_id`, `db_name`, `table_name`, `field_name`, `field_type`) VALUES
(1,	(SELECT DATABASE()),	'text',	'text',	'varchar'),
(2,	(SELECT DATABASE()),	'countries',	'country',	'varchar');


-- _translations_text --
CREATE TABLE `_translations_text` (
  `translation_id` int unsigned NOT NULL AUTO_INCREMENT,
  `translationfield_id` int unsigned NOT NULL,
  `field_id` int unsigned NOT NULL,
  `translation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `language_id` int unsigned NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`translation_id`),
  UNIQUE KEY `field_id` (`field_id`,`translationfield_id`,`language_id`),
  KEY `language_id` (`language_id`),
  KEY `translationfield_id` (`translationfield_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'languages', 'language_id', (SELECT DATABASE()), '_translations_text', 'translation_id', 'language_id', 'no-delete');
INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), '_translationfields', 'translationfield_id', (SELECT DATABASE()), '_translations_text', 'translation_id', 'translationfield_id', 'no-delete');


-- _translations_varchar --
CREATE TABLE `_translations_varchar` (
  `translation_id` int unsigned NOT NULL AUTO_INCREMENT,
  `translationfield_id` int unsigned NOT NULL,
  `field_id` int unsigned NOT NULL,
  `translation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `language_id` int unsigned NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`translation_id`),
  UNIQUE KEY `field_id` (`field_id`,`translationfield_id`,`language_id`),
  KEY `translationfield_id` (`translationfield_id`),
  KEY `language_id` (`language_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'languages', 'language_id', (SELECT DATABASE()), '_translations_varchar', 'translation_id', 'language_id', 'no-delete');
INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), '_translationfields', 'translationfield_id', (SELECT DATABASE()), '_translations_varchar', 'translation_id', 'translationfield_id', 'no-delete');


INSERT INTO `_translations_varchar` (`translation_id`, `translationfield_id`, `field_id`, `translation`, `language_id`, `last_update`) VALUES
(1,	2,	224,	'Vereinigte Arabische Emirate',	105,	NOW()),
(2,	2,	9,	'Antigua und Barbuda',	105,	NOW()),
(3,	2,	2,	'Albanien',	105,	NOW()),
(4,	2,	11,	'Armenien',	105,	NOW()),
(5,	2,	242,	'Åland',	105,	NOW()),
(6,	2,	8,	'Antarktis',	105,	NOW()),
(7,	2,	10,	'Argentinien',	105,	NOW()),
(8,	2,	4,	'Amerikanisch-Samoa',	105,	NOW()),
(9,	2,	14,	'Österreich',	105,	NOW()),
(10,	2,	13,	'Australien',	105,	NOW()),
(11,	2,	15,	'Aserbaidschan',	105,	NOW()),
(12,	2,	27,	'Bosnien und Herzegowina',	105,	NOW()),
(13,	2,	18,	'Bangladesch',	105,	NOW()),
(14,	2,	21,	'Belgien',	105,	NOW()),
(15,	2,	33,	'Bulgarien',	105,	NOW()),
(16,	2,	26,	'Bolivien',	105,	NOW()),
(17,	2,	30,	'Brasilien',	105,	NOW()),
(18,	2,	29,	'Bouvetinsel',	105,	NOW()),
(19,	2,	38,	'Kanada',	105,	NOW()),
(20,	2,	46,	'Kokosinseln',	105,	NOW()),
(21,	2,	50,	'Kongo, Demokratische Republik',	105,	NOW()),
(22,	2,	41,	'Zentralafrikanische Republik',	105,	NOW()),
(23,	2,	49,	'Kongo',	105,	NOW()),
(24,	2,	206,	'Schweiz',	105,	NOW()),
(25,	2,	53,	'Côte d’Ivoire',	105,	NOW()),
(26,	2,	51,	'Cookinseln',	105,	NOW()),
(27,	2,	37,	'Kamerun',	105,	NOW()),
(28,	2,	47,	'Kolumbien',	105,	NOW()),
(29,	2,	189,	'Serbien',	105,	NOW()),
(30,	2,	39,	'Cabo Verde',	105,	NOW()),
(31,	2,	45,	'Weihnachtsinsel',	105,	NOW()),
(32,	2,	56,	'Zypern',	105,	NOW()),
(33,	2,	57,	'Tschechien',	105,	NOW()),
(34,	2,	80,	'Deutschland',	105,	NOW()),
(35,	2,	59,	'Dschibuti',	105,	NOW()),
(36,	2,	58,	'Dänemark',	105,	NOW()),
(37,	2,	61,	'Dominikanische Republik',	105,	NOW()),
(38,	2,	3,	'Algerien',	105,	NOW()),
(39,	2,	67,	'Estland',	105,	NOW()),
(40,	2,	63,	'Ägypten',	105,	NOW()),
(41,	2,	236,	'Westsahara',	105,	NOW()),
(42,	2,	199,	'Spanien',	105,	NOW()),
(43,	2,	68,	'Äthiopien',	105,	NOW()),
(44,	2,	72,	'Finnland',	105,	NOW()),
(45,	2,	69,	'Falklandinseln',	105,	NOW()),
(46,	2,	139,	'Mikronesien',	105,	NOW()),
(47,	2,	70,	'Färöer',	105,	NOW()),
(48,	2,	73,	'Frankreich',	105,	NOW()),
(49,	2,	77,	'Gabun',	105,	NOW()),
(50,	2,	225,	'Großbritannien',	105,	NOW()),
(51,	2,	79,	'Georgien',	105,	NOW()),
(52,	2,	74,	'Französisch-Guayana',	105,	NOW()),
(53,	2,	84,	'Grönland',	105,	NOW()),
(54,	2,	65,	'Äquatorialguinea',	105,	NOW()),
(55,	2,	83,	'Griechenland',	105,	NOW()),
(56,	2,	198,	'Südgeorgien und die Südlichen Sandwichinseln',	105,	NOW()),
(57,	2,	93,	'Heard und McDonaldinseln',	105,	NOW()),
(58,	2,	54,	'Kroatien',	105,	NOW()),
(59,	2,	97,	'Ungarn',	105,	NOW()),
(60,	2,	100,	'Indonesien',	105,	NOW()),
(61,	2,	103,	'Irland',	105,	NOW()),
(62,	2,	99,	'Indien',	105,	NOW()),
(63,	2,	31,	'Britisches Territorium im Indischen Ozean',	105,	NOW()),
(64,	2,	102,	'Irak',	105,	NOW()),
(65,	2,	101,	'Iran',	105,	NOW()),
(66,	2,	98,	'Island',	105,	NOW()),
(67,	2,	105,	'Italien',	105,	NOW()),
(68,	2,	108,	'Jordanien',	105,	NOW()),
(69,	2,	106,	'Jamaika',	105,	NOW()),
(70,	2,	110,	'Kenia',	105,	NOW()),
(71,	2,	115,	'Kirgisistan',	105,	NOW()),
(72,	2,	36,	'Kambodscha',	105,	NOW()),
(73,	2,	48,	'Komoren',	105,	NOW()),
(74,	2,	180,	'St. Kitts und Nevis',	105,	NOW()),
(75,	2,	112,	'Korea, Demokratische Volksrepublik',	105,	NOW()),
(76,	2,	113,	'Korea, Republik',	105,	NOW()),
(77,	2,	109,	'Kasachstan',	105,	NOW()),
(78,	2,	118,	'Libanon',	105,	NOW()),
(79,	2,	117,	'Lettland',	105,	NOW()),
(80,	2,	124,	'Luxemburg',	105,	NOW()),
(81,	2,	123,	'Litauen',	105,	NOW()),
(82,	2,	121,	'Libyen',	105,	NOW()),
(83,	2,	144,	'Marokko',	105,	NOW()),
(84,	2,	140,	'Moldau',	105,	NOW()),
(85,	2,	127,	'Madagaskar',	105,	NOW()),
(86,	2,	133,	'Marshallinseln',	105,	NOW()),
(87,	2,	126,	'Nordmazedonien',	105,	NOW()),
(88,	2,	142,	'Mongolei',	105,	NOW()),
(89,	2,	159,	'Nördliche Marianen',	105,	NOW()),
(90,	2,	135,	'Mauretanien',	105,	NOW()),
(91,	2,	130,	'Malediven',	105,	NOW()),
(92,	2,	138,	'Mexiko',	105,	NOW()),
(93,	2,	145,	'Mosambik',	105,	NOW()),
(94,	2,	152,	'Neukaledonien',	105,	NOW()),
(95,	2,	158,	'Norfolkinsel',	105,	NOW()),
(96,	2,	150,	'Niederlande',	105,	NOW()),
(97,	2,	160,	'Norwegen',	105,	NOW()),
(98,	2,	153,	'Neuseeland',	105,	NOW()),
(99,	2,	75,	'Französisch-Polynesien',	105,	NOW()),
(100,	2,	166,	'Papua-Neuguinea',	105,	NOW()),
(101,	2,	169,	'Philippinen',	105,	NOW()),
(102,	2,	171,	'Polen',	105,	NOW()),
(103,	2,	182,	'Saint-Pierre und Miquelon',	105,	NOW()),
(104,	2,	164,	'Palästina',	105,	NOW()),
(105,	2,	174,	'Katar',	105,	NOW()),
(106,	2,	176,	'Rumänien',	105,	NOW()),
(107,	2,	177,	'Russland',	105,	NOW()),
(108,	2,	178,	'Ruanda',	105,	NOW()),
(109,	2,	187,	'Saudi-Arabien',	105,	NOW()),
(110,	2,	195,	'Salomonen',	105,	NOW()),
(111,	2,	190,	'Seychellen',	105,	NOW()),
(112,	2,	205,	'Schweden',	105,	NOW()),
(113,	2,	192,	'Singapur',	105,	NOW()),
(114,	2,	179,	'St. Helena',	105,	NOW()),
(115,	2,	194,	'Slowenien',	105,	NOW()),
(116,	2,	203,	'Spitzbergen und Jan Mayen',	105,	NOW()),
(117,	2,	193,	'Slowakei',	105,	NOW()),
(118,	2,	202,	'Suriname',	105,	NOW()),
(119,	2,	241,	'Südsudan',	105,	NOW()),
(120,	2,	186,	'São Tomé und Príncipe',	105,	NOW()),
(121,	2,	207,	'Syrien',	105,	NOW()),
(122,	2,	204,	'Eswatini',	105,	NOW()),
(123,	2,	220,	'Turks- und Caicosinseln',	105,	NOW()),
(124,	2,	42,	'Tschad',	105,	NOW()),
(125,	2,	76,	'Französische Südgebiete',	105,	NOW()),
(126,	2,	209,	'Tadschikistan',	105,	NOW()),
(127,	2,	212,	'Timor-Leste',	105,	NOW()),
(128,	2,	217,	'Tunesien',	105,	NOW()),
(129,	2,	218,	'Türkei',	105,	NOW()),
(130,	2,	216,	'Trinidad und Tobago',	105,	NOW()),
(131,	2,	210,	'Tansania',	105,	NOW()),
(132,	2,	226,	'Vereinigte Staaten',	105,	NOW()),
(133,	2,	229,	'Usbekistan',	105,	NOW()),
(134,	2,	94,	'Vatikanstadt',	105,	NOW()),
(135,	2,	183,	'St. Vincent und die Grenadinen',	105,	NOW()),
(136,	2,	233,	'Britische Jungferninseln',	105,	NOW()),
(137,	2,	234,	'Amerikanische Jungferninseln',	105,	NOW()),
(138,	2,	232,	'Vietnam',	105,	NOW()),
(139,	2,	235,	'Wallis und Futuna',	105,	NOW()),
(140,	2,	237,	'Jemen',	105,	NOW()),
(141,	2,	197,	'Südafrika',	105,	NOW()),
(142,	2,	238,	'Sambia',	105,	NOW()),
(143,	2,	239,	'Simbabwe',	105,	NOW()),
(144,	2,	243,	'Karibische Niederlande',	105,	NOW()),
(145,	2,	249,	'Saint Martin (Französischer Teil)',	105,	NOW()),
(146,	2,	250,	'Sint Maarten (Holländischer Teil)',	105,	NOW()),
(147,	2,	28,	'Botsuana',	105,	NOW()),
(148,	2,	55,	'Kuba',	105,	NOW()),
(149,	2,	71,	'Fidschi',	105,	NOW()),
(150,	2,	181,	'St. Lucia',	105,	NOW());


-- _uris --
CREATE TABLE `_uris` (
  `uri_id` int unsigned NOT NULL AUTO_INCREMENT,
  `uri_scheme` varchar(15) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `uri_host` varchar(63) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `uri_path` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `uri_query` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `content_type` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `character_encoding` varchar(31) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `content_length` int unsigned NOT NULL,
  `user` varchar(64) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'none',
  `status_code` smallint NOT NULL,
  `etag_md5` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `hits` int unsigned NOT NULL,
  `first_access` datetime NOT NULL,
  `last_access` datetime NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uri_id`),
  UNIQUE KEY `uri_scheme_uri_host_uri_path_uri_query_user` (`uri_scheme`,`uri_host`,`uri_path`,`uri_query`,`user`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


-- categories --
CREATE TABLE `categories` (
  `category_id` int unsigned NOT NULL AUTO_INCREMENT,
  `category` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_short` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `main_category_id` int unsigned DEFAULT NULL,
  `path` varchar(100) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `parameters` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sequence` tinyint unsigned DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`),
  UNIQUE KEY `path` (`path`),
  KEY `main_category_id` (`main_category_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'categories', 'category_id', 'main_category_id', 'no-delete');


-- _jobqueue --
CREATE TABLE `_jobqueue` (
  `job_id` int unsigned NOT NULL AUTO_INCREMENT,
  `job_category_id` int unsigned NOT NULL,
  `job_url` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `username` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `postdata` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `priority` tinyint NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  `started` datetime DEFAULT NULL,
  `finished` datetime DEFAULT NULL,
  `wait_until` datetime DEFAULT NULL,
  `job_status` enum('not_started','running','successful','failed','abandoned','not_found') CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT 'not_started',
  `try_no` tinyint unsigned NOT NULL DEFAULT '0',
  `error_msg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `job_category_no` tinyint unsigned NOT NULL DEFAULT '1',
  `lock_hash` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `website_id` int unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`job_id`),
  UNIQUE KEY `job_category_id_job_url_started` (`job_category_id`,`job_url`,`started`),
  KEY `priority` (`priority`),
  KEY `website_id` (`website_id`),
  KEY `job_status` (`job_status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), '_jobqueue', 'job_id', 'job_category_id', 'no-delete');
INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'websites', 'website_id', (SELECT DATABASE()), '_jobqueue', 'job_id', 'website_id', 'delete');

INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Jobs', NULL, NULL, 'jobs', '&alias=jobs', NULL, NOW());
INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Background', NULL, (SELECT category_id FROM categories c WHERE path = 'jobs'), 'jobs/background', '&alias=jobs/background', NULL, NOW());


-- countries --
CREATE TABLE `countries` (
  `country_id` int unsigned NOT NULL AUTO_INCREMENT,
  `country_code` char(2) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `country_code3` char(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `ioc_code` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `country` varchar(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `website` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no',
  PRIMARY KEY (`country_id`),
  UNIQUE KEY `country_code` (`country_code`),
  KEY `website` (`website`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `countries` (`country_id`, `country_code`, `country_code3`, `country`, `website`) VALUES
(1,	'AF',	'AFG',	'Afghanistan',	'no'),
(2,	'AL',	'ALB',	'Albania',	'no'),
(3,	'DZ',	'DZA',	'Algeria',	'no'),
(4,	'AS',	'ASM',	'American Samoa',	'no'),
(5,	'AD',	'AND',	'Andorra',	'no'),
(6,	'AO',	'AGO',	'Angola',	'no'),
(7,	'AI',	'AIA',	'Anguilla',	'no'),
(8,	'AQ',	'ATA',	'Antarctica',	'no'),
(9,	'AG',	'ATG',	'Antigua and Barbuda',	'no'),
(10,	'AR',	'ARG',	'Argentina',	'no'),
(11,	'AM',	'ARM',	'Armenia',	'no'),
(12,	'AW',	'ABW',	'Aruba',	'no'),
(13,	'AU',	'AUS',	'Australia',	'no'),
(14,	'AT',	'AUT',	'Austria',	'no'),
(15,	'AZ',	'AZE',	'Azerbaijan',	'no'),
(16,	'BS',	'BHS',	'Bahamas',	'no'),
(17,	'BH',	'BHR',	'Bahrain',	'no'),
(18,	'BD',	'BGD',	'Bangladesh',	'no'),
(19,	'BB',	'BRB',	'Barbados',	'no'),
(20,	'BY',	'BLR',	'Belarus',	'yes'),
(21,	'BE',	'BEL',	'Belgium',	'no'),
(22,	'BZ',	'BLZ',	'Belize',	'no'),
(23,	'BJ',	'BEN',	'Benin',	'no'),
(24,	'BM',	'BMU',	'Bermuda',	'no'),
(25,	'BT',	'BTN',	'Bhutan',	'no'),
(26,	'BO',	'BOL',	'Bolivia',	'no'),
(27,	'BA',	'BIH',	'Bosnia and Herzegovina',	'no'),
(28,	'BW',	'BWA',	'Botswana',	'no'),
(29,	'BV',	'BVT',	'Bouvet Island',	'no'),
(30,	'BR',	'BRA',	'Brazil',	'no'),
(31,	'IO',	'IOT',	'British Indian Ocean Territory',	'no'),
(32,	'BN',	'BRN',	'Brunei Darussalam',	'no'),
(33,	'BG',	'BGR',	'Bulgaria',	'no'),
(34,	'BF',	'BFA',	'Burkina Faso',	'no'),
(35,	'BI',	'BDI',	'Burundi',	'no'),
(36,	'KH',	'KHM',	'Cambodia',	'no'),
(37,	'CM',	'CMR',	'Cameroon',	'no'),
(38,	'CA',	'CAN',	'Canada',	'no'),
(39,	'CV',	'CPV',	'Cape Verde',	'no'),
(40,	'KY',	'CYM',	'Cayman Islands',	'no'),
(41,	'CF',	'CAF',	'Central African Republic',	'no'),
(42,	'TD',	'TCD',	'Chad',	'no'),
(43,	'CL',	'CHL',	'Chile',	'no'),
(44,	'CN',	'CHN',	'China',	'no'),
(45,	'CX',	'CXR',	'Christmas Island',	'no'),
(46,	'CC',	'CCK',	'Cocos (Keeling) Islands',	'no'),
(47,	'CO',	'COL',	'Colombia',	'no'),
(48,	'KM',	'COM',	'Comoros',	'no'),
(49,	'CG',	'COG',	'Congo',	'no'),
(50,	'CD',	'COD',	'Congo, The Democratic Republic of the',	'no'),
(51,	'CK',	'COK',	'Cook Islands',	'no'),
(52,	'CR',	'CRI',	'Costa Rica',	'no'),
(53,	'CI',	'CIV',	'Cote D\'Ivoire',	'no'),
(54,	'HR',	'HRV',	'Croatia',	'no'),
(55,	'CU',	'CUB',	'Cuba',	'no'),
(56,	'CY',	'CYP',	'Cyprus',	'no'),
(57,	'CZ',	'CZE',	'Czechia',	'no'),
(58,	'DK',	'DNK',	'Denmark',	'no'),
(59,	'DJ',	'DJI',	'Djibouti',	'no'),
(60,	'DM',	'DMA',	'Dominica',	'no'),
(61,	'DO',	'DOM',	'Dominican Republic',	'no'),
(62,	'EC',	'ECU',	'Ecuador',	'no'),
(63,	'EG',	'EGY',	'Egypt',	'no'),
(64,	'SV',	'SLV',	'El Salvador',	'no'),
(65,	'GQ',	'GNQ',	'Equatorial Guinea',	'no'),
(66,	'ER',	'ERI',	'Eritrea',	'no'),
(67,	'EE',	'EST',	'Estonia',	'no'),
(68,	'ET',	'ETH',	'Ethiopia',	'no'),
(69,	'FK',	'FLK',	'Falkland Islands (Malvinas)',	'no'),
(70,	'FO',	'FRO',	'Faroe Islands',	'no'),
(71,	'FJ',	'FJI',	'Fiji',	'no'),
(72,	'FI',	'FIN',	'Finland',	'no'),
(73,	'FR',	'FRA',	'France',	'no'),
(74,	'GF',	'GUF',	'French Guiana',	'no'),
(75,	'PF',	'PYF',	'French Polynesia',	'no'),
(76,	'TF',	'ATF',	'French Southern Territories',	'no'),
(77,	'GA',	'GAB',	'Gabon',	'no'),
(78,	'GM',	'GMB',	'Gambia',	'no'),
(79,	'GE',	'GEO',	'Georgia',	'no'),
(80,	'DE',	'DEU',	'Germany',	'yes'),
(81,	'GH',	'GHA',	'Ghana',	'no'),
(82,	'GI',	'GIB',	'Gibraltar',	'no'),
(83,	'GR',	'GRC',	'Greece',	'no'),
(84,	'GL',	'GRL',	'Greenland',	'no'),
(85,	'GD',	'GRD',	'Grenada',	'no'),
(86,	'GP',	'GLP',	'Guadeloupe',	'no'),
(87,	'GU',	'GUM',	'Guam',	'no'),
(88,	'GT',	'GTM',	'Guatemala',	'no'),
(89,	'GN',	'GIN',	'Guinea',	'no'),
(90,	'GW',	'GNB',	'Guinea-Bissau',	'no'),
(91,	'GY',	'GUY',	'Guyana',	'no'),
(92,	'HT',	'HTI',	'Haiti',	'no'),
(93,	'HM',	'HMD',	'Heard Island and McDonald Islands',	'no'),
(94,	'VA',	'VAT',	'Holy See (Vatican City State)',	'no'),
(95,	'HN',	'HND',	'Honduras',	'no'),
(96,	'HK',	'HKG',	'Hong Kong',	'no'),
(97,	'HU',	'HUN',	'Hungary',	'no'),
(98,	'IS',	'ISL',	'Iceland',	'no'),
(99,	'IN',	'IND',	'India',	'no'),
(100,	'ID',	'IDN',	'Indonesia',	'no'),
(101,	'IR',	'IRN',	'Iran',	'no'),
(102,	'IQ',	'IRQ',	'Iraq',	'no'),
(103,	'IE',	'IRL',	'Ireland',	'no'),
(104,	'IL',	'ISR',	'Israel',	'no'),
(105,	'IT',	'ITA',	'Italy',	'no'),
(106,	'JM',	'JAM',	'Jamaica',	'no'),
(107,	'JP',	'JPN',	'Japan',	'no'),
(108,	'JO',	'JOR',	'Jordan',	'no'),
(109,	'KZ',	'KAZ',	'Kazakhstan',	'no'),
(110,	'KE',	'KEN',	'Kenya',	'no'),
(111,	'KI',	'KIR',	'Kiribati',	'no'),
(112,	'KP',	'PRK',	'Korea, Democratic People\'s Republic of',	'no'),
(113,	'KR',	'KOR',	'Korea, Republic of',	'no'),
(114,	'KW',	'KWT',	'Kuwait',	'no'),
(115,	'KG',	'KGZ',	'Kyrgyzstan',	'no'),
(116,	'LA',	'LAO',	'Laos',	'no'),
(117,	'LV',	'LVA',	'Latvia',	'no'),
(118,	'LB',	'LBN',	'Lebanon',	'no'),
(119,	'LS',	'LSO',	'Lesotho',	'no'),
(120,	'LR',	'LBR',	'Liberia',	'no'),
(121,	'LY',	'LBY',	'Libya',	'no'),
(122,	'LI',	'LIE',	'Liechtenstein',	'no'),
(123,	'LT',	'LTU',	'Lithuania',	'no'),
(124,	'LU',	'LUX',	'Luxembourg',	'no'),
(125,	'MO',	'MAC',	'Macao',	'no'),
(126,	'MK',	'MKD',	'North Macedonia',	'no'),
(127,	'MG',	'MDG',	'Madagascar',	'no'),
(128,	'MW',	'MWI',	'Malawi',	'no'),
(129,	'MY',	'MYS',	'Malaysia',	'no'),
(130,	'MV',	'MDV',	'Maldives',	'no'),
(131,	'ML',	'MLI',	'Mali',	'no'),
(132,	'MT',	'MLT',	'Malta',	'no'),
(133,	'MH',	'MHL',	'Marshall Islands',	'no'),
(134,	'MQ',	'MTQ',	'Martinique',	'no'),
(135,	'MR',	'MRT',	'Mauritania',	'no'),
(136,	'MU',	'MUS',	'Mauritius',	'no'),
(137,	'YT',	'MYT',	'Mayotte',	'no'),
(138,	'MX',	'MEX',	'Mexico',	'no'),
(139,	'FM',	'FSM',	'Micronesia, Federated States of',	'no'),
(140,	'MD',	'MDA',	'Moldova',	'no'),
(141,	'MC',	'MCO',	'Monaco',	'no'),
(142,	'MN',	'MNG',	'Mongolia',	'no'),
(143,	'MS',	'MSR',	'Montserrat',	'no'),
(144,	'MA',	'MAR',	'Morocco',	'no'),
(145,	'MZ',	'MOZ',	'Mozambique',	'no'),
(146,	'MM',	'MMR',	'Myanmar',	'no'),
(147,	'NA',	'NAM',	'Namibia',	'no'),
(148,	'NR',	'NRU',	'Nauru',	'no'),
(149,	'NP',	'NPL',	'Nepal',	'no'),
(150,	'NL',	'NLD',	'Netherlands',	'no'),
(152,	'NC',	'NCL',	'New Caledonia',	'no'),
(153,	'NZ',	'NZL',	'New Zealand',	'no'),
(154,	'NI',	'NIC',	'Nicaragua',	'no'),
(155,	'NE',	'NER',	'Niger',	'no'),
(156,	'NG',	'NGA',	'Nigeria',	'no'),
(157,	'NU',	'NIU',	'Niue',	'no'),
(158,	'NF',	'NFK',	'Norfolk Island',	'no'),
(159,	'MP',	'MNP',	'Northern Mariana Islands',	'no'),
(160,	'NO',	'NOR',	'Norway',	'no'),
(161,	'OM',	'OMN',	'Oman',	'no'),
(162,	'PK',	'PAK',	'Pakistan',	'no'),
(163,	'PW',	'PLW',	'Palau',	'no'),
(164,	'PS',	'PSE',	'Palestine',	'no'),
(165,	'PA',	'PAN',	'Panama',	'no'),
(166,	'PG',	'PNG',	'Papua New Guinea',	'no'),
(167,	'PY',	'PRY',	'Paraguay',	'no'),
(168,	'PE',	'PER',	'Peru',	'no'),
(169,	'PH',	'PHL',	'Philippines',	'no'),
(170,	'PN',	'PCN',	'Pitcairn',	'no'),
(171,	'PL',	'POL',	'Poland',	'yes'),
(172,	'PT',	'PRT',	'Portugal',	'no'),
(173,	'PR',	'PRI',	'Puerto Rico',	'no'),
(174,	'QA',	'QAT',	'Qatar',	'no'),
(175,	'RE',	'REU',	'Réunion',	'no'),
(176,	'RO',	'ROU',	'Romania',	'no'),
(177,	'RU',	'RUS',	'Russian Federation',	'no'),
(178,	'RW',	'RWA',	'Rwanda',	'no'),
(179,	'SH',	'SHN',	'Saint Helena',	'no'),
(180,	'KN',	'KNA',	'Saint Kitts and Nevis',	'no'),
(181,	'LC',	'LCA',	'Saint Lucia',	'no'),
(182,	'PM',	'SPM',	'Saint Pierre and Miquelon',	'no'),
(183,	'VC',	'VCT',	'Saint Vincent and the Grenadines',	'no'),
(184,	'WS',	'WSM',	'Samoa',	'no'),
(185,	'SM',	'SMR',	'San Marino',	'no'),
(186,	'ST',	'STP',	'São Tomé and Príncipe',	'no'),
(187,	'SA',	'SAU',	'Saudi Arabia',	'no'),
(188,	'SN',	'SEN',	'Senegal',	'no'),
(189,	'RS',	'SRB',	'Serbia',	'no'),
(190,	'SC',	'SYC',	'Seychelles',	'no'),
(191,	'SL',	'SLE',	'Sierra Leone',	'no'),
(192,	'SG',	'SGP',	'Singapore',	'no'),
(193,	'SK',	'SVK',	'Slovakia',	'no'),
(194,	'SI',	'SVN',	'Slovenia',	'no'),
(195,	'SB',	'SLB',	'Solomon Islands',	'no'),
(196,	'SO',	'SOM',	'Somalia',	'no'),
(197,	'ZA',	'ZAF',	'South Africa',	'no'),
(198,	'GS',	'SGS',	'South Georgia and the South Sandwich Islands',	'no'),
(199,	'ES',	'ESP',	'Spain',	'no'),
(200,	'LK',	'LKA',	'Sri Lanka',	'no'),
(201,	'SD',	'SDN',	'Sudan',	'no'),
(202,	'SR',	'SUR',	'Suriname',	'no'),
(203,	'SJ',	'SJM',	'Svalbard and Jan Mayen',	'no'),
(204,	'SZ',	'SWZ',	'Eswatini',	'no'),
(205,	'SE',	'SWE',	'Sweden',	'no'),
(206,	'CH',	'CHE',	'Switzerland',	'no'),
(207,	'SY',	'SYR',	'Syria',	'no'),
(208,	'TW',	'TWN',	'Taiwan',	'no'),
(209,	'TJ',	'TJK',	'Tajikistan',	'no'),
(210,	'TZ',	'TZA',	'Tanzania',	'no'),
(211,	'TH',	'THA',	'Thailand',	'no'),
(212,	'TL',	'TLS',	'Timor-Leste',	'no'),
(213,	'TG',	'TGO',	'Togo',	'no'),
(214,	'TK',	'TKL',	'Tokelau',	'no'),
(215,	'TO',	'TON',	'Tonga',	'no'),
(216,	'TT',	'TTO',	'Trinidad and Tobago',	'no'),
(217,	'TN',	'TUN',	'Tunisia',	'no'),
(218,	'TR',	'TUR',	'Turkey',	'no'),
(219,	'TM',	'TKM',	'Turkmenistan',	'no'),
(220,	'TC',	'TCA',	'Turks and Caicos Islands',	'no'),
(221,	'TV',	'TUV',	'Tuvalu',	'no'),
(222,	'UG',	'UGA',	'Uganda',	'no'),
(223,	'UA',	'UKR',	'Ukraine',	'no'),
(224,	'AE',	'ARE',	'United Arab Emirates',	'no'),
(225,	'GB',	'GBR',	'United Kingdom',	'no'),
(226,	'US',	'USA',	'United States',	'no'),
(227,	'UM',	'UMI',	'United States Minor Outlying Islands',	'no'),
(228,	'UY',	'URY',	'Uruguay',	'no'),
(229,	'UZ',	'UZB',	'Uzbekistan',	'no'),
(230,	'VU',	'VUT',	'Vanuatu',	'no'),
(231,	'VE',	'VEN',	'Venezuela',	'no'),
(232,	'VN',	'VNM',	'Viet Nam',	'no'),
(233,	'VG',	'VGB',	'Virgin Islands, British',	'no'),
(234,	'VI',	'VIR',	'Virgin Islands, U.S.',	'no'),
(235,	'WF',	'WLF',	'Wallis and Futuna',	'no'),
(236,	'EH',	'ESH',	'Western Sahara',	'no'),
(237,	'YE',	'YEM',	'Yemen',	'no'),
(238,	'ZM',	'ZMB',	'Zambia',	'no'),
(239,	'ZW',	'ZWE',	'Zimbabwe',	'no'),
(240,	'ME',	'MNE',	'Montenegro',	'no'),
(241,	'SS',	'SSD',	'South Sudan',	'no'),
(242,	'AX',	'ALA',	'Åland Islands',	'no'),
(243,	'BQ',	'BES',	'Bonaire, Sint Eustatius and Saba',	'no'),
(244,	'BL',	'BLM',	'Saint Barthélemy',	'no'),
(245,	'CW',	'CUW',	'Curaçao',	'no'),
(246,	'GG',	'GGY',	'Guernsey',	'no'),
(247,	'IM',	'IMN',	'Isle of Man',	'no'),
(248,	'JE',	'JEY',	'Jersey',	'no'),
(249,	'MF',	'MAF',	'Saint Martin (French part)',	'no'),
(250,	'SX',	'SXM',	'Sint Maarten (Dutch part)',	'no'),
(251,	'XK',	'XKX',	'Kosovo', 'no');


-- languages --
CREATE TABLE `languages` (
  `language_id` int unsigned NOT NULL AUTO_INCREMENT,
  `iso_639_2t` char(3) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `iso_639_2b` char(3) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  `iso_639_1` char(2) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  `language` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `variation` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no',
  PRIMARY KEY (`language_id`),
  UNIQUE KEY `iso_639_2t_variation` (`iso_639_2t`,`variation`),
  KEY `website` (`website`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `languages` (`language_id`, `iso_639_2t`, `iso_639_2b`, `iso_639_1`, `language`, `variation`, `website`) VALUES
(1,	'aar',	NULL,	'aa',	'Afar',	NULL,	'no'),
(2,	'abk',	NULL,	'ab',	'Abkhazian',	NULL,	'no'),
(3,	'ace',	NULL,	NULL,	'Achinese',	NULL,	'no'),
(4,	'ach',	NULL,	NULL,	'Acoli',	NULL,	'no'),
(5,	'ada',	NULL,	NULL,	'Adangme',	NULL,	'no'),
(6,	'ady',	NULL,	NULL,	'Adyghe; Adygei',	NULL,	'no'),
(7,	'afa',	NULL,	NULL,	'Afro-Asiatic (Other)',	NULL,	'no'),
(8,	'afh',	NULL,	NULL,	'Afrihili',	NULL,	'no'),
(9,	'afr',	NULL,	'af',	'Afrikaans',	NULL,	'no'),
(10,	'ain',	NULL,	NULL,	'Ainu',	NULL,	'no'),
(11,	'aka',	NULL,	'ak',	'Akan',	NULL,	'no'),
(12,	'akk',	NULL,	NULL,	'Akkadian',	NULL,	'no'),
(13,	'ale',	NULL,	NULL,	'Aleut',	NULL,	'no'),
(14,	'alg',	NULL,	NULL,	'Algonquian languages',	NULL,	'no'),
(15,	'alt',	NULL,	NULL,	'Southern Altai',	NULL,	'no'),
(16,	'amh',	NULL,	'am',	'Amharic',	NULL,	'no'),
(17,	'ang',	NULL,	NULL,	'English, Old (ca.450-1100)',	NULL,	'no'),
(18,	'anp',	NULL,	NULL,	'Angika',	NULL,	'no'),
(19,	'apa',	NULL,	NULL,	'Apache languages',	NULL,	'no'),
(20,	'ara',	NULL,	'ar',	'Arabic',	NULL,	'no'),
(21,	'arc',	NULL,	NULL,	'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)',	NULL,	'no'),
(22,	'arg',	NULL,	'an',	'Aragonese',	NULL,	'no'),
(23,	'arn',	NULL,	NULL,	'Mapudungun; Mapuche',	NULL,	'no'),
(24,	'arp',	NULL,	NULL,	'Arapaho',	NULL,	'no'),
(25,	'art',	NULL,	NULL,	'Artificial (Other)',	NULL,	'no'),
(26,	'arw',	NULL,	NULL,	'Arawak',	NULL,	'no'),
(27,	'asm',	NULL,	'as',	'Assamese',	NULL,	'no'),
(28,	'ast',	NULL,	NULL,	'Asturian; Bable; Leonese; Asturleonese',	NULL,	'no'),
(29,	'ath',	NULL,	NULL,	'Athapascan languages',	NULL,	'no'),
(30,	'aus',	NULL,	NULL,	'Australian languages',	NULL,	'no'),
(31,	'ava',	NULL,	'av',	'Avaric',	NULL,	'no'),
(32,	'ave',	NULL,	'ae',	'Avestan',	NULL,	'no'),
(33,	'awa',	NULL,	NULL,	'Awadhi',	NULL,	'no'),
(34,	'aym',	NULL,	'ay',	'Aymara',	NULL,	'no'),
(35,	'aze',	NULL,	'az',	'Azerbaijani',	NULL,	'no'),
(36,	'bad',	NULL,	NULL,	'Banda languages',	NULL,	'no'),
(37,	'bai',	NULL,	NULL,	'Bamileke languages',	NULL,	'no'),
(38,	'bak',	NULL,	'ba',	'Bashkir',	NULL,	'no'),
(39,	'bal',	NULL,	NULL,	'Baluchi',	NULL,	'no'),
(40,	'bam',	NULL,	'bm',	'Bambara',	NULL,	'no'),
(41,	'ban',	NULL,	NULL,	'Balinese',	NULL,	'no'),
(42,	'bas',	NULL,	NULL,	'Basa',	NULL,	'no'),
(43,	'bat',	NULL,	NULL,	'Baltic (Other)',	NULL,	'no'),
(44,	'bej',	NULL,	NULL,	'Beja; Bedawiyet',	NULL,	'no'),
(45,	'bel',	NULL,	'be',	'Belarusian',	NULL,	'yes'),
(46,	'bem',	NULL,	NULL,	'Bemba',	NULL,	'no'),
(47,	'ben',	NULL,	'bn',	'Bengali',	NULL,	'no'),
(48,	'ber',	NULL,	NULL,	'Berber (Other)',	NULL,	'no'),
(49,	'bho',	NULL,	NULL,	'Bhojpuri',	NULL,	'no'),
(50,	'bih',	NULL,	'bh',	'Bihari',	NULL,	'no'),
(51,	'bik',	NULL,	NULL,	'Bikol',	NULL,	'no'),
(52,	'bin',	NULL,	NULL,	'Bini; Edo',	NULL,	'no'),
(53,	'bis',	NULL,	'bi',	'Bislama',	NULL,	'no'),
(54,	'bla',	NULL,	NULL,	'Siksika',	NULL,	'no'),
(55,	'bnt',	NULL,	NULL,	'Bantu (Other)',	NULL,	'no'),
(56,	'bod',	'tib',	'bo',	'Tibetan',	NULL,	'no'),
(57,	'bos',	NULL,	'bs',	'Bosnian',	NULL,	'no'),
(58,	'bra',	NULL,	NULL,	'Braj',	NULL,	'no'),
(59,	'bre',	NULL,	'br',	'Breton',	NULL,	'no'),
(60,	'btk',	NULL,	NULL,	'Batak languages',	NULL,	'no'),
(61,	'bua',	NULL,	NULL,	'Buriat',	NULL,	'no'),
(62,	'bug',	NULL,	NULL,	'Buginese',	NULL,	'no'),
(63,	'bul',	NULL,	'bg',	'Bulgarian',	NULL,	'no'),
(64,	'byn',	NULL,	NULL,	'Blin; Bilin',	NULL,	'no'),
(65,	'cad',	NULL,	NULL,	'Caddo',	NULL,	'no'),
(66,	'cai',	NULL,	NULL,	'Central American Indian (Other)',	NULL,	'no'),
(67,	'car',	NULL,	NULL,	'Galibi Carib',	NULL,	'no'),
(68,	'cat',	NULL,	'ca',	'Catalan; Valencian',	NULL,	'no'),
(69,	'cau',	NULL,	NULL,	'Caucasian (Other)',	NULL,	'no'),
(70,	'ceb',	NULL,	NULL,	'Cebuano',	NULL,	'no'),
(71,	'cel',	NULL,	NULL,	'Celtic (Other)',	NULL,	'no'),
(72,	'ces',	'cze',	'cs',	'Czech',	NULL,	'no'),
(73,	'cha',	NULL,	'ch',	'Chamorro',	NULL,	'no'),
(74,	'chb',	NULL,	NULL,	'Chibcha',	NULL,	'no'),
(75,	'che',	NULL,	'ce',	'Chechen',	NULL,	'no'),
(76,	'chg',	NULL,	NULL,	'Chagatai',	NULL,	'no'),
(77,	'chk',	NULL,	NULL,	'Chuukese',	NULL,	'no'),
(78,	'chm',	NULL,	NULL,	'Mari',	NULL,	'no'),
(79,	'chn',	NULL,	NULL,	'Chinook jargon',	NULL,	'no'),
(80,	'cho',	NULL,	NULL,	'Choctaw',	NULL,	'no'),
(81,	'chp',	NULL,	NULL,	'Chipewyan; Dene Suline',	NULL,	'no'),
(82,	'chr',	NULL,	NULL,	'Cherokee',	NULL,	'no'),
(83,	'chu',	NULL,	'cu',	'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',	NULL,	'no'),
(84,	'chv',	NULL,	'cv',	'Chuvash',	NULL,	'no'),
(85,	'chy',	NULL,	NULL,	'Cheyenne',	NULL,	'no'),
(86,	'cmc',	NULL,	NULL,	'Chamic languages',	NULL,	'no'),
(87,	'cop',	NULL,	NULL,	'Coptic',	NULL,	'no'),
(88,	'cor',	NULL,	'kw',	'Cornish',	NULL,	'no'),
(89,	'cos',	NULL,	'co',	'Corsican',	NULL,	'no'),
(90,	'cpe',	NULL,	NULL,	'Creoles and pidgins, English based (Other)',	NULL,	'no'),
(91,	'cpf',	NULL,	NULL,	'Creoles and pidgins, French-based (Other)',	NULL,	'no'),
(92,	'cpp',	NULL,	NULL,	'Creoles and pidgins, Portuguese-based (Other)',	NULL,	'no'),
(93,	'cre',	NULL,	'cr',	'Cree',	NULL,	'no'),
(94,	'crh',	NULL,	NULL,	'Crimean Tatar; Crimean Turkish',	NULL,	'no'),
(95,	'crp',	NULL,	NULL,	'Creoles and pidgins (Other)',	NULL,	'no'),
(96,	'csb',	NULL,	NULL,	'Kashubian',	NULL,	'no'),
(97,	'cus',	NULL,	NULL,	'Cushitic (Other)',	NULL,	'no'),
(98,	'cym',	'wel',	'cy',	'Welsh',	NULL,	'no'),
(99,	'dak',	NULL,	NULL,	'Dakota',	NULL,	'no'),
(100,	'dan',	NULL,	'da',	'Danish',	NULL,	'no'),
(101,	'dar',	NULL,	NULL,	'Dargwa',	NULL,	'no'),
(102,	'day',	NULL,	NULL,	'Land Dayak languages',	NULL,	'no'),
(103,	'del',	NULL,	NULL,	'Delaware',	NULL,	'no'),
(104,	'den',	NULL,	NULL,	'Slave (Athapascan)',	NULL,	'no'),
(105,	'deu',	'ger',	'de',	'German',	NULL,	'yes'),
(106,	'dgr',	NULL,	NULL,	'Dogrib',	NULL,	'no'),
(107,	'din',	NULL,	NULL,	'Dinka',	NULL,	'no'),
(108,	'div',	NULL,	'dv',	'Divehi; Dhivehi; Maldivian',	NULL,	'no'),
(109,	'doi',	NULL,	NULL,	'Dogri',	NULL,	'no'),
(110,	'dra',	NULL,	NULL,	'Dravidian (Other)',	NULL,	'no'),
(111,	'dsb',	NULL,	NULL,	'Lower Sorbian',	NULL,	'no'),
(112,	'dua',	NULL,	NULL,	'Duala',	NULL,	'no'),
(113,	'dum',	NULL,	NULL,	'Dutch, Middle (ca.1050-1350)',	NULL,	'no'),
(114,	'dyu',	NULL,	NULL,	'Dyula',	NULL,	'no'),
(115,	'dzo',	NULL,	'dz',	'Dzongkha',	NULL,	'no'),
(116,	'efi',	NULL,	NULL,	'Efik',	NULL,	'no'),
(117,	'egy',	NULL,	NULL,	'Egyptian (Ancient)',	NULL,	'no'),
(118,	'eka',	NULL,	NULL,	'Ekajuk',	NULL,	'no'),
(119,	'ell',	'gre',	'el',	'Greek, Modern (1453-)',	NULL,	'no'),
(120,	'elx',	NULL,	NULL,	'Elamite',	NULL,	'no'),
(121,	'eng',	NULL,	'en',	'English',	NULL,	'yes'),
(122,	'enm',	NULL,	NULL,	'English, Middle (1100-1500)',	NULL,	'no'),
(123,	'epo',	NULL,	'eo',	'Esperanto',	NULL,	'no'),
(124,	'est',	NULL,	'et',	'Estonian',	NULL,	'no'),
(125,	'eus',	'baq',	'eu',	'Basque',	NULL,	'no'),
(126,	'ewe',	NULL,	'ee',	'Ewe',	NULL,	'no'),
(127,	'ewo',	NULL,	NULL,	'Ewondo',	NULL,	'no'),
(128,	'fan',	NULL,	NULL,	'Fang',	NULL,	'no'),
(129,	'fao',	NULL,	'fo',	'Faroese',	NULL,	'no'),
(130,	'fas',	'per',	'fa',	'Persian',	NULL,	'no'),
(131,	'fat',	NULL,	NULL,	'Fanti',	NULL,	'no'),
(132,	'fij',	NULL,	'fj',	'Fijian',	NULL,	'no'),
(133,	'fil',	NULL,	NULL,	'Filipino; Pilipino',	NULL,	'no'),
(134,	'fin',	NULL,	'fi',	'Finnish',	NULL,	'no'),
(135,	'fiu',	NULL,	NULL,	'Finno-Ugrian (Other)',	NULL,	'no'),
(136,	'fon',	NULL,	NULL,	'Fon',	NULL,	'no'),
(137,	'fra',	'fre',	'fr',	'French',	NULL,	'no'),
(138,	'frm',	NULL,	NULL,	'French, Middle (ca.1400-1600)',	NULL,	'no'),
(139,	'fro',	NULL,	NULL,	'French, Old (842-ca.1400)',	NULL,	'no'),
(140,	'frr',	NULL,	NULL,	'Northern Frisian',	NULL,	'no'),
(141,	'frs',	NULL,	NULL,	'Eastern Frisian',	NULL,	'no'),
(142,	'fry',	NULL,	'fy',	'Western Frisian',	NULL,	'no'),
(143,	'ful',	NULL,	'ff',	'Fulah',	NULL,	'no'),
(144,	'fur',	NULL,	NULL,	'Friulian',	NULL,	'no'),
(145,	'gaa',	NULL,	NULL,	'Ga',	NULL,	'no'),
(146,	'gay',	NULL,	NULL,	'Gayo',	NULL,	'no'),
(147,	'gba',	NULL,	NULL,	'Gbaya',	NULL,	'no'),
(148,	'gem',	NULL,	NULL,	'Germanic (Other)',	NULL,	'no'),
(149,	'gez',	NULL,	NULL,	'Geez',	NULL,	'no'),
(150,	'gil',	NULL,	NULL,	'Gilbertese',	NULL,	'no'),
(151,	'gla',	NULL,	'gd',	'Gaelic; Scottish Gaelic',	NULL,	'no'),
(152,	'gle',	NULL,	'ga',	'Irish',	NULL,	'no'),
(153,	'glg',	NULL,	'gl',	'Galician',	NULL,	'no'),
(154,	'glv',	NULL,	'gv',	'Manx',	NULL,	'no'),
(155,	'gmh',	NULL,	NULL,	'German, Middle High (ca.1050-1500)',	NULL,	'no'),
(156,	'goh',	NULL,	NULL,	'German, Old High (ca.750-1050)',	NULL,	'no'),
(157,	'gon',	NULL,	NULL,	'Gondi',	NULL,	'no'),
(158,	'gor',	NULL,	NULL,	'Gorontalo',	NULL,	'no'),
(159,	'got',	NULL,	NULL,	'Gothic',	NULL,	'no'),
(160,	'grb',	NULL,	NULL,	'Grebo',	NULL,	'no'),
(161,	'grc',	NULL,	NULL,	'Greek, Ancient (to 1453)',	NULL,	'no'),
(162,	'grn',	NULL,	'gn',	'Guarani',	NULL,	'no'),
(163,	'gsw',	NULL,	NULL,	'Swiss German; Alemannic; Alsatian',	NULL,	'no'),
(164,	'guj',	NULL,	'gu',	'Gujarati',	NULL,	'no'),
(165,	'gwi',	NULL,	NULL,	'Gwich\'in',	NULL,	'no'),
(166,	'hai',	NULL,	NULL,	'Haida',	NULL,	'no'),
(167,	'hat',	NULL,	'ht',	'Haitian; Haitian Creole',	NULL,	'no'),
(168,	'hau',	NULL,	'ha',	'Hausa',	NULL,	'no'),
(169,	'haw',	NULL,	NULL,	'Hawaiian',	NULL,	'no'),
(170,	'heb',	NULL,	'he',	'Hebrew',	NULL,	'no'),
(171,	'her',	NULL,	'hz',	'Herero',	NULL,	'no'),
(172,	'hil',	NULL,	NULL,	'Hiligaynon',	NULL,	'no'),
(173,	'him',	NULL,	NULL,	'Himachali',	NULL,	'no'),
(174,	'hin',	NULL,	'hi',	'Hindi',	NULL,	'no'),
(175,	'hit',	NULL,	NULL,	'Hittite',	NULL,	'no'),
(176,	'hmn',	NULL,	NULL,	'Hmong',	NULL,	'no'),
(177,	'hmo',	NULL,	'ho',	'Hiri Motu',	NULL,	'no'),
(178,	'hrv',	'scr',	'hr',	'Croatian',	NULL,	'no'),
(179,	'hsb',	NULL,	NULL,	'Upper Sorbian',	NULL,	'no'),
(180,	'hun',	NULL,	'hu',	'Hungarian',	NULL,	'no'),
(181,	'hup',	NULL,	NULL,	'Hupa',	NULL,	'no'),
(182,	'hye',	'arm',	'hy',	'Armenian',	NULL,	'no'),
(183,	'iba',	NULL,	NULL,	'Iban',	NULL,	'no'),
(184,	'ibo',	NULL,	'ig',	'Igbo',	NULL,	'no'),
(185,	'ido',	NULL,	'io',	'Ido',	NULL,	'no'),
(186,	'iii',	NULL,	'ii',	'Sichuan Yi; Nuosu',	NULL,	'no'),
(187,	'ijo',	NULL,	NULL,	'Ijo languages',	NULL,	'no'),
(188,	'iku',	NULL,	'iu',	'Inuktitut',	NULL,	'no'),
(189,	'ile',	NULL,	'ie',	'Interlingue; Occidental',	NULL,	'no'),
(190,	'ilo',	NULL,	NULL,	'Iloko',	NULL,	'no'),
(191,	'ina',	NULL,	'ia',	'Interlingua (International Auxiliary Language Association)',	NULL,	'no'),
(192,	'inc',	NULL,	NULL,	'Indic (Other)',	NULL,	'no'),
(193,	'ind',	NULL,	'id',	'Indonesian',	NULL,	'no'),
(194,	'ine',	NULL,	NULL,	'Indo-European (Other)',	NULL,	'no'),
(195,	'inh',	NULL,	NULL,	'Ingush',	NULL,	'no'),
(196,	'ipk',	NULL,	'ik',	'Inupiaq',	NULL,	'no'),
(197,	'ira',	NULL,	NULL,	'Iranian (Other)',	NULL,	'no'),
(198,	'iro',	NULL,	NULL,	'Iroquoian languages',	NULL,	'no'),
(199,	'isl',	'ice',	'is',	'Icelandic',	NULL,	'no'),
(200,	'ita',	NULL,	'it',	'Italian',	NULL,	'no'),
(201,	'jav',	NULL,	'jv',	'Javanese',	NULL,	'no'),
(202,	'jbo',	NULL,	NULL,	'Lojban',	NULL,	'no'),
(203,	'jpn',	NULL,	'ja',	'Japanese',	NULL,	'no'),
(204,	'jpr',	NULL,	NULL,	'Judeo-Persian',	NULL,	'no'),
(205,	'jrb',	NULL,	NULL,	'Judeo-Arabic',	NULL,	'no'),
(206,	'kaa',	NULL,	NULL,	'Kara-Kalpak',	NULL,	'no'),
(207,	'kab',	NULL,	NULL,	'Kabyle',	NULL,	'no'),
(208,	'kac',	NULL,	NULL,	'Kachin; Jingpho',	NULL,	'no'),
(209,	'kal',	NULL,	'kl',	'Kalaallisut; Greenlandic',	NULL,	'no'),
(210,	'kam',	NULL,	NULL,	'Kamba',	NULL,	'no'),
(211,	'kan',	NULL,	'kn',	'Kannada',	NULL,	'no'),
(212,	'kar',	NULL,	NULL,	'Karen languages',	NULL,	'no'),
(213,	'kas',	NULL,	'ks',	'Kashmiri',	NULL,	'no'),
(214,	'kat',	'geo',	'ka',	'Georgian',	NULL,	'no'),
(215,	'kau',	NULL,	'kr',	'Kanuri',	NULL,	'no'),
(216,	'kaw',	NULL,	NULL,	'Kawi',	NULL,	'no'),
(217,	'kaz',	NULL,	'kk',	'Kazakh',	NULL,	'no'),
(218,	'kbd',	NULL,	NULL,	'Kabardian',	NULL,	'no'),
(219,	'kha',	NULL,	NULL,	'Khasi',	NULL,	'no'),
(220,	'khi',	NULL,	NULL,	'Khoisan (Other)',	NULL,	'no'),
(221,	'khm',	NULL,	'km',	'Central Khmer',	NULL,	'no'),
(222,	'kho',	NULL,	NULL,	'Khotanese',	NULL,	'no'),
(223,	'kik',	NULL,	'ki',	'Kikuyu; Gikuyu',	NULL,	'no'),
(224,	'kin',	NULL,	'rw',	'Kinyarwanda',	NULL,	'no'),
(225,	'kir',	NULL,	'ky',	'Kirghiz; Kyrgyz',	NULL,	'no'),
(226,	'kmb',	NULL,	NULL,	'Kimbundu',	NULL,	'no'),
(227,	'kok',	NULL,	NULL,	'Konkani',	NULL,	'no'),
(228,	'kom',	NULL,	'kv',	'Komi',	NULL,	'no'),
(229,	'kon',	NULL,	'kg',	'Kongo',	NULL,	'no'),
(230,	'kor',	NULL,	'ko',	'Korean',	NULL,	'no'),
(231,	'kos',	NULL,	NULL,	'Kosraean',	NULL,	'no'),
(232,	'kpe',	NULL,	NULL,	'Kpelle',	NULL,	'no'),
(233,	'krc',	NULL,	NULL,	'Karachay-Balkar',	NULL,	'no'),
(234,	'krl',	NULL,	NULL,	'Karelian',	NULL,	'no'),
(235,	'kro',	NULL,	NULL,	'Kru languages',	NULL,	'no'),
(236,	'kru',	NULL,	NULL,	'Kurukh',	NULL,	'no'),
(237,	'kua',	NULL,	'kj',	'Kuanyama; Kwanyama',	NULL,	'no'),
(238,	'kum',	NULL,	NULL,	'Kumyk',	NULL,	'no'),
(239,	'kur',	NULL,	'ku',	'Kurdish',	NULL,	'no'),
(240,	'kut',	NULL,	NULL,	'Kutenai',	NULL,	'no'),
(241,	'lad',	NULL,	NULL,	'Ladino',	NULL,	'no'),
(242,	'lah',	NULL,	NULL,	'Lahnda',	NULL,	'no'),
(243,	'lam',	NULL,	NULL,	'Lamba',	NULL,	'no'),
(244,	'lao',	NULL,	'lo',	'Lao',	NULL,	'no'),
(245,	'lat',	NULL,	'la',	'Latin',	NULL,	'no'),
(246,	'lav',	NULL,	'lv',	'Latvian',	NULL,	'no'),
(247,	'lez',	NULL,	NULL,	'Lezghian',	NULL,	'no'),
(248,	'lim',	NULL,	'li',	'Limburgan; Limburger; Limburgish',	NULL,	'no'),
(249,	'lin',	NULL,	'ln',	'Lingala',	NULL,	'no'),
(250,	'lit',	NULL,	'lt',	'Lithuanian',	NULL,	'no'),
(251,	'lol',	NULL,	NULL,	'Mongo',	NULL,	'no'),
(252,	'loz',	NULL,	NULL,	'Lozi',	NULL,	'no'),
(253,	'ltz',	NULL,	'lb',	'Luxembourgish; Letzeburgesch',	NULL,	'no'),
(254,	'lua',	NULL,	NULL,	'Luba-Lulua',	NULL,	'no'),
(255,	'lub',	NULL,	'lu',	'Luba-Katanga',	NULL,	'no'),
(256,	'lug',	NULL,	'lg',	'Ganda',	NULL,	'no'),
(257,	'lui',	NULL,	NULL,	'Luiseno',	NULL,	'no'),
(258,	'lun',	NULL,	NULL,	'Lunda',	NULL,	'no'),
(259,	'luo',	NULL,	NULL,	'Luo (Kenya and Tanzania)',	NULL,	'no'),
(260,	'lus',	NULL,	NULL,	'Lushai',	NULL,	'no'),
(261,	'mad',	NULL,	NULL,	'Madurese',	NULL,	'no'),
(262,	'mag',	NULL,	NULL,	'Magahi',	NULL,	'no'),
(263,	'mah',	NULL,	'mh',	'Marshallese',	NULL,	'no'),
(264,	'mai',	NULL,	NULL,	'Maithili',	NULL,	'no'),
(265,	'mak',	NULL,	NULL,	'Makasar',	NULL,	'no'),
(266,	'mal',	NULL,	'ml',	'Malayalam',	NULL,	'no'),
(267,	'man',	NULL,	NULL,	'Mandingo',	NULL,	'no'),
(268,	'map',	NULL,	NULL,	'Austronesian (Other)',	NULL,	'no'),
(269,	'mar',	NULL,	'mr',	'Marathi',	NULL,	'no'),
(270,	'mas',	NULL,	NULL,	'Masai',	NULL,	'no'),
(271,	'mdf',	NULL,	NULL,	'Moksha',	NULL,	'no'),
(272,	'mdr',	NULL,	NULL,	'Mandar',	NULL,	'no'),
(273,	'men',	NULL,	NULL,	'Mende',	NULL,	'no'),
(274,	'mga',	NULL,	NULL,	'Irish, Middle (900-1200)',	NULL,	'no'),
(275,	'mic',	NULL,	NULL,	'Mi\'kmaq; Micmac',	NULL,	'no'),
(276,	'min',	NULL,	NULL,	'Minangkabau',	NULL,	'no'),
(277,	'mis',	NULL,	NULL,	'Uncoded languages',	NULL,	'no'),
(278,	'mkd',	'mac',	'mk',	'Macedonian',	NULL,	'no'),
(279,	'mkh',	NULL,	NULL,	'Mon-Khmer (Other)',	NULL,	'no'),
(280,	'mlg',	NULL,	'mg',	'Malagasy',	NULL,	'no'),
(281,	'mlt',	NULL,	'mt',	'Maltese',	NULL,	'no'),
(282,	'mnc',	NULL,	NULL,	'Manchu',	NULL,	'no'),
(283,	'mni',	NULL,	NULL,	'Manipuri',	NULL,	'no'),
(284,	'mno',	NULL,	NULL,	'Manobo languages',	NULL,	'no'),
(285,	'moh',	NULL,	NULL,	'Mohawk',	NULL,	'no'),
(286,	'mol',	NULL,	'mo',	'Moldavian',	NULL,	'no'),
(287,	'mon',	NULL,	'mn',	'Mongolian',	NULL,	'no'),
(288,	'mos',	NULL,	NULL,	'Mossi',	NULL,	'no'),
(289,	'mri',	'mao',	'mi',	'Maori',	NULL,	'no'),
(290,	'msa',	'may',	'ms',	'Malay',	NULL,	'no'),
(291,	'mul',	NULL,	NULL,	'Multiple languages',	NULL,	'no'),
(292,	'mun',	NULL,	NULL,	'Munda languages',	NULL,	'no'),
(293,	'mus',	NULL,	NULL,	'Creek',	NULL,	'no'),
(294,	'mwl',	NULL,	NULL,	'Mirandese',	NULL,	'no'),
(295,	'mwr',	NULL,	NULL,	'Marwari',	NULL,	'no'),
(296,	'mya',	'bur',	'my',	'Burmese',	NULL,	'no'),
(297,	'myn',	NULL,	NULL,	'Mayan languages',	NULL,	'no'),
(298,	'myv',	NULL,	NULL,	'Erzya',	NULL,	'no'),
(299,	'nah',	NULL,	NULL,	'Nahuatl languages',	NULL,	'no'),
(300,	'nai',	NULL,	NULL,	'North American Indian',	NULL,	'no'),
(301,	'nap',	NULL,	NULL,	'Neapolitan',	NULL,	'no'),
(302,	'nau',	NULL,	'na',	'Nauru',	NULL,	'no'),
(303,	'nav',	NULL,	'nv',	'Navajo; Navaho',	NULL,	'no'),
(304,	'nbl',	NULL,	'nr',	'Ndebele, South; South Ndebele',	NULL,	'no'),
(305,	'nde',	NULL,	'nd',	'Ndebele, North; North Ndebele',	NULL,	'no'),
(306,	'ndo',	NULL,	'ng',	'Ndonga',	NULL,	'no'),
(307,	'nds',	NULL,	NULL,	'Low German; Low Saxon; German, Low; Saxon, Low',	NULL,	'no'),
(308,	'nep',	NULL,	'ne',	'Nepali',	NULL,	'no'),
(309,	'new',	NULL,	NULL,	'Nepal Bhasa; Newari',	NULL,	'no'),
(310,	'nia',	NULL,	NULL,	'Nias',	NULL,	'no'),
(311,	'nic',	NULL,	NULL,	'Niger-Kordofanian (Other)',	NULL,	'no'),
(312,	'niu',	NULL,	NULL,	'Niuean',	NULL,	'no'),
(313,	'nld',	'dut',	'nl',	'Dutch; Flemish',	NULL,	'no'),
(314,	'nno',	NULL,	'nn',	'Norwegian Nynorsk; Nynorsk, Norwegian',	NULL,	'no'),
(315,	'nob',	NULL,	'nb',	'Bokmal, Norwegian; Norwegian Bokmal',	NULL,	'no'),
(316,	'nog',	NULL,	NULL,	'Nogai',	NULL,	'no'),
(317,	'non',	NULL,	NULL,	'Norse, Old',	NULL,	'no'),
(318,	'nor',	NULL,	'no',	'Norwegian',	NULL,	'no'),
(319,	'nqo',	NULL,	NULL,	'N\'Ko',	NULL,	'no'),
(320,	'nso',	NULL,	NULL,	'Pedi; Sepedi; Northern Sotho',	NULL,	'no'),
(321,	'nub',	NULL,	NULL,	'Nubian languages',	NULL,	'no'),
(322,	'nwc',	NULL,	NULL,	'Classical Newari; Old Newari; Classical Nepal Bhasa',	NULL,	'no'),
(323,	'nya',	NULL,	'ny',	'Chichewa; Chewa; Nyanja',	NULL,	'no'),
(324,	'nym',	NULL,	NULL,	'Nyamwezi',	NULL,	'no'),
(325,	'nyn',	NULL,	NULL,	'Nyankole',	NULL,	'no'),
(326,	'nyo',	NULL,	NULL,	'Nyoro',	NULL,	'no'),
(327,	'nzi',	NULL,	NULL,	'Nzima',	NULL,	'no'),
(328,	'oci',	NULL,	'oc',	'Occitan (post 1500); Provençal',	NULL,	'no'),
(329,	'oji',	NULL,	'oj',	'Ojibwa',	NULL,	'no'),
(330,	'ori',	NULL,	'or',	'Oriya',	NULL,	'no'),
(331,	'orm',	NULL,	'om',	'Oromo',	NULL,	'no'),
(332,	'osa',	NULL,	NULL,	'Osage',	NULL,	'no'),
(333,	'oss',	NULL,	'os',	'Ossetian; Ossetic',	NULL,	'no'),
(334,	'ota',	NULL,	NULL,	'Turkish, Ottoman (1500-1928)',	NULL,	'no'),
(335,	'oto',	NULL,	NULL,	'Otomian languages',	NULL,	'no'),
(336,	'paa',	NULL,	NULL,	'Papuan (Other)',	NULL,	'no'),
(337,	'pag',	NULL,	NULL,	'Pangasinan',	NULL,	'no'),
(338,	'pal',	NULL,	NULL,	'Pahlavi',	NULL,	'no'),
(339,	'pam',	NULL,	NULL,	'Pampanga; Kapampangan',	NULL,	'no'),
(340,	'pan',	NULL,	'pa',	'Panjabi; Punjabi',	NULL,	'no'),
(341,	'pap',	NULL,	NULL,	'Papiamento',	NULL,	'no'),
(342,	'pau',	NULL,	NULL,	'Palauan',	NULL,	'no'),
(343,	'peo',	NULL,	NULL,	'Persian, Old (ca.600-400 B.C.)',	NULL,	'no'),
(344,	'phi',	NULL,	NULL,	'Philippine (Other)',	NULL,	'no'),
(345,	'phn',	NULL,	NULL,	'Phoenician',	NULL,	'no'),
(346,	'pli',	NULL,	'pi',	'Pali',	NULL,	'no'),
(347,	'pol',	NULL,	'pl',	'Polish',	NULL,	'yes'),
(348,	'pon',	NULL,	NULL,	'Pohnpeian',	NULL,	'no'),
(349,	'por',	NULL,	'pt',	'Portuguese',	NULL,	'no'),
(350,	'pra',	NULL,	NULL,	'Prakrit languages',	NULL,	'no'),
(351,	'pro',	NULL,	NULL,	'Provençal, Old (to 1500)',	NULL,	'no'),
(352,	'pus',	NULL,	'ps',	'Pushto; Pashto',	NULL,	'no'),
(353,	'que',	NULL,	'qu',	'Quechua',	NULL,	'no'),
(354,	'raj',	NULL,	NULL,	'Rajasthani',	NULL,	'no'),
(355,	'rap',	NULL,	NULL,	'Rapanui',	NULL,	'no'),
(356,	'rar',	NULL,	NULL,	'Rarotongan; Cook Islands Maori',	NULL,	'no'),
(357,	'roa',	NULL,	NULL,	'Romance (Other)',	NULL,	'no'),
(358,	'roh',	NULL,	'rm',	'Romansh',	NULL,	'no'),
(359,	'rom',	NULL,	NULL,	'Romany',	NULL,	'no'),
(360,	'ron',	'rum',	'ro',	'Romanian',	NULL,	'no'),
(361,	'run',	NULL,	'rn',	'Rundi',	NULL,	'no'),
(362,	'rup',	NULL,	NULL,	'Aromanian; Arumanian; Macedo-Romanian',	NULL,	'no'),
(363,	'rus',	NULL,	'ru',	'Russian',	NULL,	'no'),
(364,	'sad',	NULL,	NULL,	'Sandawe',	NULL,	'no'),
(365,	'sag',	NULL,	'sg',	'Sango',	NULL,	'no'),
(366,	'sah',	NULL,	NULL,	'Yakut',	NULL,	'no'),
(367,	'sai',	NULL,	NULL,	'South American Indian (Other)',	NULL,	'no'),
(368,	'sal',	NULL,	NULL,	'Salishan languages',	NULL,	'no'),
(369,	'sam',	NULL,	NULL,	'Samaritan Aramaic',	NULL,	'no'),
(370,	'san',	NULL,	'sa',	'Sanskrit',	NULL,	'no'),
(371,	'sas',	NULL,	NULL,	'Sasak',	NULL,	'no'),
(372,	'sat',	NULL,	NULL,	'Santali',	NULL,	'no'),
(373,	'scn',	NULL,	NULL,	'Sicilian',	NULL,	'no'),
(374,	'sco',	NULL,	NULL,	'Scots',	NULL,	'no'),
(375,	'sel',	NULL,	NULL,	'Selkup',	NULL,	'no'),
(376,	'sem',	NULL,	NULL,	'Semitic (Other)',	NULL,	'no'),
(377,	'sga',	NULL,	NULL,	'Irish, Old (to 900)',	NULL,	'no'),
(378,	'sgn',	NULL,	NULL,	'Sign Languages',	NULL,	'no'),
(379,	'shn',	NULL,	NULL,	'Shan',	NULL,	'no'),
(380,	'sid',	NULL,	NULL,	'Sidamo',	NULL,	'no'),
(381,	'sin',	NULL,	'si',	'Sinhala; Sinhalese',	NULL,	'no'),
(382,	'sio',	NULL,	NULL,	'Siouan languages',	NULL,	'no'),
(383,	'sit',	NULL,	NULL,	'Sino-Tibetan (Other)',	NULL,	'no'),
(384,	'sla',	NULL,	NULL,	'Slavic (Other)',	NULL,	'no'),
(385,	'slk',	'slo',	'sk',	'Slovak',	NULL,	'no'),
(386,	'slv',	NULL,	'sl',	'Slovenian',	NULL,	'no'),
(387,	'sma',	NULL,	NULL,	'Southern Sami',	NULL,	'no'),
(388,	'sme',	NULL,	'se',	'Northern Sami',	NULL,	'no'),
(389,	'smi',	NULL,	NULL,	'Sami languages (Other)',	NULL,	'no'),
(390,	'smj',	NULL,	NULL,	'Lule Sami',	NULL,	'no'),
(391,	'smn',	NULL,	NULL,	'Inari Sami',	NULL,	'no'),
(392,	'smo',	NULL,	'sm',	'Samoan',	NULL,	'no'),
(393,	'sms',	NULL,	NULL,	'Skolt Sami',	NULL,	'no'),
(394,	'sna',	NULL,	'sn',	'Shona',	NULL,	'no'),
(395,	'snd',	NULL,	'sd',	'Sindhi',	NULL,	'no'),
(396,	'snk',	NULL,	NULL,	'Soninke',	NULL,	'no'),
(397,	'sog',	NULL,	NULL,	'Sogdian',	NULL,	'no'),
(398,	'som',	NULL,	'so',	'Somali',	NULL,	'no'),
(399,	'son',	NULL,	NULL,	'Songhai languages',	NULL,	'no'),
(400,	'sot',	NULL,	'st',	'Sotho, Southern',	NULL,	'no'),
(401,	'spa',	NULL,	'es',	'Spanish; Castilian',	NULL,	'no'),
(402,	'sqi',	'alb',	'sq',	'Albanian',	NULL,	'no'),
(403,	'srd',	NULL,	'sc',	'Sardinian',	NULL,	'no'),
(404,	'srn',	NULL,	NULL,	'Sranan Tongo',	NULL,	'no'),
(405,	'srp',	'scc',	'sr',	'Serbian',	NULL,	'no'),
(406,	'srr',	NULL,	NULL,	'Serer',	NULL,	'no'),
(407,	'ssa',	NULL,	NULL,	'Nilo-Saharan (Other)',	NULL,	'no'),
(408,	'ssw',	NULL,	'ss',	'Swati',	NULL,	'no'),
(409,	'suk',	NULL,	NULL,	'Sukuma',	NULL,	'no'),
(410,	'sun',	NULL,	'su',	'Sundanese',	NULL,	'no'),
(411,	'sus',	NULL,	NULL,	'Susu',	NULL,	'no'),
(412,	'sux',	NULL,	NULL,	'Sumerian',	NULL,	'no'),
(413,	'swa',	NULL,	'sw',	'Swahili',	NULL,	'no'),
(414,	'swe',	NULL,	'sv',	'Swedish',	NULL,	'no'),
(415,	'syc',	NULL,	NULL,	'Classical Syriac',	NULL,	'no'),
(416,	'syr',	NULL,	NULL,	'Syriac',	NULL,	'no'),
(417,	'tah',	NULL,	'ty',	'Tahitian',	NULL,	'no'),
(418,	'tai',	NULL,	NULL,	'Tai (Other)',	NULL,	'no'),
(419,	'tam',	NULL,	'ta',	'Tamil',	NULL,	'no'),
(420,	'tat',	NULL,	'tt',	'Tatar',	NULL,	'no'),
(421,	'tel',	NULL,	'te',	'Telugu',	NULL,	'no'),
(422,	'tem',	NULL,	NULL,	'Timne',	NULL,	'no'),
(423,	'ter',	NULL,	NULL,	'Tereno',	NULL,	'no'),
(424,	'tet',	NULL,	NULL,	'Tetum',	NULL,	'no'),
(425,	'tgk',	NULL,	'tg',	'Tajik',	NULL,	'no'),
(426,	'tgl',	NULL,	'tl',	'Tagalog',	NULL,	'no'),
(427,	'tha',	NULL,	'th',	'Thai',	NULL,	'no'),
(428,	'tig',	NULL,	NULL,	'Tigre',	NULL,	'no'),
(429,	'tir',	NULL,	'ti',	'Tigrinya',	NULL,	'no'),
(430,	'tiv',	NULL,	NULL,	'Tiv',	NULL,	'no'),
(431,	'tkl',	NULL,	NULL,	'Tokelau',	NULL,	'no'),
(432,	'tlh',	NULL,	NULL,	'Klingon; tlhIngan-Hol',	NULL,	'no'),
(433,	'tli',	NULL,	NULL,	'Tlingit',	NULL,	'no'),
(434,	'tmh',	NULL,	NULL,	'Tamashek',	NULL,	'no'),
(435,	'tog',	NULL,	NULL,	'Tonga (Nyasa)',	NULL,	'no'),
(436,	'ton',	NULL,	'to',	'Tonga (Tonga Islands)',	NULL,	'no'),
(437,	'tpi',	NULL,	NULL,	'Tok Pisin',	NULL,	'no'),
(438,	'tsi',	NULL,	NULL,	'Tsimshian',	NULL,	'no'),
(439,	'tsn',	NULL,	'tn',	'Tswana',	NULL,	'no'),
(440,	'tso',	NULL,	'ts',	'Tsonga',	NULL,	'no'),
(441,	'tuk',	NULL,	'tk',	'Turkmen',	NULL,	'no'),
(442,	'tum',	NULL,	NULL,	'Tumbuka',	NULL,	'no'),
(443,	'tup',	NULL,	NULL,	'Tupi languages',	NULL,	'no'),
(444,	'tur',	NULL,	'tr',	'Turkish',	NULL,	'no'),
(445,	'tut',	NULL,	NULL,	'Altaic (Other)',	NULL,	'no'),
(446,	'tvl',	NULL,	NULL,	'Tuvalu',	NULL,	'no'),
(447,	'twi',	NULL,	'tw',	'Twi',	NULL,	'no'),
(448,	'tyv',	NULL,	NULL,	'Tuvinian',	NULL,	'no'),
(449,	'udm',	NULL,	NULL,	'Udmurt',	NULL,	'no'),
(450,	'uga',	NULL,	NULL,	'Ugaritic',	NULL,	'no'),
(451,	'uig',	NULL,	'ug',	'Uighur; Uyghur',	NULL,	'no'),
(452,	'ukr',	NULL,	'uk',	'Ukrainian',	NULL,	'no'),
(453,	'umb',	NULL,	NULL,	'Umbundu',	NULL,	'no'),
(454,	'und',	NULL,	NULL,	'Undetermined',	NULL,	'no'),
(455,	'urd',	NULL,	'ur',	'Urdu',	NULL,	'no'),
(456,	'uzb',	NULL,	'uz',	'Uzbek',	NULL,	'no'),
(457,	'vai',	NULL,	NULL,	'Vai',	NULL,	'no'),
(458,	'ven',	NULL,	've',	'Venda',	NULL,	'no'),
(459,	'vie',	NULL,	'vi',	'Vietnamese',	NULL,	'no'),
(460,	'vol',	NULL,	'vo',	'Volapük',	NULL,	'no'),
(461,	'vot',	NULL,	NULL,	'Votic',	NULL,	'no'),
(462,	'wak',	NULL,	NULL,	'Wakashan languages',	NULL,	'no'),
(463,	'wal',	NULL,	NULL,	'Walamo',	NULL,	'no'),
(464,	'war',	NULL,	NULL,	'Waray',	NULL,	'no'),
(465,	'was',	NULL,	NULL,	'Washo',	NULL,	'no'),
(466,	'wen',	NULL,	NULL,	'Sorbian languages',	NULL,	'no'),
(467,	'wln',	NULL,	'wa',	'Walloon',	NULL,	'no'),
(468,	'wol',	NULL,	'wo',	'Wolof',	NULL,	'no'),
(469,	'xal',	NULL,	NULL,	'Kalmyk; Oirat',	NULL,	'no'),
(470,	'xho',	NULL,	'xh',	'Xhosa',	NULL,	'no'),
(471,	'yao',	NULL,	NULL,	'Yao',	NULL,	'no'),
(472,	'yap',	NULL,	NULL,	'Yapese',	NULL,	'no'),
(473,	'yid',	NULL,	'yi',	'Yiddish',	NULL,	'no'),
(474,	'yor',	NULL,	'yo',	'Yoruba',	NULL,	'no'),
(475,	'ypk',	NULL,	NULL,	'Yupik languages',	NULL,	'no'),
(476,	'zap',	NULL,	NULL,	'Zapotec',	NULL,	'no'),
(477,	'zbl',	NULL,	NULL,	'Blissymbols; Blissymbolics; Bliss',	NULL,	'no'),
(478,	'zen',	NULL,	NULL,	'Zenaga',	NULL,	'no'),
(479,	'zha',	NULL,	'za',	'Zhuang; Chuang',	NULL,	'no'),
(480,	'zho',	'chi',	'zh',	'Chinese',	NULL,	'no'),
(481,	'znd',	NULL,	NULL,	'Zande languages',	NULL,	'no'),
(482,	'zul',	NULL,	'zu',	'Zulu',	NULL,	'no'),
(483,	'zun',	NULL,	NULL,	'Zuni',	NULL,	'no'),
(484,	'zxx',	NULL,	NULL,	'No linguistic content; Not applicable',	NULL,	'no'),
(485,	'zza',	NULL,	NULL,	'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki',	NULL,	'no');


-- languages_categories --
CREATE TABLE `languages_categories` (
  `language_category_id` int unsigned NOT NULL AUTO_INCREMENT,
  `language_id` int unsigned NOT NULL,
  `country_id` int unsigned DEFAULT NULL,
  `category_id` int unsigned NOT NULL,
  `language_tag` varchar(25) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `label` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type_category_id` int unsigned NOT NULL,
  `sequence` tinyint unsigned DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`language_category_id`),
  UNIQUE KEY `language_tag` (`language_tag`),
  UNIQUE KEY `language_country_type_category` (`language_id`,`type_category_id`,`category_id`,`country_id`),
  KEY `language_id` (`language_id`),
  KEY `category_id` (`category_id`),
  KEY `type_category_id` (`type_category_id`),
  KEY `country_id` (`country_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `_relations` (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES (DATABASE(), 'languages', 'language_id', DATABASE(), 'languages_categories', 'language_category_id', 'language_id', 'delete');
INSERT INTO `_relations` (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES (DATABASE(), 'categories', 'category_id', DATABASE(), 'languages_categories', 'language_category_id', 'category_id', 'no-delete');
INSERT INTO `_relations` (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`)  VALUES (DATABASE(), 'categories', 'category_id', DATABASE(), 'languages_categories', 'language_category_id', 'type_category_id', 'no-delete');
INSERT INTO `_relations` (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES (DATABASE(), 'countries', 'country_id', DATABASE(), 'languages_categories', 'language_category_id', 'country_id', 'no-delete');

INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Language', NULL, NULL, 'language', '&alias=language&use_subtree=1', NULL, NOW());
INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Register', NULL, /*_ID categories language _*/, 'language/register', '&alias=language/register&no_append=1&own_type_category=1', NULL, NOW());
INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Neutral', NULL, /*_ID categories language/register _*/, 'language/register/neutral', '&alias=language/register/neutral', 1, NOW());
INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Formal', NULL, /*_ID categories language/register _*/, 'language/register/formal', '&alias=language/register/formal&default_language_register=1', 2, NOW());
INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Informal', NULL, /*_ID categories language/register _*/, 'language/register/informal', '&alias=language/register/informal', 3, NOW());


-- logins --
CREATE TABLE `logins` (
  `login_id` int unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(100) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `login_rights` enum('admin','read and write','read') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'read',
  `password` varchar(60) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `password_change` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no',
  `logged_in` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no',
  `last_click` int unsigned DEFAULT NULL,
  `active` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'yes',
  `login_category_id` int unsigned DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`login_id`),
  UNIQUE KEY `benutzername` (`username`),
  KEY `login_category_id` (`login_category_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'logins', 'login_id', 'login_category_id', 'no-delete');

INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Logins', NULL, NULL, 'logins', '&alias=logins', NULL, NOW());


-- redirects --
CREATE TABLE `redirects` (
  `redirect_id` int unsigned NOT NULL AUTO_INCREMENT,
  `old_url` varchar(160) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `new_url` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `code` smallint unsigned NOT NULL DEFAULT '301',
  `area` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website_id` int unsigned NOT NULL DEFAULT '1',
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`redirect_id`),
  UNIQUE KEY `old_url_website_id` (`old_url`,`website_id`),
  KEY `area` (`area`),
  KEY `website_id` (`website_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'websites', 'website_id', (SELECT DATABASE()), 'redirects', 'redirect_id', 'website_id', 'delete');


-- text --
CREATE TABLE `text` (
  `text_id` int unsigned NOT NULL AUTO_INCREMENT,
  `text` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `more_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `area` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`text_id`),
  UNIQUE KEY `text` (`text`(250)),
  KEY `area` (`area`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- tokens --
CREATE TABLE `tokens` (
  `token_id` int unsigned NOT NULL AUTO_INCREMENT,
  `access_token` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `access_token_expires` datetime NOT NULL,
  `login_id` int unsigned NOT NULL,
  `client_identifier` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `client_secret` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `refresh_token` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created` datetime NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`token_id`),
  UNIQUE KEY `access_token` (`access_token`),
  UNIQUE KEY `client_identifier` (`client_identifier`),
  UNIQUE KEY `login_id` (`login_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'logins', 'login_id', (SELECT DATABASE()), 'tokens', 'token_id', 'login_id', 'delete');


-- webpages --
CREATE TABLE `webpages` (
  `page_id` int unsigned NOT NULL AUTO_INCREMENT,
  `website_id` int unsigned NOT NULL DEFAULT '1',
  `title` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `identifier` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `ending` enum('.html','/','none') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'none',
  `sequence` tinyint NOT NULL,
  `mother_page_id` int unsigned DEFAULT NULL,
  `live` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'yes',
  `parameters` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`page_id`),
  UNIQUE KEY `identifier_website_id` (`identifier`,`website_id`),
  KEY `mother_page_id` (`mother_page_id`),
  KEY `website_id` (`website_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'webpages', 'page_id', (SELECT DATABASE()), 'webpages', 'page_id', 'mother_page_id', 'no-delete');

INSERT INTO `webpages` (`page_id`, `title`, `content`, `identifier`, `ending`, `sequence`, `mother_page_id`, `live`, `parameters`, `last_update`) VALUES
(1,	'Website',	'Hello World',	'/',	'none',	1,	NULL,	'yes',	NULL,	NOW()),
(2,	'Internal Area',	'%%% include internal-area %%%',	'/db',	'/',	2,	NULL,	'yes',	'&edit=admin',	NOW()),
(3,	'Login',	'%%% request login %%%',	'/login',	'/',	0,	2,	'yes',	'&edit=admin',	NOW()),
(4,	'Logout',	'%%% request logout %%%',	'/logout',	'/',	10,	2,	'yes',	'&edit=admin',	NOW()),
(5,	'Tables',	'%%% tables * %%%',	'/db*',	'none',	1,	2,	'yes',	'&edit=admin',	NOW()),
(6,	'Help',	'%%% request helptext * %%%',	'/help*',	'none',	9,	2,	'yes',	'&breadcrumbs_h1_prefix=1',	NOW()),
(7,	'Maintenance',	'%%% request maintenance %%%',	'/db/maintenance',	'/',	7,	2,	'yes',	'&edit=admin',	NOW()),
(8,	'Adminer',	'%%% request adminer %%%',	'/db/adminer',	'/',	7,	2,	'yes',	'&edit=admin',	NOW()),
(9,	'Website Settings',	'%%% forms settings-website %%%',	'/db/settings',	'none',	10,	2,	'yes',	'&edit=admin',	NOW()),
(10,	'Files',	'%%% request medium * %%%',	'/files*',	'/',	10,	1,	'yes',	'&edit=admin',	NOW()),
(11,	'Media',	'%%% forms media %%%',	'/db/media',	'/',	9,	2,	'yes',	'&edit=admin',	NOW()),
(12,	'Media',	'%%% forms media * %%%',	'/db/media*',	'/',	1,	11,	'yes',	'&edit=admin',	NOW()),
(13,	'Robots', '%%% set content_type=txt %%%\n# robots.txt', '/robots.txt', 'none', 40, 1, 'yes', '&edit=admin', NOW());


-- webpages_categories --
CREATE TABLE `webpages_categories` (
  `page_category_id` int unsigned NOT NULL AUTO_INCREMENT,
  `page_id` int unsigned NOT NULL,
  `category_id` int unsigned NOT NULL,
  `property` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type_category_id` int unsigned NOT NULL,
  `sequence` tinyint unsigned DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`page_category_id`),
  UNIQUE KEY `page_id_category_id` (`page_id`,`category_id`),
  KEY `category_id` (`category_id`),
  KEY `type_category_id` (`type_category_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'webpages_categories', 'page_category_id', 'category_id', 'no-delete');
INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'webpages', 'page_id', (SELECT DATABASE()), 'webpages_categories', 'page_category_id', 'page_id', 'delete');

INSERT INTO categories (`category`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Menu', NULL, NULL, 'menu', '&alias=menu', NULL, NOW());
INSERT INTO categories (`category`, `category_short`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Top Menu', 'Top', NULL, /*_ID categories menu _*/, 'menu/top', '&alias=menu/top&main_menu=1', 1, NOW());
INSERT INTO categories (`category`, `category_short`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Bottom Menu', 'Bottom', NULL, /*_ID categories menu _*/, 'menu/bottom', '&alias=menu/bottom', 2, NOW());
INSERT INTO categories (`category`, `category_short`, `description`, `main_category_id`, `path`, `parameters`, `sequence`, `last_update`) VALUES ('Internal Menu', 'Internal', NULL, /*_ID categories menu _*/, 'menu/internal', '&alias=menu/internal&session_menu=1', 3, NOW());


-- webpages_media --
CREATE TABLE `webpages_media` (
  `page_medium_id` int unsigned NOT NULL AUTO_INCREMENT,
  `page_id` int unsigned NOT NULL,
  `medium_id` int unsigned NOT NULL,
  `sequence` tinyint NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`page_medium_id`),
  UNIQUE KEY `page_id` (`page_id`,`sequence`),
  UNIQUE KEY `medium_id` (`medium_id`,`page_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'media', 'medium_id', (SELECT DATABASE()), 'webpages_media', 'page_medium_id', 'medium_id', 'no-delete');
INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'webpages', 'page_id', (SELECT DATABASE()), 'webpages_media', 'page_medium_id', 'page_id', 'delete');


-- websites --
CREATE TABLE `websites` (
  `website_id` int unsigned NOT NULL AUTO_INCREMENT,
  `website` varchar(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `domain` varchar(63) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`website_id`),
  UNIQUE KEY `website` (`website`),
  UNIQUE KEY `domainname` (`domain`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `websites` (`website_id`, `website`, `domain`) VALUES
(1,	'All Websites',	'*');

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'websites', 'website_id', (SELECT DATABASE()), 'webpages', 'page_id', 'website_id', 'no-delete');
