/**
 * default module
 * SQL for installation
 *
 * Part of »Zugzwang Project«
 * https://www.zugzwang.org/modules/default
 *
 * @author Gustaf Mossakowski <gustaf@koenige.org>
 * @copyright Copyright © 2020-2021 Gustaf Mossakowski
 * @license http://opensource.org/licenses/lgpl-3.0.html LGPL-3.0
 */


-- _logging --
CREATE TABLE `_logging` (
  `log_id` int unsigned NOT NULL AUTO_INCREMENT,
  `query` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `record_id` int unsigned DEFAULT NULL,
  `user` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `record_id` (`record_id`),
  KEY `last_update` (`last_update`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- _relations --
CREATE TABLE `_relations` (
  `rel_id` int unsigned NOT NULL AUTO_INCREMENT,
  `master_db` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `master_table` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `master_field` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `detail_db` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `detail_table` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `detail_field` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `delete` enum('delete','ask','no-delete','update') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no-delete',
  `detail_id_field` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `detail_url` varchar(63) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  PRIMARY KEY (`rel_id`),
  UNIQUE KEY `master_db` (`master_db`,`master_table`,`master_field`,`detail_db`,`detail_table`,`detail_field`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;


-- _settings --
CREATE TABLE `_settings` (
  `setting_id` int unsigned NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `setting_value` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `explanation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `website_id` int unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`setting_id`),
  UNIQUE KEY `setting_key_website_id` (`setting_key`,`website_id`),
  KEY `website_id` (`website_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'websites', 'website_id', (SELECT DATABASE()), '_settings', 'setting_id', 'website_id', 'delete');


-- _translationfields --
CREATE TABLE `_translationfields` (
  `translationfield_id` int unsigned NOT NULL AUTO_INCREMENT,
  `db_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `table_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `field_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `field_type` enum('varchar','text') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'varchar',
  PRIMARY KEY (`translationfield_id`),
  UNIQUE KEY `db_name` (`db_name`,`table_name`,`field_name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

INSERT INTO `_translationfields` (`translationfield_id`, `db_name`, `table_name`, `field_name`, `field_type`) VALUES
(1,	(SELECT DATABASE()),	'text',	'text',	'varchar'),
(2,	(SELECT DATABASE()),	'countries',	'country',	'varchar');


-- _translations_text --
CREATE TABLE `_translations_text` (
  `translation_id` int unsigned NOT NULL AUTO_INCREMENT,
  `translationfield_id` int unsigned NOT NULL,
  `field_id` int unsigned NOT NULL,
  `translation` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `language_id` int unsigned NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`translation_id`),
  UNIQUE KEY `field_id` (`field_id`,`translationfield_id`,`language_id`),
  KEY `language_id` (`language_id`),
  KEY `translationfield_id` (`translationfield_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'languages', 'language_id', (SELECT DATABASE()), '_translations_text', 'translation_id', 'language_id', 'no-delete');
INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), '_translationfields', 'translationfield_id', (SELECT DATABASE()), '_translations_text', 'translation_id', 'translationfield_id', 'no-delete');


-- _translations_varchar --
CREATE TABLE `_translations_varchar` (
  `translation_id` int unsigned NOT NULL AUTO_INCREMENT,
  `translationfield_id` int unsigned NOT NULL,
  `field_id` int unsigned NOT NULL,
  `translation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `language_id` int unsigned NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`translation_id`),
  UNIQUE KEY `field_id` (`field_id`,`translationfield_id`,`language_id`),
  KEY `translationfield_id` (`translationfield_id`),
  KEY `language_id` (`language_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'languages', 'language_id', (SELECT DATABASE()), '_translations_varchar', 'translation_id', 'language_id', 'no-delete');
INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), '_translationfields', 'translationfield_id', (SELECT DATABASE()), '_translations_varchar', 'translation_id', 'translationfield_id', 'no-delete');


INSERT INTO `_translations_varchar` (`translation_id`, `translationfield_id`, `field_id`, `translation`, `language_id`, `last_update`) VALUES
(1,	2,	224,	'Vereinigte Arabische Emirate',	105,	NOW()),
(2,	2,	9,	'Antigua und Barbuda',	105,	NOW()),
(3,	2,	2,	'Albanien',	105,	NOW()),
(4,	2,	11,	'Armenien',	105,	NOW()),
(5,	2,	242,	'Åland',	105,	NOW()),
(6,	2,	8,	'Antarktis',	105,	NOW()),
(7,	2,	10,	'Argentinien',	105,	NOW()),
(8,	2,	4,	'Amerikanisch-Samoa',	105,	NOW()),
(9,	2,	14,	'Österreich',	105,	NOW()),
(10,	2,	13,	'Australien',	105,	NOW()),
(11,	2,	15,	'Aserbaidschan',	105,	NOW()),
(12,	2,	27,	'Bosnien und Herzegowina',	105,	NOW()),
(13,	2,	18,	'Bangladesch',	105,	NOW()),
(14,	2,	21,	'Belgien',	105,	NOW()),
(15,	2,	33,	'Bulgarien',	105,	NOW()),
(16,	2,	26,	'Bolivien',	105,	NOW()),
(17,	2,	30,	'Brasilien',	105,	NOW()),
(18,	2,	29,	'Bouvetinsel',	105,	NOW()),
(19,	2,	38,	'Kanada',	105,	NOW()),
(20,	2,	46,	'Kokosinseln',	105,	NOW()),
(21,	2,	50,	'Kongo, Demokratische Republik',	105,	NOW()),
(22,	2,	41,	'Zentralafrikanische Republik',	105,	NOW()),
(23,	2,	49,	'Kongo',	105,	NOW()),
(24,	2,	206,	'Schweiz',	105,	NOW()),
(25,	2,	53,	'Côte d’Ivoire',	105,	NOW()),
(26,	2,	51,	'Cookinseln',	105,	NOW()),
(27,	2,	37,	'Kamerun',	105,	NOW()),
(28,	2,	47,	'Kolumbien',	105,	NOW()),
(29,	2,	189,	'Serbien',	105,	NOW()),
(30,	2,	39,	'Cabo Verde',	105,	NOW()),
(31,	2,	45,	'Weihnachtsinsel',	105,	NOW()),
(32,	2,	56,	'Zypern',	105,	NOW()),
(33,	2,	57,	'Tschechien',	105,	NOW()),
(34,	2,	80,	'Deutschland',	105,	NOW()),
(35,	2,	59,	'Dschibuti',	105,	NOW()),
(36,	2,	58,	'Dänemark',	105,	NOW()),
(37,	2,	61,	'Dominikanische Republik',	105,	NOW()),
(38,	2,	3,	'Algerien',	105,	NOW()),
(39,	2,	67,	'Estland',	105,	NOW()),
(40,	2,	63,	'Ägypten',	105,	NOW()),
(41,	2,	236,	'Westsahara',	105,	NOW()),
(42,	2,	199,	'Spanien',	105,	NOW()),
(43,	2,	68,	'Äthiopien',	105,	NOW()),
(44,	2,	72,	'Finnland',	105,	NOW()),
(45,	2,	69,	'Falklandinseln',	105,	NOW()),
(46,	2,	139,	'Mikronesien',	105,	NOW()),
(47,	2,	70,	'Färöer',	105,	NOW()),
(48,	2,	73,	'Frankreich',	105,	NOW()),
(49,	2,	77,	'Gabun',	105,	NOW()),
(50,	2,	225,	'Großbritannien',	105,	NOW()),
(51,	2,	79,	'Georgien',	105,	NOW()),
(52,	2,	74,	'Französisch-Guayana',	105,	NOW()),
(53,	2,	84,	'Grönland',	105,	NOW()),
(54,	2,	65,	'Äquatorialguinea',	105,	NOW()),
(55,	2,	83,	'Griechenland',	105,	NOW()),
(56,	2,	198,	'Südgeorgien und die Südlichen Sandwichinseln',	105,	NOW()),
(57,	2,	93,	'Heard und McDonaldinseln',	105,	NOW()),
(58,	2,	54,	'Kroatien',	105,	NOW()),
(59,	2,	97,	'Ungarn',	105,	NOW()),
(60,	2,	100,	'Indonesien',	105,	NOW()),
(61,	2,	103,	'Irland',	105,	NOW()),
(62,	2,	99,	'Indien',	105,	NOW()),
(63,	2,	31,	'Britisches Territorium im Indischen Ozean',	105,	NOW()),
(64,	2,	102,	'Irak',	105,	NOW()),
(65,	2,	101,	'Iran',	105,	NOW()),
(66,	2,	98,	'Island',	105,	NOW()),
(67,	2,	105,	'Italien',	105,	NOW()),
(68,	2,	108,	'Jordanien',	105,	NOW()),
(69,	2,	106,	'Jamaika',	105,	NOW()),
(70,	2,	110,	'Kenia',	105,	NOW()),
(71,	2,	115,	'Kirgisistan',	105,	NOW()),
(72,	2,	36,	'Kambodscha',	105,	NOW()),
(73,	2,	48,	'Komoren',	105,	NOW()),
(74,	2,	180,	'St. Kitts und Nevis',	105,	NOW()),
(75,	2,	112,	'Korea, Demokratische Volksrepublik',	105,	NOW()),
(76,	2,	113,	'Korea, Republik',	105,	NOW()),
(77,	2,	109,	'Kasachstan',	105,	NOW()),
(78,	2,	118,	'Libanon',	105,	NOW()),
(79,	2,	117,	'Lettland',	105,	NOW()),
(80,	2,	124,	'Luxemburg',	105,	NOW()),
(81,	2,	123,	'Litauen',	105,	NOW()),
(82,	2,	121,	'Libyen',	105,	NOW()),
(83,	2,	144,	'Marokko',	105,	NOW()),
(84,	2,	140,	'Moldau',	105,	NOW()),
(85,	2,	127,	'Madagaskar',	105,	NOW()),
(86,	2,	133,	'Marshallinseln',	105,	NOW()),
(87,	2,	126,	'Nordmazedonien',	105,	NOW()),
(88,	2,	142,	'Mongolei',	105,	NOW()),
(89,	2,	159,	'Nördliche Marianen',	105,	NOW()),
(90,	2,	135,	'Mauretanien',	105,	NOW()),
(91,	2,	130,	'Malediven',	105,	NOW()),
(92,	2,	138,	'Mexiko',	105,	NOW()),
(93,	2,	145,	'Mosambik',	105,	NOW()),
(94,	2,	152,	'Neukaledonien',	105,	NOW()),
(95,	2,	158,	'Norfolkinsel',	105,	NOW()),
(96,	2,	150,	'Niederlande',	105,	NOW()),
(97,	2,	160,	'Norwegen',	105,	NOW()),
(98,	2,	153,	'Neuseeland',	105,	NOW()),
(99,	2,	75,	'Französisch-Polynesien',	105,	NOW()),
(100,	2,	166,	'Papua-Neuguinea',	105,	NOW()),
(101,	2,	169,	'Philippinen',	105,	NOW()),
(102,	2,	171,	'Polen',	105,	NOW()),
(103,	2,	182,	'Saint-Pierre und Miquelon',	105,	NOW()),
(104,	2,	164,	'Palästina',	105,	NOW()),
(105,	2,	174,	'Katar',	105,	NOW()),
(106,	2,	176,	'Rumänien',	105,	NOW()),
(107,	2,	177,	'Russland',	105,	NOW()),
(108,	2,	178,	'Ruanda',	105,	NOW()),
(109,	2,	187,	'Saudi-Arabien',	105,	NOW()),
(110,	2,	195,	'Salomonen',	105,	NOW()),
(111,	2,	190,	'Seychellen',	105,	NOW()),
(112,	2,	205,	'Schweden',	105,	NOW()),
(113,	2,	192,	'Singapur',	105,	NOW()),
(114,	2,	179,	'St. Helena',	105,	NOW()),
(115,	2,	194,	'Slowenien',	105,	NOW()),
(116,	2,	203,	'Spitzbergen und Jan Mayen',	105,	NOW()),
(117,	2,	193,	'Slowakei',	105,	NOW()),
(118,	2,	202,	'Suriname',	105,	NOW()),
(119,	2,	241,	'Südsudan',	105,	NOW()),
(120,	2,	186,	'São Tomé und Príncipe',	105,	NOW()),
(121,	2,	207,	'Syrien',	105,	NOW()),
(122,	2,	204,	'Eswatini',	105,	NOW()),
(123,	2,	220,	'Turks- und Caicosinseln',	105,	NOW()),
(124,	2,	42,	'Tschad',	105,	NOW()),
(125,	2,	76,	'Französische Südgebiete',	105,	NOW()),
(126,	2,	209,	'Tadschikistan',	105,	NOW()),
(127,	2,	212,	'Timor-Leste',	105,	NOW()),
(128,	2,	217,	'Tunesien',	105,	NOW()),
(129,	2,	218,	'Türkei',	105,	NOW()),
(130,	2,	216,	'Trinidad und Tobago',	105,	NOW()),
(131,	2,	210,	'Tansania',	105,	NOW()),
(132,	2,	226,	'Vereinigte Staaten',	105,	NOW()),
(133,	2,	229,	'Usbekistan',	105,	NOW()),
(134,	2,	94,	'Vatikanstadt',	105,	NOW()),
(135,	2,	183,	'St. Vincent und die Grenadinen',	105,	NOW()),
(136,	2,	233,	'Britische Jungferninseln',	105,	NOW()),
(137,	2,	234,	'Amerikanische Jungferninseln',	105,	NOW()),
(138,	2,	232,	'Vietnam',	105,	NOW()),
(139,	2,	235,	'Wallis und Futuna',	105,	NOW()),
(140,	2,	237,	'Jemen',	105,	NOW()),
(141,	2,	197,	'Südafrika',	105,	NOW()),
(142,	2,	238,	'Sambia',	105,	NOW()),
(143,	2,	239,	'Simbabwe',	105,	NOW()),
(144,	2,	243,	'Karibische Niederlande',	105,	NOW()),
(145,	2,	249,	'Saint Martin (Französischer Teil)',	105,	NOW()),
(146,	2,	250,	'Sint Maarten (Holländischer Teil)',	105,	NOW()),
(147,	2,	28,	'Botsuana',	105,	NOW()),
(148,	2,	55,	'Kuba',	105,	NOW()),
(149,	2,	71,	'Fidschi',	105,	NOW()),
(150,	2,	181,	'St. Lucia',	105,	NOW());


-- _uris --
CREATE TABLE `_uris` (
  `uri_id` int unsigned NOT NULL AUTO_INCREMENT,
  `uri_scheme` varchar(15) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `uri_host` varchar(63) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `uri_path` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `uri_query` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `content_type` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `character_encoding` varchar(31) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `content_length` int unsigned NOT NULL,
  `user` varchar(64) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'none',
  `status_code` smallint NOT NULL,
  `etag_md5` varchar(32) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `hits` int unsigned NOT NULL,
  `first_access` datetime NOT NULL,
  `last_access` datetime NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uri_id`),
  UNIQUE KEY `uri_scheme_uri_host_uri_path_uri_query_user` (`uri_scheme`,`uri_host`,`uri_path`,`uri_query`,`user`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;


-- categories --
CREATE TABLE `categories` (
  `category_id` int unsigned NOT NULL AUTO_INCREMENT,
  `category` varchar(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `main_category_id` int unsigned DEFAULT NULL,
  `path` varchar(100) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `parameters` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sequence` tinyint unsigned DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`),
  UNIQUE KEY `path` (`path`),
  KEY `main_category_id` (`main_category_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'categories', 'category_id', (SELECT DATABASE()), 'categories', 'category_id', 'main_category_id', 'no-delete');


-- countries --
CREATE TABLE `countries` (
  `country_id` int unsigned NOT NULL AUTO_INCREMENT,
  `country_code` char(2) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `country_code3` char(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `ioc_code` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `country` varchar(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `website` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no',
  PRIMARY KEY (`country_id`),
  UNIQUE KEY `country_code` (`country_code`),
  KEY `website` (`website`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `countries` (`country_id`, `country_code`, `country_code3`, `country`, `website`) VALUES
(1,	'AF',	'AFG',	'Afghanistan',	'no'),
(2,	'AL',	'ALB',	'Albania',	'no'),
(3,	'DZ',	'DZA',	'Algeria',	'no'),
(4,	'AS',	'ASM',	'American Samoa',	'no'),
(5,	'AD',	'AND',	'Andorra',	'no'),
(6,	'AO',	'AGO',	'Angola',	'no'),
(7,	'AI',	'AIA',	'Anguilla',	'no'),
(8,	'AQ',	'ATA',	'Antarctica',	'no'),
(9,	'AG',	'ATG',	'Antigua and Barbuda',	'no'),
(10,	'AR',	'ARG',	'Argentina',	'no'),
(11,	'AM',	'ARM',	'Armenia',	'no'),
(12,	'AW',	'ABW',	'Aruba',	'no'),
(13,	'AU',	'AUS',	'Australia',	'no'),
(14,	'AT',	'AUT',	'Austria',	'no'),
(15,	'AZ',	'AZE',	'Azerbaijan',	'no'),
(16,	'BS',	'BHS',	'Bahamas',	'no'),
(17,	'BH',	'BHR',	'Bahrain',	'no'),
(18,	'BD',	'BGD',	'Bangladesh',	'no'),
(19,	'BB',	'BRB',	'Barbados',	'no'),
(20,	'BY',	'BLR',	'Belarus',	'yes'),
(21,	'BE',	'BEL',	'Belgium',	'no'),
(22,	'BZ',	'BLZ',	'Belize',	'no'),
(23,	'BJ',	'BEN',	'Benin',	'no'),
(24,	'BM',	'BMU',	'Bermuda',	'no'),
(25,	'BT',	'BTN',	'Bhutan',	'no'),
(26,	'BO',	'BOL',	'Bolivia',	'no'),
(27,	'BA',	'BIH',	'Bosnia and Herzegovina',	'no'),
(28,	'BW',	'BWA',	'Botswana',	'no'),
(29,	'BV',	'BVT',	'Bouvet Island',	'no'),
(30,	'BR',	'BRA',	'Brazil',	'no'),
(31,	'IO',	'IOT',	'British Indian Ocean Territory',	'no'),
(32,	'BN',	'BRN',	'Brunei Darussalam',	'no'),
(33,	'BG',	'BGR',	'Bulgaria',	'no'),
(34,	'BF',	'BFA',	'Burkina Faso',	'no'),
(35,	'BI',	'BDI',	'Burundi',	'no'),
(36,	'KH',	'KHM',	'Cambodia',	'no'),
(37,	'CM',	'CMR',	'Cameroon',	'no'),
(38,	'CA',	'CAN',	'Canada',	'no'),
(39,	'CV',	'CPV',	'Cape Verde',	'no'),
(40,	'KY',	'CYM',	'Cayman Islands',	'no'),
(41,	'CF',	'CAF',	'Central African Republic',	'no'),
(42,	'TD',	'TCD',	'Chad',	'no'),
(43,	'CL',	'CHL',	'Chile',	'no'),
(44,	'CN',	'CHN',	'China',	'no'),
(45,	'CX',	'CXR',	'Christmas Island',	'no'),
(46,	'CC',	'CCK',	'Cocos (Keeling) Islands',	'no'),
(47,	'CO',	'COL',	'Colombia',	'no'),
(48,	'KM',	'COM',	'Comoros',	'no'),
(49,	'CG',	'COG',	'Congo',	'no'),
(50,	'CD',	'COD',	'Congo, The Democratic Republic of the',	'no'),
(51,	'CK',	'COK',	'Cook Islands',	'no'),
(52,	'CR',	'CRI',	'Costa Rica',	'no'),
(53,	'CI',	'CIV',	'Cote D\'Ivoire',	'no'),
(54,	'HR',	'HRV',	'Croatia',	'no'),
(55,	'CU',	'CUB',	'Cuba',	'no'),
(56,	'CY',	'CYP',	'Cyprus',	'no'),
(57,	'CZ',	'CZE',	'Czechia',	'no'),
(58,	'DK',	'DNK',	'Denmark',	'no'),
(59,	'DJ',	'DJI',	'Djibouti',	'no'),
(60,	'DM',	'DMA',	'Dominica',	'no'),
(61,	'DO',	'DOM',	'Dominican Republic',	'no'),
(62,	'EC',	'ECU',	'Ecuador',	'no'),
(63,	'EG',	'EGY',	'Egypt',	'no'),
(64,	'SV',	'SLV',	'El Salvador',	'no'),
(65,	'GQ',	'GNQ',	'Equatorial Guinea',	'no'),
(66,	'ER',	'ERI',	'Eritrea',	'no'),
(67,	'EE',	'EST',	'Estonia',	'no'),
(68,	'ET',	'ETH',	'Ethiopia',	'no'),
(69,	'FK',	'FLK',	'Falkland Islands (Malvinas)',	'no'),
(70,	'FO',	'FRO',	'Faroe Islands',	'no'),
(71,	'FJ',	'FJI',	'Fiji',	'no'),
(72,	'FI',	'FIN',	'Finland',	'no'),
(73,	'FR',	'FRA',	'France',	'no'),
(74,	'GF',	'GUF',	'French Guiana',	'no'),
(75,	'PF',	'PYF',	'French Polynesia',	'no'),
(76,	'TF',	'ATF',	'French Southern Territories',	'no'),
(77,	'GA',	'GAB',	'Gabon',	'no'),
(78,	'GM',	'GMB',	'Gambia',	'no'),
(79,	'GE',	'GEO',	'Georgia',	'no'),
(80,	'DE',	'DEU',	'Germany',	'yes'),
(81,	'GH',	'GHA',	'Ghana',	'no'),
(82,	'GI',	'GIB',	'Gibraltar',	'no'),
(83,	'GR',	'GRC',	'Greece',	'no'),
(84,	'GL',	'GRL',	'Greenland',	'no'),
(85,	'GD',	'GRD',	'Grenada',	'no'),
(86,	'GP',	'GLP',	'Guadeloupe',	'no'),
(87,	'GU',	'GUM',	'Guam',	'no'),
(88,	'GT',	'GTM',	'Guatemala',	'no'),
(89,	'GN',	'GIN',	'Guinea',	'no'),
(90,	'GW',	'GNB',	'Guinea-Bissau',	'no'),
(91,	'GY',	'GUY',	'Guyana',	'no'),
(92,	'HT',	'HTI',	'Haiti',	'no'),
(93,	'HM',	'HMD',	'Heard Island and McDonald Islands',	'no'),
(94,	'VA',	'VAT',	'Holy See (Vatican City State)',	'no'),
(95,	'HN',	'HND',	'Honduras',	'no'),
(96,	'HK',	'HKG',	'Hong Kong',	'no'),
(97,	'HU',	'HUN',	'Hungary',	'no'),
(98,	'IS',	'ISL',	'Iceland',	'no'),
(99,	'IN',	'IND',	'India',	'no'),
(100,	'ID',	'IDN',	'Indonesia',	'no'),
(101,	'IR',	'IRN',	'Iran',	'no'),
(102,	'IQ',	'IRQ',	'Iraq',	'no'),
(103,	'IE',	'IRL',	'Ireland',	'no'),
(104,	'IL',	'ISR',	'Israel',	'no'),
(105,	'IT',	'ITA',	'Italy',	'no'),
(106,	'JM',	'JAM',	'Jamaica',	'no'),
(107,	'JP',	'JPN',	'Japan',	'no'),
(108,	'JO',	'JOR',	'Jordan',	'no'),
(109,	'KZ',	'KAZ',	'Kazakhstan',	'no'),
(110,	'KE',	'KEN',	'Kenya',	'no'),
(111,	'KI',	'KIR',	'Kiribati',	'no'),
(112,	'KP',	'PRK',	'Korea, Democratic People\'s Republic of',	'no'),
(113,	'KR',	'KOR',	'Korea, Republic of',	'no'),
(114,	'KW',	'KWT',	'Kuwait',	'no'),
(115,	'KG',	'KGZ',	'Kyrgyzstan',	'no'),
(116,	'LA',	'LAO',	'Laos',	'no'),
(117,	'LV',	'LVA',	'Latvia',	'no'),
(118,	'LB',	'LBN',	'Lebanon',	'no'),
(119,	'LS',	'LSO',	'Lesotho',	'no'),
(120,	'LR',	'LBR',	'Liberia',	'no'),
(121,	'LY',	'LBY',	'Libya',	'no'),
(122,	'LI',	'LIE',	'Liechtenstein',	'no'),
(123,	'LT',	'LTU',	'Lithuania',	'no'),
(124,	'LU',	'LUX',	'Luxembourg',	'no'),
(125,	'MO',	'MAC',	'Macao',	'no'),
(126,	'MK',	'MKD',	'North Macedonia',	'no'),
(127,	'MG',	'MDG',	'Madagascar',	'no'),
(128,	'MW',	'MWI',	'Malawi',	'no'),
(129,	'MY',	'MYS',	'Malaysia',	'no'),
(130,	'MV',	'MDV',	'Maldives',	'no'),
(131,	'ML',	'MLI',	'Mali',	'no'),
(132,	'MT',	'MLT',	'Malta',	'no'),
(133,	'MH',	'MHL',	'Marshall Islands',	'no'),
(134,	'MQ',	'MTQ',	'Martinique',	'no'),
(135,	'MR',	'MRT',	'Mauritania',	'no'),
(136,	'MU',	'MUS',	'Mauritius',	'no'),
(137,	'YT',	'MYT',	'Mayotte',	'no'),
(138,	'MX',	'MEX',	'Mexico',	'no'),
(139,	'FM',	'FSM',	'Micronesia, Federated States of',	'no'),
(140,	'MD',	'MDA',	'Moldova',	'no'),
(141,	'MC',	'MCO',	'Monaco',	'no'),
(142,	'MN',	'MNG',	'Mongolia',	'no'),
(143,	'MS',	'MSR',	'Montserrat',	'no'),
(144,	'MA',	'MAR',	'Morocco',	'no'),
(145,	'MZ',	'MOZ',	'Mozambique',	'no'),
(146,	'MM',	'MMR',	'Myanmar',	'no'),
(147,	'NA',	'NAM',	'Namibia',	'no'),
(148,	'NR',	'NRU',	'Nauru',	'no'),
(149,	'NP',	'NPL',	'Nepal',	'no'),
(150,	'NL',	'NLD',	'Netherlands',	'no'),
(152,	'NC',	'NCL',	'New Caledonia',	'no'),
(153,	'NZ',	'NZL',	'New Zealand',	'no'),
(154,	'NI',	'NIC',	'Nicaragua',	'no'),
(155,	'NE',	'NER',	'Niger',	'no'),
(156,	'NG',	'NGA',	'Nigeria',	'no'),
(157,	'NU',	'NIU',	'Niue',	'no'),
(158,	'NF',	'NFK',	'Norfolk Island',	'no'),
(159,	'MP',	'MNP',	'Northern Mariana Islands',	'no'),
(160,	'NO',	'NOR',	'Norway',	'no'),
(161,	'OM',	'OMN',	'Oman',	'no'),
(162,	'PK',	'PAK',	'Pakistan',	'no'),
(163,	'PW',	'PLW',	'Palau',	'no'),
(164,	'PS',	'PSE',	'Palestine',	'no'),
(165,	'PA',	'PAN',	'Panama',	'no'),
(166,	'PG',	'PNG',	'Papua New Guinea',	'no'),
(167,	'PY',	'PRY',	'Paraguay',	'no'),
(168,	'PE',	'PER',	'Peru',	'no'),
(169,	'PH',	'PHL',	'Philippines',	'no'),
(170,	'PN',	'PCN',	'Pitcairn',	'no'),
(171,	'PL',	'POL',	'Poland',	'yes'),
(172,	'PT',	'PRT',	'Portugal',	'no'),
(173,	'PR',	'PRI',	'Puerto Rico',	'no'),
(174,	'QA',	'QAT',	'Qatar',	'no'),
(175,	'RE',	'REU',	'Réunion',	'no'),
(176,	'RO',	'ROU',	'Romania',	'no'),
(177,	'RU',	'RUS',	'Russian Federation',	'no'),
(178,	'RW',	'RWA',	'Rwanda',	'no'),
(179,	'SH',	'SHN',	'Saint Helena',	'no'),
(180,	'KN',	'KNA',	'Saint Kitts and Nevis',	'no'),
(181,	'LC',	'LCA',	'Saint Lucia',	'no'),
(182,	'PM',	'SPM',	'Saint Pierre and Miquelon',	'no'),
(183,	'VC',	'VCT',	'Saint Vincent and the Grenadines',	'no'),
(184,	'WS',	'WSM',	'Samoa',	'no'),
(185,	'SM',	'SMR',	'San Marino',	'no'),
(186,	'ST',	'STP',	'São Tomé and Príncipe',	'no'),
(187,	'SA',	'SAU',	'Saudi Arabia',	'no'),
(188,	'SN',	'SEN',	'Senegal',	'no'),
(189,	'RS',	'SRB',	'Serbia',	'no'),
(190,	'SC',	'SYC',	'Seychelles',	'no'),
(191,	'SL',	'SLE',	'Sierra Leone',	'no'),
(192,	'SG',	'SGP',	'Singapore',	'no'),
(193,	'SK',	'SVK',	'Slovakia',	'no'),
(194,	'SI',	'SVN',	'Slovenia',	'no'),
(195,	'SB',	'SLB',	'Solomon Islands',	'no'),
(196,	'SO',	'SOM',	'Somalia',	'no'),
(197,	'ZA',	'ZAF',	'South Africa',	'no'),
(198,	'GS',	'SGS',	'South Georgia and the South Sandwich Islands',	'no'),
(199,	'ES',	'ESP',	'Spain',	'no'),
(200,	'LK',	'LKA',	'Sri Lanka',	'no'),
(201,	'SD',	'SDN',	'Sudan',	'no'),
(202,	'SR',	'SUR',	'Suriname',	'no'),
(203,	'SJ',	'SJM',	'Svalbard and Jan Mayen',	'no'),
(204,	'SZ',	'SWZ',	'Eswatini',	'no'),
(205,	'SE',	'SWE',	'Sweden',	'no'),
(206,	'CH',	'CHE',	'Switzerland',	'no'),
(207,	'SY',	'SYR',	'Syria',	'no'),
(208,	'TW',	'TWN',	'Taiwan',	'no'),
(209,	'TJ',	'TJK',	'Tajikistan',	'no'),
(210,	'TZ',	'TZA',	'Tanzania',	'no'),
(211,	'TH',	'THA',	'Thailand',	'no'),
(212,	'TL',	'TLS',	'Timor-Leste',	'no'),
(213,	'TG',	'TGO',	'Togo',	'no'),
(214,	'TK',	'TKL',	'Tokelau',	'no'),
(215,	'TO',	'TON',	'Tonga',	'no'),
(216,	'TT',	'TTO',	'Trinidad and Tobago',	'no'),
(217,	'TN',	'TUN',	'Tunisia',	'no'),
(218,	'TR',	'TUR',	'Turkey',	'no'),
(219,	'TM',	'TKM',	'Turkmenistan',	'no'),
(220,	'TC',	'TCA',	'Turks and Caicos Islands',	'no'),
(221,	'TV',	'TUV',	'Tuvalu',	'no'),
(222,	'UG',	'UGA',	'Uganda',	'no'),
(223,	'UA',	'UKR',	'Ukraine',	'no'),
(224,	'AE',	'ARE',	'United Arab Emirates',	'no'),
(225,	'GB',	'GBR',	'United Kingdom',	'no'),
(226,	'US',	'USA',	'United States',	'no'),
(227,	'UM',	'UMI',	'United States Minor Outlying Islands',	'no'),
(228,	'UY',	'URY',	'Uruguay',	'no'),
(229,	'UZ',	'UZB',	'Uzbekistan',	'no'),
(230,	'VU',	'VUT',	'Vanuatu',	'no'),
(231,	'VE',	'VEN',	'Venezuela',	'no'),
(232,	'VN',	'VNM',	'Viet Nam',	'no'),
(233,	'VG',	'VGB',	'Virgin Islands, British',	'no'),
(234,	'VI',	'VIR',	'Virgin Islands, U.S.',	'no'),
(235,	'WF',	'WLF',	'Wallis and Futuna',	'no'),
(236,	'EH',	'ESH',	'Western Sahara',	'no'),
(237,	'YE',	'YEM',	'Yemen',	'no'),
(238,	'ZM',	'ZMB',	'Zambia',	'no'),
(239,	'ZW',	'ZWE',	'Zimbabwe',	'no'),
(240,	'ME',	'MNE',	'Montenegro',	'no'),
(241,	'SS',	'SSD',	'South Sudan',	'no'),
(242,	'AX',	'ALA',	'Åland Islands',	'no'),
(243,	'BQ',	'BES',	'Bonaire, Sint Eustatius and Saba',	'no'),
(244,	'BL',	'BLM',	'Saint Barthélemy',	'no'),
(245,	'CW',	'CUW',	'Curaçao',	'no'),
(246,	'GG',	'GGY',	'Guernsey',	'no'),
(247,	'IM',	'IMN',	'Isle of Man',	'no'),
(248,	'JE',	'JEY',	'Jersey',	'no'),
(249,	'MF',	'MAF',	'Saint Martin (French part)',	'no'),
(250,	'SX',	'SXM',	'Sint Maarten (Dutch part)',	'no'),
(251,	'XK',	'XKX',	'Kosovo', 'no');


-- languages --
CREATE TABLE `languages` (
  `language_id` int unsigned NOT NULL AUTO_INCREMENT,
  `iso_639_2t` char(3) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `iso_639_2b` char(3) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  `iso_639_1` char(2) CHARACTER SET latin1 COLLATE latin1_general_cs DEFAULT NULL,
  `language_de` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `language_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `language_fr` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `variation` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no',
  PRIMARY KEY (`language_id`),
  UNIQUE KEY `iso_639_2t_variation` (`iso_639_2t`,`variation`),
  KEY `website` (`website`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `languages` (`language_id`, `iso_639_2t`, `iso_639_2b`, `iso_639_1`, `language_de`, `language_en`, `language_fr`, `variation`, `website`) VALUES
(1,	'aar',	NULL,	'aa',	'Afar',	'Afar',	'afar',	NULL,	'no'),
(2,	'abk',	NULL,	'ab',	'Abchasisch',	'Abkhazian',	'abkhaze',	NULL,	'no'),
(3,	'ace',	NULL,	NULL,	'Aceh-Sprache',	'Achinese',	'aceh',	NULL,	'no'),
(4,	'ach',	NULL,	NULL,	'Acholi-Sprache',	'Acoli',	'acoli',	NULL,	'no'),
(5,	'ada',	NULL,	NULL,	'Adangme-Sprache',	'Adangme',	'adangme',	NULL,	'no'),
(6,	'ady',	NULL,	NULL,	'Adygisch',	'Adyghe; Adygei',	'adyghé',	NULL,	'no'),
(7,	'afa',	NULL,	NULL,	'Hamitosemitische Sprachen (Andere)',	'Afro-Asiatic (Other)',	'afro-asiatiques, autres langues',	NULL,	'no'),
(8,	'afh',	NULL,	NULL,	'Afrihili',	'Afrihili',	'afrihili',	NULL,	'no'),
(9,	'afr',	NULL,	'af',	'Afrikaans',	'Afrikaans',	'afrikaans',	NULL,	'no'),
(10,	'ain',	NULL,	NULL,	'Ainu-Sprache',	'Ainu',	'ainou',	NULL,	'no'),
(11,	'aka',	NULL,	'ak',	'Akan-Sprache',	'Akan',	'akan',	NULL,	'no'),
(12,	'akk',	NULL,	NULL,	'Akkadisch',	'Akkadian',	'akkadien',	NULL,	'no'),
(13,	'ale',	NULL,	NULL,	'Aleutisch',	'Aleut',	'aléoute',	NULL,	'no'),
(14,	'alg',	NULL,	NULL,	'Algonkin-Sprachen (Andere)',	'Algonquian languages',	'algonquines, langues',	NULL,	'no'),
(15,	'alt',	NULL,	NULL,	'Südaltaisch',	'Southern Altai',	'altai du Sud',	NULL,	'no'),
(16,	'amh',	NULL,	'am',	'Amharisch',	'Amharic',	'amharique',	NULL,	'no'),
(17,	'ang',	NULL,	NULL,	'Altenglisch',	'English, Old (ca.450-1100)',	'anglo-saxon (ca.450-1100)',	NULL,	'no'),
(18,	'anp',	NULL,	NULL,	'Anga-Sprache',	'Angika',	'angika',	NULL,	'no'),
(19,	'apa',	NULL,	NULL,	'Apachen-Sprache',	'Apache languages',	'apache',	NULL,	'no'),
(20,	'ara',	NULL,	'ar',	'Arabisch',	'Arabic',	'arabe',	NULL,	'no'),
(21,	'arc',	NULL,	NULL,	'Aramäisch',	'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)',	'araméen d\'empire (700-300 BCE)',	NULL,	'no'),
(22,	'arg',	NULL,	'an',	'Aragonesisch',	'Aragonese',	'aragonais',	NULL,	'no'),
(23,	'arn',	NULL,	NULL,	'Arauka-Sprachen',	'Mapudungun; Mapuche',	'mapudungun; mapuche; mapuce',	NULL,	'no'),
(24,	'arp',	NULL,	NULL,	'Arapaho-Sprache',	'Arapaho',	'arapaho',	NULL,	'no'),
(25,	'art',	NULL,	NULL,	'Kunstsprachen (Andere)',	'Artificial (Other)',	'artificielles, autres langues',	NULL,	'no'),
(26,	'arw',	NULL,	NULL,	'Arawak-Sprachen',	'Arawak',	'arawak',	NULL,	'no'),
(27,	'asm',	NULL,	'as',	'Assamesisch',	'Assamese',	'assamais',	NULL,	'no'),
(28,	'ast',	NULL,	NULL,	'Asturisch',	'Asturian; Bable; Leonese; Asturleonese',	'asturien; bable; léonais; asturoléonais',	NULL,	'no'),
(29,	'ath',	NULL,	NULL,	'Athapaskische Sprachen',	'Athapascan languages',	'athapascanes, langues',	NULL,	'no'),
(30,	'aus',	NULL,	NULL,	'Australische Sprachen',	'Australian languages',	'australiennes, langues',	NULL,	'no'),
(31,	'ava',	NULL,	'av',	'Awarisch',	'Avaric',	'avar',	NULL,	'no'),
(32,	'ave',	NULL,	'ae',	'Avestisch',	'Avestan',	'avestique',	NULL,	'no'),
(33,	'awa',	NULL,	NULL,	'Awadhi',	'Awadhi',	'awadhi',	NULL,	'no'),
(34,	'aym',	NULL,	'ay',	'Aymará-Sprache',	'Aymara',	'aymara',	NULL,	'no'),
(35,	'aze',	NULL,	'az',	'Aserbeidschanisch',	'Azerbaijani',	'azéri',	NULL,	'no'),
(36,	'bad',	NULL,	NULL,	'Banda-Sprache (Ubangi-Sprachen)',	'Banda languages',	'banda, langues',	NULL,	'no'),
(37,	'bai',	NULL,	NULL,	'Bamileke-Sprache',	'Bamileke languages',	'bamilékés, langues',	NULL,	'no'),
(38,	'bak',	NULL,	'ba',	'Baschkirisch',	'Bashkir',	'bachkir',	NULL,	'no'),
(39,	'bal',	NULL,	NULL,	'Belutschisch',	'Baluchi',	'baloutchi',	NULL,	'no'),
(40,	'bam',	NULL,	'bm',	'Bambara-Sprache',	'Bambara',	'bambara',	NULL,	'no'),
(41,	'ban',	NULL,	NULL,	'Balinesisch',	'Balinese',	'balinais',	NULL,	'no'),
(42,	'bas',	NULL,	NULL,	'Basaa-Sprache',	'Basa',	'basa',	NULL,	'no'),
(43,	'bat',	NULL,	NULL,	'Baltische Sprachen (Andere)',	'Baltic (Other)',	'baltiques, autres langues',	NULL,	'no'),
(44,	'bej',	NULL,	NULL,	'Bedauye',	'Beja; Bedawiyet',	'bedja',	NULL,	'no'),
(45,	'bel',	NULL,	'be',	'Weißrussisch',	'Belarusian',	'biélorusse',	NULL,	'yes'),
(46,	'bem',	NULL,	NULL,	'Bemba-Sprache',	'Bemba',	'bemba',	NULL,	'no'),
(47,	'ben',	NULL,	'bn',	'Bengali',	'Bengali',	'bengali',	NULL,	'no'),
(48,	'ber',	NULL,	NULL,	'Berbersprachen (Andere)',	'Berber (Other)',	'berberes, autres langues',	NULL,	'no'),
(49,	'bho',	NULL,	NULL,	'Bhojpuri',	'Bhojpuri',	'bhojpuri',	NULL,	'no'),
(50,	'bih',	NULL,	'bh',	'Bihari',	'Bihari',	'bihari',	NULL,	'no'),
(51,	'bik',	NULL,	NULL,	'Bikol-Sprache',	'Bikol',	'bikol',	NULL,	'no'),
(52,	'bin',	NULL,	NULL,	'Edo-Sprache',	'Bini; Edo',	'bini; edo',	NULL,	'no'),
(53,	'bis',	NULL,	'bi',	'Beach-la-mar',	'Bislama',	'bichlamar',	NULL,	'no'),
(54,	'bla',	NULL,	NULL,	'Blackfoot-Sprache',	'Siksika',	'blackfoot',	NULL,	'no'),
(55,	'bnt',	NULL,	NULL,	'Bantusprachen (Andere)',	'Bantu (Other)',	'bantoues, autres langues',	NULL,	'no'),
(56,	'bod',	'tib',	'bo',	'Tibetisch',	'Tibetan',	'tibétain',	NULL,	'no'),
(57,	'bos',	NULL,	'bs',	'Bosnisch',	'Bosnian',	'bosniaque',	NULL,	'no'),
(58,	'bra',	NULL,	NULL,	'Braj-Bhakha',	'Braj',	'braj',	NULL,	'no'),
(59,	'bre',	NULL,	'br',	'Bretonisch',	'Breton',	'breton',	NULL,	'no'),
(60,	'btk',	NULL,	NULL,	'Batak-Sprache',	'Batak languages',	'batak, langues',	NULL,	'no'),
(61,	'bua',	NULL,	NULL,	'Burjatisch',	'Buriat',	'bouriate',	NULL,	'no'),
(62,	'bug',	NULL,	NULL,	'Bugi-Sprache',	'Buginese',	'bugi',	NULL,	'no'),
(63,	'bul',	NULL,	'bg',	'Bulgarisch',	'Bulgarian',	'bulgare',	NULL,	'no'),
(64,	'byn',	NULL,	NULL,	'Bilin-Sprache',	'Blin; Bilin',	'blin; bilen',	NULL,	'no'),
(65,	'cad',	NULL,	NULL,	'Caddo-Sprachen',	'Caddo',	'caddo',	NULL,	'no'),
(66,	'cai',	NULL,	NULL,	'Indianersprachen, Zentralamerika (Andere)',	'Central American Indian (Other)',	'indiennes d\'Amérique centrale, autres langues',	NULL,	'no'),
(67,	'car',	NULL,	NULL,	'Karibische Sprachen',	'Galibi Carib',	'karib; galibi; carib',	NULL,	'no'),
(68,	'cat',	NULL,	'ca',	'Katalanisch',	'Catalan; Valencian',	'catalan; valencien',	NULL,	'no'),
(69,	'cau',	NULL,	NULL,	'Kaukasische Sprachen (Andere)',	'Caucasian (Other)',	'caucasiennes, autres langues',	NULL,	'no'),
(70,	'ceb',	NULL,	NULL,	'Cebuano',	'Cebuano',	'cebuano',	NULL,	'no'),
(71,	'cel',	NULL,	NULL,	'Keltische Sprachen (Andere)',	'Celtic (Other)',	'celtiques, autres langues',	NULL,	'no'),
(72,	'ces',	'cze',	'cs',	'Tschechisch',	'Czech',	'tcheque',	NULL,	'no'),
(73,	'cha',	NULL,	'ch',	'Chamorro-Sprache',	'Chamorro',	'chamorro',	NULL,	'no'),
(74,	'chb',	NULL,	NULL,	'Chibcha-Sprachen',	'Chibcha',	'chibcha',	NULL,	'no'),
(75,	'che',	NULL,	'ce',	'Tschetschenisch',	'Chechen',	'tchétchene',	NULL,	'no'),
(76,	'chg',	NULL,	NULL,	'Tschagataisch',	'Chagatai',	'djaghatai',	NULL,	'no'),
(77,	'chk',	NULL,	NULL,	'Trukesisch',	'Chuukese',	'chuuk',	NULL,	'no'),
(78,	'chm',	NULL,	NULL,	'Tscheremissisch',	'Mari',	'mari',	NULL,	'no'),
(79,	'chn',	NULL,	NULL,	'Chinook-Jargon',	'Chinook jargon',	'chinook, jargon',	NULL,	'no'),
(80,	'cho',	NULL,	NULL,	'Choctaw-Sprache',	'Choctaw',	'choctaw',	NULL,	'no'),
(81,	'chp',	NULL,	NULL,	'Chipewyan-Sprache',	'Chipewyan; Dene Suline',	'chipewyan',	NULL,	'no'),
(82,	'chr',	NULL,	NULL,	'Cherokee-Sprache',	'Cherokee',	'cherokee',	NULL,	'no'),
(83,	'chu',	NULL,	'cu',	'Kirchenslawisch',	'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',	'slavon d\'église; vieux slave; slavon liturgique; vieux bulgare',	NULL,	'no'),
(84,	'chv',	NULL,	'cv',	'Tschuwaschisch',	'Chuvash',	'tchouvache',	NULL,	'no'),
(85,	'chy',	NULL,	NULL,	'Cheyenne-Sprache',	'Cheyenne',	'cheyenne',	NULL,	'no'),
(86,	'cmc',	NULL,	NULL,	'Cham-Sprachen',	'Chamic languages',	'chames, langues',	NULL,	'no'),
(87,	'cop',	NULL,	NULL,	'Koptisch',	'Coptic',	'copte',	NULL,	'no'),
(88,	'cor',	NULL,	'kw',	'Kornisch',	'Cornish',	'cornique',	NULL,	'no'),
(89,	'cos',	NULL,	'co',	'Korsisch',	'Corsican',	'corse',	NULL,	'no'),
(90,	'cpe',	NULL,	NULL,	'Kreolisch-Englisch (Andere)',	'Creoles and pidgins, English based (Other)',	'créoles et pidgins anglais, autres',	NULL,	'no'),
(91,	'cpf',	NULL,	NULL,	'Kreolisch-Französisch (Andere)',	'Creoles and pidgins, French-based (Other)',	'créoles et pidgins français, autres',	NULL,	'no'),
(92,	'cpp',	NULL,	NULL,	'Kreolisch-Portugiesisch (Andere)',	'Creoles and pidgins, Portuguese-based (Other)',	'créoles et pidgins portugais, autres',	NULL,	'no'),
(93,	'cre',	NULL,	'cr',	'Cree-Sprache',	'Cree',	'cree',	NULL,	'no'),
(94,	'crh',	NULL,	NULL,	'Krimtatarisch',	'Crimean Tatar; Crimean Turkish',	'tatar de Crimé',	NULL,	'no'),
(95,	'crp',	NULL,	NULL,	'Kreolische Sprachen; Pidginsprachen (Andere)',	'Creoles and pidgins (Other)',	'créoles et pidgins divers',	NULL,	'no'),
(96,	'csb',	NULL,	NULL,	'Kaschubisch',	'Kashubian',	'kachoube',	NULL,	'no'),
(97,	'cus',	NULL,	NULL,	'Kuschitische Sprachen (Andere)',	'Cushitic (Other)',	'couchitiques, autres langues',	NULL,	'no'),
(98,	'cym',	'wel',	'cy',	'Kymrisch',	'Welsh',	'gallois',	NULL,	'no'),
(99,	'dak',	NULL,	NULL,	'Dakota-Sprache',	'Dakota',	'dakota',	NULL,	'no'),
(100,	'dan',	NULL,	'da',	'Danakil-Sprache',	'Danish',	'danois',	NULL,	'no'),
(101,	'dar',	NULL,	NULL,	'Darginisch',	'Dargwa',	'dargwa',	NULL,	'no'),
(102,	'day',	NULL,	NULL,	'Dajakisch',	'Land Dayak languages',	'dayak, langues',	NULL,	'no'),
(103,	'del',	NULL,	NULL,	'Delaware-Sprache',	'Delaware',	'delaware',	NULL,	'no'),
(104,	'den',	NULL,	NULL,	'Slave-Sprache',	'Slave (Athapascan)',	'esclave (athapascan)',	NULL,	'no'),
(105,	'deu',	'ger',	'de',	'Deutsch',	'German',	'allemand',	NULL,	'yes'),
(106,	'dgr',	NULL,	NULL,	'Dogrib-Sprache',	'Dogrib',	'dogrib',	NULL,	'no'),
(107,	'din',	NULL,	NULL,	'Dinka-Sprache',	'Dinka',	'dinka',	NULL,	'no'),
(108,	'div',	NULL,	'dv',	'Maledivisch',	'Divehi; Dhivehi; Maldivian',	'maldivien',	NULL,	'no'),
(109,	'doi',	NULL,	NULL,	'Dogri',	'Dogri',	'dogri',	NULL,	'no'),
(110,	'dra',	NULL,	NULL,	'Drawidische Sprachen (Andere)',	'Dravidian (Other)',	'dravidiennes, autres langues',	NULL,	'no'),
(111,	'dsb',	NULL,	NULL,	'Niedersorbisch',	'Lower Sorbian',	'bas-sorabe',	NULL,	'no'),
(112,	'dua',	NULL,	NULL,	'Duala-Sprachen',	'Duala',	'douala',	NULL,	'no'),
(113,	'dum',	NULL,	NULL,	'Mittelniederländisch',	'Dutch, Middle (ca.1050-1350)',	'néerlandais moyen (ca. 1050-1350)',	NULL,	'no'),
(114,	'dyu',	NULL,	NULL,	'Dyula-Sprache',	'Dyula',	'dioula',	NULL,	'no'),
(115,	'dzo',	NULL,	'dz',	'Dzongkha',	'Dzongkha',	'dzongkha',	NULL,	'no'),
(116,	'efi',	NULL,	NULL,	'Efik',	'Efik',	'efik',	NULL,	'no'),
(117,	'egy',	NULL,	NULL,	'Ägyptisch',	'Egyptian (Ancient)',	'égyptien',	NULL,	'no'),
(118,	'eka',	NULL,	NULL,	'Ekajuk',	'Ekajuk',	'ekajuk',	NULL,	'no'),
(119,	'ell',	'gre',	'el',	'Neugriechisch',	'Greek, Modern (1453-)',	'grec moderne (apres 1453)',	NULL,	'no'),
(120,	'elx',	NULL,	NULL,	'Elamisch',	'Elamite',	'élamite',	NULL,	'no'),
(121,	'eng',	NULL,	'en',	'Englisch',	'English',	'anglais',	NULL,	'yes'),
(122,	'enm',	NULL,	NULL,	'Mittelenglisch',	'English, Middle (1100-1500)',	'anglais moyen (1100-1500)',	NULL,	'no'),
(123,	'epo',	NULL,	'eo',	'Esperanto',	'Esperanto',	'espéranto',	NULL,	'no'),
(124,	'est',	NULL,	'et',	'Estnisch',	'Estonian',	'estonien',	NULL,	'no'),
(125,	'eus',	'baq',	'eu',	'Baskisch',	'Basque',	'basque',	NULL,	'no'),
(126,	'ewe',	NULL,	'ee',	'Ewe-Sprache',	'Ewe',	'éwé',	NULL,	'no'),
(127,	'ewo',	NULL,	NULL,	'Ewondo',	'Ewondo',	'éwondo',	NULL,	'no'),
(128,	'fan',	NULL,	NULL,	'Pangwe-Sprache',	'Fang',	'fang',	NULL,	'no'),
(129,	'fao',	NULL,	'fo',	'Färöisch',	'Faroese',	'féroien',	NULL,	'no'),
(130,	'fas',	'per',	'fa',	'Persisch',	'Persian',	'persan',	NULL,	'no'),
(131,	'fat',	NULL,	NULL,	'Fante-Sprache',	'Fanti',	'fanti',	NULL,	'no'),
(132,	'fij',	NULL,	'fj',	'Fidschi-Sprache',	'Fijian',	'fidjien',	NULL,	'no'),
(133,	'fil',	NULL,	NULL,	'Pilipino',	'Filipino; Pilipino',	'filipino; pilipino',	NULL,	'no'),
(134,	'fin',	NULL,	'fi',	'Finnisch',	'Finnish',	'finnois',	NULL,	'no'),
(135,	'fiu',	NULL,	NULL,	'Finnougrische Sprachen (Andere)',	'Finno-Ugrian (Other)',	'finno-ougriennes, autres langues',	NULL,	'no'),
(136,	'fon',	NULL,	NULL,	'Fon-Sprache',	'Fon',	'fon',	NULL,	'no'),
(137,	'fra',	'fre',	'fr',	'Französisch',	'French',	'français',	NULL,	'no'),
(138,	'frm',	NULL,	NULL,	'Mittelfranzösisch',	'French, Middle (ca.1400-1600)',	'français moyen (1400-1600)',	NULL,	'no'),
(139,	'fro',	NULL,	NULL,	'Altfranzösisch',	'French, Old (842-ca.1400)',	'français ancien (842-ca.1400)',	NULL,	'no'),
(140,	'frr',	NULL,	NULL,	'Nordfriesisch',	'Northern Frisian',	'frison septentrional',	NULL,	'no'),
(141,	'frs',	NULL,	NULL,	'Ostfriesisch',	'Eastern Frisian',	'frison oriental',	NULL,	'no'),
(142,	'fry',	NULL,	'fy',	'Friesisch',	'Western Frisian',	'frison occidental',	NULL,	'no'),
(143,	'ful',	NULL,	'ff',	'Ful',	'Fulah',	'peul',	NULL,	'no'),
(144,	'fur',	NULL,	NULL,	'Friulisch',	'Friulian',	'frioulan',	NULL,	'no'),
(145,	'gaa',	NULL,	NULL,	'Ga-Sprache',	'Ga',	'ga',	NULL,	'no'),
(146,	'gay',	NULL,	NULL,	'Gayo-Sprache',	'Gayo',	'gayo',	NULL,	'no'),
(147,	'gba',	NULL,	NULL,	'Gbaya-Sprache',	'Gbaya',	'gbaya',	NULL,	'no'),
(148,	'gem',	NULL,	NULL,	'Germanische Sprachen (Andere)',	'Germanic (Other)',	'germaniques, autres langues',	NULL,	'no'),
(149,	'gez',	NULL,	NULL,	'Altäthiopisch',	'Geez',	'gueze',	NULL,	'no'),
(150,	'gil',	NULL,	NULL,	'Gilbertesisch',	'Gilbertese',	'kiribati',	NULL,	'no'),
(151,	'gla',	NULL,	'gd',	'Gälisch-Schottisch',	'Gaelic; Scottish Gaelic',	'gaélique; gaélique écossais',	NULL,	'no'),
(152,	'gle',	NULL,	'ga',	'Irisch',	'Irish',	'irlandais',	NULL,	'no'),
(153,	'glg',	NULL,	'gl',	'Galicisch',	'Galician',	'galicien',	NULL,	'no'),
(154,	'glv',	NULL,	'gv',	'Manx',	'Manx',	'manx; mannois',	NULL,	'no'),
(155,	'gmh',	NULL,	NULL,	'Mittelhochdeutsch',	'German, Middle High (ca.1050-1500)',	'allemand, moyen haut (ca. 1050-1500)',	NULL,	'no'),
(156,	'goh',	NULL,	NULL,	'Althochdeutsch',	'German, Old High (ca.750-1050)',	'allemand, vieux haut (ca. 750-1050)',	NULL,	'no'),
(157,	'gon',	NULL,	NULL,	'Gondi-Sprache',	'Gondi',	'gond',	NULL,	'no'),
(158,	'gor',	NULL,	NULL,	'Gorontalesisch',	'Gorontalo',	'gorontalo',	NULL,	'no'),
(159,	'got',	NULL,	NULL,	'Gotisch',	'Gothic',	'gothique',	NULL,	'no'),
(160,	'grb',	NULL,	NULL,	'Grebo-Sprache',	'Grebo',	'grebo',	NULL,	'no'),
(161,	'grc',	NULL,	NULL,	'Griechisch',	'Greek, Ancient (to 1453)',	'grec ancien (jusqu\'a 1453)',	NULL,	'no'),
(162,	'grn',	NULL,	'gn',	'Guaraní-Sprache',	'Guarani',	'guarani',	NULL,	'no'),
(163,	'gsw',	NULL,	NULL,	'Schweizerdeutsch',	'Swiss German; Alemannic; Alsatian',	'suisse alémanique; alémanique; alsacien',	NULL,	'no'),
(164,	'guj',	NULL,	'gu',	'Gujarati-Sprache',	'Gujarati',	'goudjrati',	NULL,	'no'),
(165,	'gwi',	NULL,	NULL,	'Kutchin-Sprache',	'Gwich\'in',	'gwich\'in',	NULL,	'no'),
(166,	'hai',	NULL,	NULL,	'Haida-Sprache',	'Haida',	'haida',	NULL,	'no'),
(167,	'hat',	NULL,	'ht',	'Haitien',	'Haitian; Haitian Creole',	'haitien; créole haitien',	NULL,	'no'),
(168,	'hau',	NULL,	'ha',	'Haussa-Sprache',	'Hausa',	'haoussa',	NULL,	'no'),
(169,	'haw',	NULL,	NULL,	'Hawaiisch',	'Hawaiian',	'hawaien',	NULL,	'no'),
(170,	'heb',	NULL,	'he',	'Hebräisch',	'Hebrew',	'hébreu',	NULL,	'no'),
(171,	'her',	NULL,	'hz',	'Herero-Sprache',	'Herero',	'herero',	NULL,	'no'),
(172,	'hil',	NULL,	NULL,	'Hiligaynon-Sprache',	'Hiligaynon',	'hiligaynon',	NULL,	'no'),
(173,	'him',	NULL,	NULL,	'Himachali',	'Himachali',	'himachali',	NULL,	'no'),
(174,	'hin',	NULL,	'hi',	'Hindi',	'Hindi',	'hindi',	NULL,	'no'),
(175,	'hit',	NULL,	NULL,	'Hethitisch',	'Hittite',	'hittite',	NULL,	'no'),
(176,	'hmn',	NULL,	NULL,	'Miao-Sprachen',	'Hmong',	'hmong',	NULL,	'no'),
(177,	'hmo',	NULL,	'ho',	'Hiri-Motu',	'Hiri Motu',	'hiri motu',	NULL,	'no'),
(178,	'hrv',	'scr',	'hr',	'Kroatisch',	'Croatian',	'croate',	NULL,	'no'),
(179,	'hsb',	NULL,	NULL,	'Obersorbisch',	'Upper Sorbian',	'haut-sorabe',	NULL,	'no'),
(180,	'hun',	NULL,	'hu',	'Ungarisch',	'Hungarian',	'hongrois',	NULL,	'no'),
(181,	'hup',	NULL,	NULL,	'Hupa-Sprache',	'Hupa',	'hupa',	NULL,	'no'),
(182,	'hye',	'arm',	'hy',	'Armenisch',	'Armenian',	'arménien',	NULL,	'no'),
(183,	'iba',	NULL,	NULL,	'Iban-Sprache',	'Iban',	'iban',	NULL,	'no'),
(184,	'ibo',	NULL,	'ig',	'Ibo-Sprache',	'Igbo',	'igbo',	NULL,	'no'),
(185,	'ido',	NULL,	'io',	'Ido',	'Ido',	'ido',	NULL,	'no'),
(186,	'iii',	NULL,	'ii',	'Lalo-Sprache',	'Sichuan Yi; Nuosu',	'yi de Sichuan',	NULL,	'no'),
(187,	'ijo',	NULL,	NULL,	'Ijo-Sprache',	'Ijo languages',	'ijo, langues',	NULL,	'no'),
(188,	'iku',	NULL,	'iu',	'Inuktitut',	'Inuktitut',	'inuktitut',	NULL,	'no'),
(189,	'ile',	NULL,	'ie',	'Interlingue',	'Interlingue; Occidental',	'interlingue',	NULL,	'no'),
(190,	'ilo',	NULL,	NULL,	'Ilokano-Sprache',	'Iloko',	'ilocano',	NULL,	'no'),
(191,	'ina',	NULL,	'ia',	'Interlingua',	'Interlingua (International Auxiliary Language Association)',	'interlingua (langue auxiliaire internationale)',	NULL,	'no'),
(192,	'inc',	NULL,	NULL,	'Indoarische Sprachen (Andere)',	'Indic (Other)',	'indo-aryennes, autres langues',	NULL,	'no'),
(193,	'ind',	NULL,	'id',	'Bahasa Indonesia',	'Indonesian',	'indonésien',	NULL,	'no'),
(194,	'ine',	NULL,	NULL,	'Indogermanische Sprachen (Andere)',	'Indo-European (Other)',	'indo-européennes, autres langues',	NULL,	'no'),
(195,	'inh',	NULL,	NULL,	'Inguschisch',	'Ingush',	'ingouche',	NULL,	'no'),
(196,	'ipk',	NULL,	'ik',	'Inupik',	'Inupiaq',	'inupiaq',	NULL,	'no'),
(197,	'ira',	NULL,	NULL,	'Iranische Sprachen (Andere)',	'Iranian (Other)',	'iraniennes, autres langues',	NULL,	'no'),
(198,	'iro',	NULL,	NULL,	'Irokesische Sprachen',	'Iroquoian languages',	'iroquoises, langues (famille)',	NULL,	'no'),
(199,	'isl',	'ice',	'is',	'Isländisch',	'Icelandic',	'islandais',	NULL,	'no'),
(200,	'ita',	NULL,	'it',	'Italienisch',	'Italian',	'italien',	NULL,	'no'),
(201,	'jav',	NULL,	'jv',	'Javanisch',	'Javanese',	'javanais',	NULL,	'no'),
(202,	'jbo',	NULL,	NULL,	'Lojban',	'Lojban',	'lojban',	NULL,	'no'),
(203,	'jpn',	NULL,	'ja',	'Japanisch',	'Japanese',	'japonais',	NULL,	'no'),
(204,	'jpr',	NULL,	NULL,	'Jüdisch-Persisch',	'Judeo-Persian',	'judéo-persan',	NULL,	'no'),
(205,	'jrb',	NULL,	NULL,	'Jüdisch-Arabisch',	'Judeo-Arabic',	'judéo-arabe',	NULL,	'no'),
(206,	'kaa',	NULL,	NULL,	'Karakalpakisch',	'Kara-Kalpak',	'karakalpak',	NULL,	'no'),
(207,	'kab',	NULL,	NULL,	'Kabylisch',	'Kabyle',	'kabyle',	NULL,	'no'),
(208,	'kac',	NULL,	NULL,	'Kachin-Sprache',	'Kachin; Jingpho',	'kachin; jingpho',	NULL,	'no'),
(209,	'kal',	NULL,	'kl',	'Grönländisch',	'Kalaallisut; Greenlandic',	'groenlandais',	NULL,	'no'),
(210,	'kam',	NULL,	NULL,	'Kamba-Sprache',	'Kamba',	'kamba',	NULL,	'no'),
(211,	'kan',	NULL,	'kn',	'Kannada',	'Kannada',	'kannada',	NULL,	'no'),
(212,	'kar',	NULL,	NULL,	'Karenisch',	'Karen languages',	'karen, langues',	NULL,	'no'),
(213,	'kas',	NULL,	'ks',	'Kaschmiri',	'Kashmiri',	'kashmiri',	NULL,	'no'),
(214,	'kat',	'geo',	'ka',	'Georgisch',	'Georgian',	'géorgien',	NULL,	'no'),
(215,	'kau',	NULL,	'kr',	'Kanuri-Sprache',	'Kanuri',	'kanouri',	NULL,	'no'),
(216,	'kaw',	NULL,	NULL,	'Kawi',	'Kawi',	'kawi',	NULL,	'no'),
(217,	'kaz',	NULL,	'kk',	'Kasachisch',	'Kazakh',	'kazakh',	NULL,	'no'),
(218,	'kbd',	NULL,	NULL,	'Kabardinisch',	'Kabardian',	'kabardien',	NULL,	'no'),
(219,	'kha',	NULL,	NULL,	'Khasi-Sprache',	'Khasi',	'khasi',	NULL,	'no'),
(220,	'khi',	NULL,	NULL,	'Khoisan-Sprachen (Andere)',	'Khoisan (Other)',	'khoisan, autres langues',	NULL,	'no'),
(221,	'khm',	NULL,	'km',	'Kambodschanisch',	'Central Khmer',	'khmer central',	NULL,	'no'),
(222,	'kho',	NULL,	NULL,	'Sakisch',	'Khotanese',	'khotanais',	NULL,	'no'),
(223,	'kik',	NULL,	'ki',	'Kikuyu-Sprache',	'Kikuyu; Gikuyu',	'kikuyu',	NULL,	'no'),
(224,	'kin',	NULL,	'rw',	'Rwanda-Sprache',	'Kinyarwanda',	'rwanda',	NULL,	'no'),
(225,	'kir',	NULL,	'ky',	'Kirgisisch',	'Kirghiz; Kyrgyz',	'kirghiz',	NULL,	'no'),
(226,	'kmb',	NULL,	NULL,	'Kimbundu-Sprache',	'Kimbundu',	'kimbundu',	NULL,	'no'),
(227,	'kok',	NULL,	NULL,	'Konkani',	'Konkani',	'konkani',	NULL,	'no'),
(228,	'kom',	NULL,	'kv',	'Komi-Sprache',	'Komi',	'kom',	NULL,	'no'),
(229,	'kon',	NULL,	'kg',	'Kongo-Sprache',	'Kongo',	'kongo',	NULL,	'no'),
(230,	'kor',	NULL,	'ko',	'Koreanisch',	'Korean',	'coréen',	NULL,	'no'),
(231,	'kos',	NULL,	NULL,	'Kosreanisch',	'Kosraean',	'kosrae',	NULL,	'no'),
(232,	'kpe',	NULL,	NULL,	'Kpelle-Sprache',	'Kpelle',	'kpellé',	NULL,	'no'),
(233,	'krc',	NULL,	NULL,	'Karatschaiisch-Balkarisch',	'Karachay-Balkar',	'karatchai balkar',	NULL,	'no'),
(234,	'krl',	NULL,	NULL,	'Karelisch',	'Karelian',	'carélien',	NULL,	'no'),
(235,	'kro',	NULL,	NULL,	'Kru-Sprachen',	'Kru languages',	'krou, langues',	NULL,	'no'),
(236,	'kru',	NULL,	NULL,	'Oraon-Sprache',	'Kurukh',	'kurukh',	NULL,	'no'),
(237,	'kua',	NULL,	'kj',	'Kwanyama-Sprache',	'Kuanyama; Kwanyama',	'kuanyama; kwanyama',	NULL,	'no'),
(238,	'kum',	NULL,	NULL,	'Kumükisch',	'Kumyk',	'koumyk',	NULL,	'no'),
(239,	'kur',	NULL,	'ku',	'Kurdisch',	'Kurdish',	'kurde',	NULL,	'no'),
(240,	'kut',	NULL,	NULL,	'Kutenai-Sprache',	'Kutenai',	'kutenai',	NULL,	'no'),
(241,	'lad',	NULL,	NULL,	'Judenspanisch',	'Ladino',	'judéo-espagnol',	NULL,	'no'),
(242,	'lah',	NULL,	NULL,	'Lahnda',	'Lahnda',	'lahnda',	NULL,	'no'),
(243,	'lam',	NULL,	NULL,	'Lamba-Sprache (Bantusprache)',	'Lamba',	'lamba',	NULL,	'no'),
(244,	'lao',	NULL,	'lo',	'Laotisch',	'Lao',	'lao',	NULL,	'no'),
(245,	'lat',	NULL,	'la',	'Latein',	'Latin',	'latin',	NULL,	'no'),
(246,	'lav',	NULL,	'lv',	'Lettisch',	'Latvian',	'letton',	NULL,	'no'),
(247,	'lez',	NULL,	NULL,	'Lesgisch',	'Lezghian',	'lezghien',	NULL,	'no'),
(248,	'lim',	NULL,	'li',	'Limburgisch',	'Limburgan; Limburger; Limburgish',	'limbourgeois',	NULL,	'no'),
(249,	'lin',	NULL,	'ln',	'Lingala',	'Lingala',	'lingala',	NULL,	'no'),
(250,	'lit',	NULL,	'lt',	'Litauisch',	'Lithuanian',	'lituanien',	NULL,	'no'),
(251,	'lol',	NULL,	NULL,	'Mongo-Sprache',	'Mongo',	'mongo',	NULL,	'no'),
(252,	'loz',	NULL,	NULL,	'Rotse-Sprache',	'Lozi',	'lozi',	NULL,	'no'),
(253,	'ltz',	NULL,	'lb',	'Luxemburgisch',	'Luxembourgish; Letzeburgesch',	'luxembourgeois',	NULL,	'no'),
(254,	'lua',	NULL,	NULL,	'Lulua-Sprache',	'Luba-Lulua',	'luba-lulua',	NULL,	'no'),
(255,	'lub',	NULL,	'lu',	'Luba-Katanga-Sprache',	'Luba-Katanga',	'luba-katanga',	NULL,	'no'),
(256,	'lug',	NULL,	'lg',	'Ganda-Sprache',	'Ganda',	'ganda',	NULL,	'no'),
(257,	'lui',	NULL,	NULL,	'Luiseno-Sprache',	'Luiseno',	'luiseno',	NULL,	'no'),
(258,	'lun',	NULL,	NULL,	'Lunda-Sprache',	'Lunda',	'lunda',	NULL,	'no'),
(259,	'luo',	NULL,	NULL,	'Luo-Sprache',	'Luo (Kenya and Tanzania)',	'luo (Kenya et Tanzanie)',	NULL,	'no'),
(260,	'lus',	NULL,	NULL,	'Lushai-Sprache',	'Lushai',	'lushai',	NULL,	'no'),
(261,	'mad',	NULL,	NULL,	'Maduresisch',	'Madurese',	'madourais',	NULL,	'no'),
(262,	'mag',	NULL,	NULL,	'Khotta',	'Magahi',	'magahi',	NULL,	'no'),
(263,	'mah',	NULL,	'mh',	'Marschallesisch',	'Marshallese',	'marshall',	NULL,	'no'),
(264,	'mai',	NULL,	NULL,	'Maithili',	'Maithili',	'maithili',	NULL,	'no'),
(265,	'mak',	NULL,	NULL,	'Makassarisch',	'Makasar',	'makassar',	NULL,	'no'),
(266,	'mal',	NULL,	'ml',	'Malayalam',	'Malayalam',	'malayalam',	NULL,	'no'),
(267,	'man',	NULL,	NULL,	'Malinke-Sprache',	'Mandingo',	'mandingue',	NULL,	'no'),
(268,	'map',	NULL,	NULL,	'Austronesische Sprachen (Andere)',	'Austronesian (Other)',	'malayo-polynésiennes, autres langues',	NULL,	'no'),
(269,	'mar',	NULL,	'mr',	'Marathi',	'Marathi',	'marathe',	NULL,	'no'),
(270,	'mas',	NULL,	NULL,	'Massai-Sprache',	'Masai',	'massai',	NULL,	'no'),
(271,	'mdf',	NULL,	NULL,	'Mokscha-Sprache',	'Moksha',	'moksa',	NULL,	'no'),
(272,	'mdr',	NULL,	NULL,	'Mandaresisch',	'Mandar',	'mandar',	NULL,	'no'),
(273,	'men',	NULL,	NULL,	'Mende-Sprache',	'Mende',	'mendé',	NULL,	'no'),
(274,	'mga',	NULL,	NULL,	'Mittelirisch',	'Irish, Middle (900-1200)',	'irlandais moyen (900-1200)',	NULL,	'no'),
(275,	'mic',	NULL,	NULL,	'Micmac-Sprache',	'Mi\'kmaq; Micmac',	'mi\'kmaq; micmac',	NULL,	'no'),
(276,	'min',	NULL,	NULL,	'Minangkabau-Sprache',	'Minangkabau',	'minangkabau',	NULL,	'no'),
(277,	'mis',	NULL,	NULL,	'Einzelne andere Sprachen',	'Uncoded languages',	'langues non codées',	NULL,	'no'),
(278,	'mkd',	'mac',	'mk',	'Makedonisch',	'Macedonian',	'macédonien',	NULL,	'no'),
(279,	'mkh',	NULL,	NULL,	'Mon-Khmer-Sprachen (Andere)',	'Mon-Khmer (Other)',	'môn-khmer, autres langues',	NULL,	'no'),
(280,	'mlg',	NULL,	'mg',	'Malagassi-Sprache',	'Malagasy',	'malgache',	NULL,	'no'),
(281,	'mlt',	NULL,	'mt',	'Maltesisch',	'Maltese',	'maltais',	NULL,	'no'),
(282,	'mnc',	NULL,	NULL,	'Mandschurisch',	'Manchu',	'mandchou',	NULL,	'no'),
(283,	'mni',	NULL,	NULL,	'Meithei-Sprache',	'Manipuri',	'manipuri',	NULL,	'no'),
(284,	'mno',	NULL,	NULL,	'Manobo-Sprache',	'Manobo languages',	'manobo, langues',	NULL,	'no'),
(285,	'moh',	NULL,	NULL,	'Mohawk-Sprache',	'Mohawk',	'mohawk',	NULL,	'no'),
(286,	'mol',	NULL,	'mo',	'Moldauisch',	'Moldavian',	'moldave',	NULL,	'no'),
(287,	'mon',	NULL,	'mn',	'Mongolisch',	'Mongolian',	'mongol',	NULL,	'no'),
(288,	'mos',	NULL,	NULL,	'Mossi-Sprache',	'Mossi',	'moré',	NULL,	'no'),
(289,	'mri',	'mao',	'mi',	'Maori-Sprache',	'Maori',	'maori',	NULL,	'no'),
(290,	'msa',	'may',	'ms',	'Malaiisch',	'Malay',	'malais',	NULL,	'no'),
(291,	'mul',	NULL,	NULL,	'Mehrere Sprachen',	'Multiple languages',	'multilingue',	NULL,	'no'),
(292,	'mun',	NULL,	NULL,	'Mundasprachen (Andere)',	'Munda languages',	'mounda, langues',	NULL,	'no'),
(293,	'mus',	NULL,	NULL,	'Muskogisch',	'Creek',	'muskogee',	NULL,	'no'),
(294,	'mwl',	NULL,	NULL,	'Mirandesisch',	'Mirandese',	'mirandais',	NULL,	'no'),
(295,	'mwr',	NULL,	NULL,	'Marwari',	'Marwari',	'marvari',	NULL,	'no'),
(296,	'mya',	'bur',	'my',	'Birmanisch',	'Burmese',	'birman',	NULL,	'no'),
(297,	'myn',	NULL,	NULL,	'Maya-Sprachen',	'Mayan languages',	'maya, langues',	NULL,	'no'),
(298,	'myv',	NULL,	NULL,	'Erza-Mordwinisch',	'Erzya',	'erza',	NULL,	'no'),
(299,	'nah',	NULL,	NULL,	'Nahuatl',	'Nahuatl languages',	'nahuatl, langues',	NULL,	'no'),
(300,	'nai',	NULL,	NULL,	'Indianersprachen, Nordamerika (Andere)',	'North American Indian',	'indiennes d\'Amérique du Nord, autres langues',	NULL,	'no'),
(301,	'nap',	NULL,	NULL,	'Neapel / Mundart',	'Neapolitan',	'napolitain',	NULL,	'no'),
(302,	'nau',	NULL,	'na',	'Nauruanisch',	'Nauru',	'nauruan',	NULL,	'no'),
(303,	'nav',	NULL,	'nv',	'Navajo-Sprache',	'Navajo; Navaho',	'navaho',	NULL,	'no'),
(304,	'nbl',	NULL,	'nr',	'Ndebele-Sprache (Transvaal)',	'Ndebele, South; South Ndebele',	'ndébélé du Sud',	NULL,	'no'),
(305,	'nde',	NULL,	'nd',	'Ndebele-Sprache (Simbabwe)',	'Ndebele, North; North Ndebele',	'ndébélé du Nord',	NULL,	'no'),
(306,	'ndo',	NULL,	'ng',	'Ndonga',	'Ndonga',	'ndonga',	NULL,	'no'),
(307,	'nds',	NULL,	NULL,	'Niederdeutsch',	'Low German; Low Saxon; German, Low; Saxon, Low',	'bas allemand; bas saxon; allemand, bas; saxon, bas',	NULL,	'no'),
(308,	'nep',	NULL,	'ne',	'Nepali',	'Nepali',	'népalais',	NULL,	'no'),
(309,	'new',	NULL,	NULL,	'Newari',	'Nepal Bhasa; Newari',	'nepal bhasa; newari',	NULL,	'no'),
(310,	'nia',	NULL,	NULL,	'Nias-Sprache',	'Nias',	'nias',	NULL,	'no'),
(311,	'nic',	NULL,	NULL,	'Nigerkordofanische Sprachen (Andere)',	'Niger-Kordofanian (Other)',	'nigéro-congolaises, autres langues',	NULL,	'no'),
(312,	'niu',	NULL,	NULL,	'Niue-Sprache',	'Niuean',	'niué',	NULL,	'no'),
(313,	'nld',	'dut',	'nl',	'Niederländisch',	'Dutch; Flemish',	'néerlandais; flamand',	NULL,	'no'),
(314,	'nno',	NULL,	'nn',	'Nynorsk',	'Norwegian Nynorsk; Nynorsk, Norwegian',	'norvégien nynorsk; nynorsk, norvégien',	NULL,	'no'),
(315,	'nob',	NULL,	'nb',	'Bokmal',	'Bokmal, Norwegian; Norwegian Bokmal',	'norvégien bokmal',	NULL,	'no'),
(316,	'nog',	NULL,	NULL,	'Nogaisch',	'Nogai',	'nogai; nogay',	NULL,	'no'),
(317,	'non',	NULL,	NULL,	'Altnorwegisch',	'Norse, Old',	'norrois, vieux',	NULL,	'no'),
(318,	'nor',	NULL,	'no',	'Norwegisch',	'Norwegian',	'norvégien',	NULL,	'no'),
(319,	'nqo',	NULL,	NULL,	'N\'ko',	'N\'Ko',	'n\'ko',	NULL,	'no'),
(320,	'nso',	NULL,	NULL,	'Pedi-Sprache',	'Pedi; Sepedi; Northern Sotho',	'pedi; sepedi; sotho du Nord',	NULL,	'no'),
(321,	'nub',	NULL,	NULL,	'Nubische Sprachen',	'Nubian languages',	'nubiennes, langues',	NULL,	'no'),
(322,	'nwc',	NULL,	NULL,	'Alt-Newari',	'Classical Newari; Old Newari; Classical Nepal Bhasa',	'newari classique',	NULL,	'no'),
(323,	'nya',	NULL,	'ny',	'Nyanja-Sprache',	'Chichewa; Chewa; Nyanja',	'chichewa; chewa; nyanja',	NULL,	'no'),
(324,	'nym',	NULL,	NULL,	'Nyamwezi-Sprache',	'Nyamwezi',	'nyamwezi',	NULL,	'no'),
(325,	'nyn',	NULL,	NULL,	'Nkole-Sprache',	'Nyankole',	'nyankolé',	NULL,	'no'),
(326,	'nyo',	NULL,	NULL,	'Nyoro-Sprache',	'Nyoro',	'nyoro',	NULL,	'no'),
(327,	'nzi',	NULL,	NULL,	'Nzima-Sprache',	'Nzima',	'nzema',	NULL,	'no'),
(328,	'oci',	NULL,	'oc',	'Okzitanisch',	'Occitan (post 1500); Provençal',	'occitan (apres 1500); provençal',	NULL,	'no'),
(329,	'oji',	NULL,	'oj',	'Ojibwa-Sprache',	'Ojibwa',	'ojibwa',	NULL,	'no'),
(330,	'ori',	NULL,	'or',	'Oriya-Sprache',	'Oriya',	'oriya',	NULL,	'no'),
(331,	'orm',	NULL,	'om',	'Galla-Sprache',	'Oromo',	'galla',	NULL,	'no'),
(332,	'osa',	NULL,	NULL,	'Osage-Sprache',	'Osage',	'osage',	NULL,	'no'),
(333,	'oss',	NULL,	'os',	'Ossetisch',	'Ossetian; Ossetic',	'ossete',	NULL,	'no'),
(334,	'ota',	NULL,	NULL,	'Osmanisch',	'Turkish, Ottoman (1500-1928)',	'turc ottoman (1500-1928)',	NULL,	'no'),
(335,	'oto',	NULL,	NULL,	'Otomangue-Sprachen',	'Otomian languages',	'otomangue, langues',	NULL,	'no'),
(336,	'paa',	NULL,	NULL,	'Papuasprachen (Andere)',	'Papuan (Other)',	'papoues, autres langues',	NULL,	'no'),
(337,	'pag',	NULL,	NULL,	'Pangasinan-Sprache',	'Pangasinan',	'pangasinan',	NULL,	'no'),
(338,	'pal',	NULL,	NULL,	'Mittelpersisch',	'Pahlavi',	'pahlavi',	NULL,	'no'),
(339,	'pam',	NULL,	NULL,	'Pampanggan-Sprache',	'Pampanga; Kapampangan',	'pampangan',	NULL,	'no'),
(340,	'pan',	NULL,	'pa',	'Pandschabi-Sprache',	'Panjabi; Punjabi',	'pendjabi',	NULL,	'no'),
(341,	'pap',	NULL,	NULL,	'Papiamento',	'Papiamento',	'papiamento',	NULL,	'no'),
(342,	'pau',	NULL,	NULL,	'Palau-Sprache',	'Palauan',	'palau',	NULL,	'no'),
(343,	'peo',	NULL,	NULL,	'Altpersisch',	'Persian, Old (ca.600-400 B.C.)',	'perse, vieux (ca. 600-400 av. J.-C.)',	NULL,	'no'),
(344,	'phi',	NULL,	NULL,	'Philippinen-Austronesisch (Other)',	'Philippine (Other)',	'philippines, autres langues',	NULL,	'no'),
(345,	'phn',	NULL,	NULL,	'Phönikisch',	'Phoenician',	'phénicien',	NULL,	'no'),
(346,	'pli',	NULL,	'pi',	'Pali',	'Pali',	'pali',	NULL,	'no'),
(347,	'pol',	NULL,	'pl',	'Polnisch',	'Polish',	'polonais',	NULL,	'yes'),
(348,	'pon',	NULL,	NULL,	'Ponapeanisch',	'Pohnpeian',	'pohnpei',	NULL,	'no'),
(349,	'por',	NULL,	'pt',	'Portugiesisch',	'Portuguese',	'portugais',	NULL,	'no'),
(350,	'pra',	NULL,	NULL,	'Prakrit',	'Prakrit languages',	'prâkrit',	NULL,	'no'),
(351,	'pro',	NULL,	NULL,	'Altokzitanisch',	'Provençal, Old (to 1500)',	'provençal ancien (jusqu\'a 1500)',	NULL,	'no'),
(352,	'pus',	NULL,	'ps',	'Paschtu',	'Pushto; Pashto',	'pachto',	NULL,	'no'),
(353,	'que',	NULL,	'qu',	'Quechua-Sprache',	'Quechua',	'quechua',	NULL,	'no'),
(354,	'raj',	NULL,	NULL,	'Rajasthani',	'Rajasthani',	'rajasthani',	NULL,	'no'),
(355,	'rap',	NULL,	NULL,	'Osterinsel-Sprache',	'Rapanui',	'rapanui',	NULL,	'no'),
(356,	'rar',	NULL,	NULL,	'Rarotonganisch',	'Rarotongan; Cook Islands Maori',	'rarotonga; maori des îles Cook',	NULL,	'no'),
(357,	'roa',	NULL,	NULL,	'Romanes (andere)',	'Romance (Other)',	'romanes, autres langues',	NULL,	'no'),
(358,	'roh',	NULL,	'rm',	'Romanische Sprachen (Andere)',	'Romansh',	'romanche',	NULL,	'no'),
(359,	'rom',	NULL,	NULL,	'Romani (Sprache)',	'Romany',	'tsigane',	NULL,	'no'),
(360,	'ron',	'rum',	'ro',	'Rumänisch',	'Romanian',	'roumain',	NULL,	'no'),
(361,	'run',	NULL,	'rn',	'Rundi-Sprache',	'Rundi',	'rundi',	NULL,	'no'),
(362,	'rup',	NULL,	NULL,	'Aromunisch',	'Aromanian; Arumanian; Macedo-Romanian',	'aroumain; macédo-roumain',	NULL,	'no'),
(363,	'rus',	NULL,	'ru',	'Russisch',	'Russian',	'russe',	NULL,	'no'),
(364,	'sad',	NULL,	NULL,	'Sandawe-Sprache',	'Sandawe',	'sandawe',	NULL,	'no'),
(365,	'sag',	NULL,	'sg',	'Sango-Sprache',	'Sango',	'sango',	NULL,	'no'),
(366,	'sah',	NULL,	NULL,	'Jakutisch',	'Yakut',	'iakoute',	NULL,	'no'),
(367,	'sai',	NULL,	NULL,	'Indianersprachen, Südamerika (Andere)',	'South American Indian (Other)',	'indiennes d\'Amérique du Sud, autres langues',	NULL,	'no'),
(368,	'sal',	NULL,	NULL,	'Salish-Sprache',	'Salishan languages',	'salish, langues',	NULL,	'no'),
(369,	'sam',	NULL,	NULL,	'Samaritanisch',	'Samaritan Aramaic',	'samaritain',	NULL,	'no'),
(370,	'san',	NULL,	'sa',	'Sanskrit',	'Sanskrit',	'sanskrit',	NULL,	'no'),
(371,	'sas',	NULL,	NULL,	'Sasak',	'Sasak',	'sasak',	NULL,	'no'),
(372,	'sat',	NULL,	NULL,	'Santali',	'Santali',	'santal',	NULL,	'no'),
(373,	'scn',	NULL,	NULL,	'Sizilianisch',	'Sicilian',	'sicilien',	NULL,	'no'),
(374,	'sco',	NULL,	NULL,	'Schottisch',	'Scots',	'écossais',	NULL,	'no'),
(375,	'sel',	NULL,	NULL,	'Selkupisch',	'Selkup',	'selkoupe',	NULL,	'no'),
(376,	'sem',	NULL,	NULL,	'Semitische Sprachen (Andere)',	'Semitic (Other)',	'sémitiques, autres langues',	NULL,	'no'),
(377,	'sga',	NULL,	NULL,	'Altirisch',	'Irish, Old (to 900)',	'irlandais ancien (jusqu\'a 900)',	NULL,	'no'),
(378,	'sgn',	NULL,	NULL,	'Zeichensprachen',	'Sign Languages',	'langues des signes',	NULL,	'no'),
(379,	'shn',	NULL,	NULL,	'Schan-Sprache',	'Shan',	'chan',	NULL,	'no'),
(380,	'sid',	NULL,	NULL,	'Sidamo-Sprache',	'Sidamo',	'sidamo',	NULL,	'no'),
(381,	'sin',	NULL,	'si',	'Singhalesisch',	'Sinhala; Sinhalese',	'singhalais',	NULL,	'no'),
(382,	'sio',	NULL,	NULL,	'Sioux-Sprachen',	'Siouan languages',	'sioux, langues',	NULL,	'no'),
(383,	'sit',	NULL,	NULL,	'Sinotibetische Sprachen (Andere)',	'Sino-Tibetan (Other)',	'sino-tibétaines, autres langues',	NULL,	'no'),
(384,	'sla',	NULL,	NULL,	'Slawische Sprachen (Andere)',	'Slavic (Other)',	'slaves, autres langues',	NULL,	'no'),
(385,	'slk',	'slo',	'sk',	'Slowakisch',	'Slovak',	'slovaque',	NULL,	'no'),
(386,	'slv',	NULL,	'sl',	'Slowenisch',	'Slovenian',	'slovene',	NULL,	'no'),
(387,	'sma',	NULL,	NULL,	'Südsaamisch',	'Southern Sami',	'sami du Sud',	NULL,	'no'),
(388,	'sme',	NULL,	'se',	'Nordsaamisch',	'Northern Sami',	'sami du Nord',	NULL,	'no'),
(389,	'smi',	NULL,	NULL,	'Saamisch (Andere)',	'Sami languages (Other)',	'sami, autres langues',	NULL,	'no'),
(390,	'smj',	NULL,	NULL,	'Lulesaamisch',	'Lule Sami',	'sami de Lule',	NULL,	'no'),
(391,	'smn',	NULL,	NULL,	'Inarisaamisch',	'Inari Sami',	'sami d\'Inari',	NULL,	'no'),
(392,	'smo',	NULL,	'sm',	'Samoanisch',	'Samoan',	'samoan',	NULL,	'no'),
(393,	'sms',	NULL,	NULL,	'Skoltsaamisch',	'Skolt Sami',	'sami skolt',	NULL,	'no'),
(394,	'sna',	NULL,	'sn',	'Schona-Sprache',	'Shona',	'shona',	NULL,	'no'),
(395,	'snd',	NULL,	'sd',	'Sindhi-Sprache',	'Sindhi',	'sindhi',	NULL,	'no'),
(396,	'snk',	NULL,	NULL,	'Soninke-Sprache',	'Soninke',	'soninké',	NULL,	'no'),
(397,	'sog',	NULL,	NULL,	'Sogdisch',	'Sogdian',	'sogdien',	NULL,	'no'),
(398,	'som',	NULL,	'so',	'Somali',	'Somali',	'somali',	NULL,	'no'),
(399,	'son',	NULL,	NULL,	'Songhai-Sprache',	'Songhai languages',	'songhai, langues',	NULL,	'no'),
(400,	'sot',	NULL,	'st',	'Süd-Sotho-Sprache',	'Sotho, Southern',	'sotho du Sud',	NULL,	'no'),
(401,	'spa',	NULL,	'es',	'Spanisch',	'Spanish; Castilian',	'espagnol; castillan',	NULL,	'no'),
(402,	'sqi',	'alb',	'sq',	'Albanisch',	'Albanian',	'albanais',	NULL,	'no'),
(403,	'srd',	NULL,	'sc',	'Sardisch',	'Sardinian',	'sarde',	NULL,	'no'),
(404,	'srn',	NULL,	NULL,	'Sranantongo',	'Sranan Tongo',	'sranan tongo',	NULL,	'no'),
(405,	'srp',	'scc',	'sr',	'Serbisch',	'Serbian',	'serbe',	NULL,	'no'),
(406,	'srr',	NULL,	NULL,	'Serer-Sprache',	'Serer',	'sérere',	NULL,	'no'),
(407,	'ssa',	NULL,	NULL,	'Nilosaharanische Sprachen (Andere)',	'Nilo-Saharan (Other)',	'nilo-sahariennes, autres langues',	NULL,	'no'),
(408,	'ssw',	NULL,	'ss',	'Swasi-Sprache',	'Swati',	'swati',	NULL,	'no'),
(409,	'suk',	NULL,	NULL,	'Sukuma-Sprache',	'Sukuma',	'sukuma',	NULL,	'no'),
(410,	'sun',	NULL,	'su',	'Sundanesisch',	'Sundanese',	'soundanais',	NULL,	'no'),
(411,	'sus',	NULL,	NULL,	'Susu',	'Susu',	'soussou',	NULL,	'no'),
(412,	'sux',	NULL,	NULL,	'Sumerisch',	'Sumerian',	'sumérien',	NULL,	'no'),
(413,	'swa',	NULL,	'sw',	'Swahili',	'Swahili',	'swahili',	NULL,	'no'),
(414,	'swe',	NULL,	'sv',	'Schwedisch',	'Swedish',	'suédois',	NULL,	'no'),
(415,	'syc',	NULL,	NULL,	'Klassisches Syrisch',	'Classical Syriac',	'syriaque classique',	NULL,	'no'),
(416,	'syr',	NULL,	NULL,	'Syrisch',	'Syriac',	'syriaque',	NULL,	'no'),
(417,	'tah',	NULL,	'ty',	'Tahitisch',	'Tahitian',	'tahitien',	NULL,	'no'),
(418,	'tai',	NULL,	NULL,	'Thaisprachen (Andere)',	'Tai (Other)',	'thaies, autres langues',	NULL,	'no'),
(419,	'tam',	NULL,	'ta',	'Tamil',	'Tamil',	'tamoul',	NULL,	'no'),
(420,	'tat',	NULL,	'tt',	'Tatarisch',	'Tatar',	'tatar',	NULL,	'no'),
(421,	'tel',	NULL,	'te',	'Telugu-Sprache',	'Telugu',	'télougou',	NULL,	'no'),
(422,	'tem',	NULL,	NULL,	'Temne-Sprache',	'Timne',	'temne',	NULL,	'no'),
(423,	'ter',	NULL,	NULL,	'Tereno-Sprache',	'Tereno',	'tereno',	NULL,	'no'),
(424,	'tet',	NULL,	NULL,	'Tetum-Sprache',	'Tetum',	'tetum',	NULL,	'no'),
(425,	'tgk',	NULL,	'tg',	'Tadschikisch',	'Tajik',	'tadjik',	NULL,	'no'),
(426,	'tgl',	NULL,	'tl',	'Tagalog',	'Tagalog',	'tagalog',	NULL,	'no'),
(427,	'tha',	NULL,	'th',	'Thailändisch',	'Thai',	'thai',	NULL,	'no'),
(428,	'tig',	NULL,	NULL,	'Tigre-Sprache',	'Tigre',	'tigré',	NULL,	'no'),
(429,	'tir',	NULL,	'ti',	'Tigrinja-Sprache',	'Tigrinya',	'tigrigna',	NULL,	'no'),
(430,	'tiv',	NULL,	NULL,	'Tiv-Sprache',	'Tiv',	'tiv',	NULL,	'no'),
(431,	'tkl',	NULL,	NULL,	'Tokelauanisch',	'Tokelau',	'tokelau',	NULL,	'no'),
(432,	'tlh',	NULL,	NULL,	'Klingonisch',	'Klingon; tlhIngan-Hol',	'klingon',	NULL,	'no'),
(433,	'tli',	NULL,	NULL,	'Tlingit-Sprache',	'Tlingit',	'tlingit',	NULL,	'no'),
(434,	'tmh',	NULL,	NULL,	'Tamašeq',	'Tamashek',	'tamacheq',	NULL,	'no'),
(435,	'tog',	NULL,	NULL,	'Tonga (Bantusprache, Sambia)',	'Tonga (Nyasa)',	'tonga (Nyasa)',	NULL,	'no'),
(436,	'ton',	NULL,	'to',	'Tongaisch',	'Tonga (Tonga Islands)',	'tongan (Îles Tonga)',	NULL,	'no'),
(437,	'tpi',	NULL,	NULL,	'Neumelanesisch',	'Tok Pisin',	'tok pisin',	NULL,	'no'),
(438,	'tsi',	NULL,	NULL,	'Tsimshian-Sprache',	'Tsimshian',	'tsimshian',	NULL,	'no'),
(439,	'tsn',	NULL,	'tn',	'Tswana-Sprache',	'Tswana',	'tswana',	NULL,	'no'),
(440,	'tso',	NULL,	'ts',	'Tsonga-Sprache',	'Tsonga',	'tsonga',	NULL,	'no'),
(441,	'tuk',	NULL,	'tk',	'Turkmenisch',	'Turkmen',	'turkmene',	NULL,	'no'),
(442,	'tum',	NULL,	NULL,	'Tumbuka-Sprache',	'Tumbuka',	'tumbuka',	NULL,	'no'),
(443,	'tup',	NULL,	NULL,	'Tupi-Sprache',	'Tupi languages',	'tupi, langues',	NULL,	'no'),
(444,	'tur',	NULL,	'tr',	'Türkisch',	'Turkish',	'turc',	NULL,	'no'),
(445,	'tut',	NULL,	NULL,	'Altaische Sprachen (Andere)',	'Altaic (Other)',	'altaiques, autres langues',	NULL,	'no'),
(446,	'tvl',	NULL,	NULL,	'Elliceanisch',	'Tuvalu',	'tuvalu',	NULL,	'no'),
(447,	'twi',	NULL,	'tw',	'Twi-Sprache',	'Twi',	'twi',	NULL,	'no'),
(448,	'tyv',	NULL,	NULL,	'Tuwinisch',	'Tuvinian',	'touva',	NULL,	'no'),
(449,	'udm',	NULL,	NULL,	'Udmurtisch',	'Udmurt',	'oudmourte',	NULL,	'no'),
(450,	'uga',	NULL,	NULL,	'Ugaritisch',	'Ugaritic',	'ougaritique',	NULL,	'no'),
(451,	'uig',	NULL,	'ug',	'Uigurisch',	'Uighur; Uyghur',	'ouigour',	NULL,	'no'),
(452,	'ukr',	NULL,	'uk',	'Ukrainisch',	'Ukrainian',	'ukrainien',	NULL,	'no'),
(453,	'umb',	NULL,	NULL,	'Mbundu-Sprache',	'Umbundu',	'umbundu',	NULL,	'no'),
(454,	'und',	NULL,	NULL,	'Nicht zu entscheiden',	'Undetermined',	'indéterminée',	NULL,	'no'),
(455,	'urd',	NULL,	'ur',	'Urdu',	'Urdu',	'ourdou',	NULL,	'no'),
(456,	'uzb',	NULL,	'uz',	'Usbekisch',	'Uzbek',	'ouszbek',	NULL,	'no'),
(457,	'vai',	NULL,	NULL,	'Vai-Sprache',	'Vai',	'vai',	NULL,	'no'),
(458,	'ven',	NULL,	've',	'Venda-Sprache',	'Venda',	'venda',	NULL,	'no'),
(459,	'vie',	NULL,	'vi',	'Vietnamesisch',	'Vietnamese',	'vietnamien',	NULL,	'no'),
(460,	'vol',	NULL,	'vo',	'Volapük',	'Volapük',	'volapük',	NULL,	'no'),
(461,	'vot',	NULL,	NULL,	'Wotisch',	'Votic',	'vote',	NULL,	'no'),
(462,	'wak',	NULL,	NULL,	'Wakash-Sprachen',	'Wakashan languages',	'wakashennes, langues',	NULL,	'no'),
(463,	'wal',	NULL,	NULL,	'Walamo-Sprache',	'Walamo',	'walamo',	NULL,	'no'),
(464,	'war',	NULL,	NULL,	'Waray',	'Waray',	'waray',	NULL,	'no'),
(465,	'was',	NULL,	NULL,	'Washo-Sprache',	'Washo',	'washo',	NULL,	'no'),
(466,	'wen',	NULL,	NULL,	'Sorbisch',	'Sorbian languages',	'sorabes, langues',	NULL,	'no'),
(467,	'wln',	NULL,	'wa',	'Wallonisch',	'Walloon',	'wallon',	NULL,	'no'),
(468,	'wol',	NULL,	'wo',	'Wolof-Sprache',	'Wolof',	'wolof',	NULL,	'no'),
(469,	'xal',	NULL,	NULL,	'Kalmückisch',	'Kalmyk; Oirat',	'kalmouk; oirat',	NULL,	'no'),
(470,	'xho',	NULL,	'xh',	'Xhosa-Sprache',	'Xhosa',	'xhosa',	NULL,	'no'),
(471,	'yao',	NULL,	NULL,	'Yao-Sprache (Bantusprache)',	'Yao',	'yao',	NULL,	'no'),
(472,	'yap',	NULL,	NULL,	'Yapesisch',	'Yapese',	'yapois',	NULL,	'no'),
(473,	'yid',	NULL,	'yi',	'Jiddisch',	'Yiddish',	'yiddish',	NULL,	'no'),
(474,	'yor',	NULL,	'yo',	'Yoruba-Sprache',	'Yoruba',	'yoruba',	NULL,	'no'),
(475,	'ypk',	NULL,	NULL,	'Yupik-Sprache',	'Yupik languages',	'yupik, langues',	NULL,	'no'),
(476,	'zap',	NULL,	NULL,	'Zapotekisch',	'Zapotec',	'zapoteque',	NULL,	'no'),
(477,	'zbl',	NULL,	NULL,	'Bliss-Symbol',	'Blissymbols; Blissymbolics; Bliss',	'symboles Bliss; Bliss',	NULL,	'no'),
(478,	'zen',	NULL,	NULL,	'Zenaga',	'Zenaga',	'zenaga',	NULL,	'no'),
(479,	'zha',	NULL,	'za',	'Zhuang',	'Zhuang; Chuang',	'zhuang; chuang',	NULL,	'no'),
(480,	'zho',	'chi',	'zh',	'Chinesisch',	'Chinese',	'chinois',	NULL,	'no'),
(481,	'znd',	NULL,	NULL,	'Zande-Sprachen',	'Zande languages',	'zandé, langues',	NULL,	'no'),
(482,	'zul',	NULL,	'zu',	'Zulu-Sprache',	'Zulu',	'zoulou',	NULL,	'no'),
(483,	'zun',	NULL,	NULL,	'Zuni-Sprache',	'Zuni',	'zuni',	NULL,	'no'),
(484,	'zxx',	NULL,	NULL,	'kein linguistischer Inhalt, nicht anwendbar',	'No linguistic content; Not applicable',	'pas de contenu linguistique; non applicable',	NULL,	'no'),
(485,	'zza',	NULL,	NULL,	'Zazaki',	'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki',	'zaza; dimili; dimli; kirdki; kirmanjki; zazaki',	NULL,	'no');


-- logins --
CREATE TABLE `logins` (
  `login_id` int unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(63) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `login_rights` enum('admin','read and write','read') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'read',
  `password` varchar(60) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `password_change` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no',
  `logged_in` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'no',
  `last_click` int unsigned DEFAULT NULL,
  `active` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'yes',
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`login_id`),
  UNIQUE KEY `benutzername` (`username`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;


-- redirects --
CREATE TABLE `redirects` (
  `redirect_id` int unsigned NOT NULL AUTO_INCREMENT,
  `old_url` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `new_url` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `code` smallint unsigned NOT NULL DEFAULT '301',
  `area` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `website_id` int unsigned NOT NULL DEFAULT '1',
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`redirect_id`),
  UNIQUE KEY `old_url_website_id` (`old_url`,`website_id`),
  KEY `area` (`area`),
  KEY `website_id` (`website_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'websites', 'website_id', (SELECT DATABASE()), 'redirects', 'redirect_id', 'website_id', 'delete');


-- text --
CREATE TABLE `text` (
  `text_id` int unsigned NOT NULL AUTO_INCREMENT,
  `text` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `more_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `area` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`text_id`),
  UNIQUE KEY `text` (`text`(250)),
  KEY `area` (`area`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- webpages --
CREATE TABLE `webpages` (
  `page_id` int unsigned NOT NULL AUTO_INCREMENT,
  `website_id` int unsigned NOT NULL DEFAULT '1',
  `title` varchar(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `identifier` varchar(127) CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `ending` enum('.html','/','none') CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL DEFAULT 'none',
  `sequence` tinyint NOT NULL,
  `mother_page_id` int unsigned DEFAULT NULL,
  `live` enum('yes','no') CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT 'yes',
  `menu` enum('top','bottom','internal') CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `parameters` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`page_id`),
  UNIQUE KEY `identifier_website_id` (`identifier`,`website_id`),
  KEY `mother_page_id` (`mother_page_id`),
  KEY `website_id` (`website_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'webpages', 'page_id', (SELECT DATABASE()), 'webpages', 'page_id', 'mother_page_id', 'no-delete');

INSERT INTO `webpages` (`page_id`, `title`, `content`, `identifier`, `ending`, `sequence`, `mother_page_id`, `live`, `menu`, `parameters`, `last_update`) VALUES
(1,	'Website',	'Hello World',	'/',	'none',	1,	NULL,	'yes',	'top',	NULL,	NOW()),
(2,	'Internal Area',	'## Website\r\n\r\n* [Web pages](/db/webpages)\r\n* [Media](/db/media)\r\n\r\n## Help\r\n\r\n* [Markdown (German)](/hilfe/markdown)\r\n\r\n## Machine Room\r\n\r\n(Access normally not necessary)\r\n\r\n* [Redirects](/db/redirects) – if a web address has changed.\r\n* [Maintenance](/db/maintenance) – administration of everything.\r\n* [Log of database changes](/db/logging)\r\n* [Table relations](/db/relations)\r\n* [Logins](/db/logins)\r\n\r\n## [Logout](/logout/)\r\n',	'/db',	'/',	2,	NULL,	'yes',	'internal',	'&edit=admin',	NOW()),
(3,	'Login',	'%%% request login %%%',	'/login',	'/',	0,	2,	'yes',	NULL,	'&edit=admin',	NOW()),
(4,	'Logout',	'%%% request logout %%%',	'/logout',	'/',	10,	2,	'yes',	'internal',	'&edit=admin',	NOW()),
(5,	'Tables',	'%%% tables * %%%',	'/db*',	'none',	1,	2,	'yes',	NULL,	'&edit=admin',	NOW()),
(6,	'Markdown-Hilfe',	'# Markdown\r\n\r\n## HTML\r\n\r\nHTML kann direkt in den Text geschrieben werden und wird direkt ausgegeben. Blockelemente sollten durch Leerzeilen vom Text abgetrennt und die Start- und Endmarkierungen nicht eingerückt werden. Innerhalb von HTML-Blockelementen (Tabellen, Überschriften, Absätzen etc.) wird kein Markdown interpretiert.\r\n\r\nBeispiel:\r\n\r\n	Normaler Absatz.\r\n\r\n	<table>\r\n		<tr>\r\n			<td>Bla</td>\r\n		</tr>\r\n	</table>\r\n	\r\n	Neuer Absatz, hier kann auch eine \r\n	<abbr title=\"Abkürzung\">Abk.</abbr> eingebaut werden.\r\n\r\n## Sonderzeichen\r\n\r\n& sowie < und > werden von Markdown automatisch maskiert.\r\n\r\n## Block-Elemente\r\n\r\n### Absätze und Zeilenumbrüche\r\n\r\nEin Absatz besteht aus mehreren Zeilen, die von anderen Absätzen durch eine Leerzeile abgetrennt werden.\r\n\r\nZeilenumbrüche können durch das Einfügen von zwei Leerzeichen am Ende einer Zeile erzwungen werden.\r\n\r\n### Überschriften\r\n\r\n	Dies ist eine Überschrift 1. Ordnung (H1)\r\n	=========================================\r\n\r\n	Dies ist eine Überschrift 2. Ordnung (H2)\r\n	-----------------------------------------\r\n\r\noder\r\n\r\n	# Dies ist eine H1\r\n\r\n	## Dies ist eine H2\r\n\r\n	###### Dies ist eine H6\r\n\r\noder\r\n\r\n	# Dies ist eine H1 #\r\n\r\n	## Dies ist eine H2 ##\r\n\r\n	### Dies ist eine H3 ######\r\n\r\n### Zitate\r\n\r\n	> Zitatblöcke funktionieren wie in E-Mails.\r\n	> Zitate können auch verschachtelt werden:\r\n	>> Dies ist ein Zitat von meinem Vorredner.\r\n\r\n### Listen\r\n\r\n	* unsortierte Listen werden mit * oder\r\n	* mit - oder\r\n	* mit + als erstem Zeichen einer Zeile markiert.\r\n\r\n	1. Sortierte Listen\r\n	2. beginnen mit Zahlen, Punkt und Leerzeichen\r\n	\r\n	* Hierarchische Listen\r\n	  * mit zwei Leerzeichen Einrückung\r\n	  * dann wird die Liste automatisch hierarchisch dargestellt\r\n	* weitere Punkte wieder ausgerückt\r\n\r\nDa jede Nummer mit Punkt und Leerzeichen dazu führt, dass Text als Listeneintrag interpretiert wird, kann man dies durch Einfügen eines \\ verhindern:\r\n\r\n	1986\\. Was für ein wundervolles Jahr.\r\n	\r\n### Code-Blöcke\r\n\r\nCode-Blöcke (Programmauszüge, HTML-Schnipsel) werden mit vier Leerzeichen oder einem Tabulator eingerückt und werden dann so dargestellt wie eingegeben.\r\n\r\n### Horizontale Linien\r\n\r\n	* * *\r\n\r\n	***\r\n\r\n	*****\r\n\r\n	- - -\r\n\r\n	---------------------------------------\r\n\r\n	_ _ _\r\n\r\n## Text-Elemente\r\n\r\n### Links\r\n\r\nDirekt im Text:\r\n\r\n	Dies ist [ein Beispiel](http://example.com/ \"Titel\") Inline-Link.\r\n	\r\n	[Dieser Link](http://example.net/) hat kein Titel-Attribut.\r\n\r\n	Auf der Seite [Über mich](/about/) gibt es weitere Informationen.\r\n\r\nOder als Referenz im Text, mit Angabe der URL am Ende eines Textes. Groß- und Kleinschreibung wird dabei nicht beachtet.\r\n\r\n	Dies ist [ein Beispiel][id] für einen Referenz-Link.\r\n\r\n	[id]: http://example.com/  \"Optionalen Titel hier eintragen\"\r\n\r\nLinkreferenzen können auch abgekürzt werden:\r\n\r\n	[Google][]\r\n	\r\n	[Google]: http://google.com/\r\n\r\n### Betonung\r\n\r\n	*Betonter Text, wird meist kursiv dargestellt*\r\n\r\n	_Betonter Text, wird meist kursiv dargestellt_\r\n	\r\n	**Stark betonter Text, wird meist fett dargestellt**\r\n	\r\n	__Stark betonter Text, wird meist fett dargestellt__\r\n	\r\n	\\*Text, von Sternchen umschlossen \\*\r\n\r\n### Code\r\n\r\nCode-Blöcke werden in Zollzeichen (\'\' \' \'\') eingebunden. Enthält der Code selber ein Zollzeichen, muß der Code mit zwei Zollzeichen eingeführt und beendet werden.\r\n\r\n	Z. B. HTML-Code: \'<title>\' \r\n	\r\n	\'\'Code mit \' im Text.\'\'\r\n	\r\n\r\n### Grafiken\r\n\r\nDirekt im Text\r\n\r\n	![Alternativer Text](/pfad/zu/img.jpg)\r\n\r\n	![Alternativer Text](/pfad/zu/img.jpg \"Optionaler Titel\")\r\n\r\noder als Referenz im Text, mit Angabe der URL am Ende eines Textes\r\n\r\n	![Alternativer Text][id]\r\n\r\n	[id]: url/zur/grafik  \"Optionales title-Attribut\"\r\n\r\n### einfache Links\r\n\r\n	<http://www.example.com/>\r\n\r\n	<address@example.com>\r\n\r\n### Maskierung\r\n\r\nDa einige Zeichen an bestimmten Stellen in Markdown eine besondere Bedeutung haben, muß man sie mit einem \'\\\' maskieren, wenn man sie trotzdem darstellen möchte:\r\n\r\n	\\ \' * _ {} [] () # + - . !\r\n\r\n***\r\n	\r\n* [Komplette Referenz Markdown, Original auf Englisch](http://daringfireball.net/projects/markdown/syntax)\r\n* [Komplette Referenz Markdown, Deutsche Übersetzung](http://markdown.de/syntax/)\r\n\r\n***\r\n\r\nMarkdown-Extra            {#extra}\r\n==============\r\n\r\nMarkdown-Extra ist eine Erweiterung zu Markdown. Dadurch gibt es ein paar weitere Möglichkeiten:\r\n\r\n### Abkürzungen\r\n\r\nsehen ähnlich wie Links aus und werden an das Ende des Textes gestellt. Die Abkürzung wird dann überall im Text automatisch mit der Langform hinterlegt. \r\n\r\n	*[BBR]: Bundesamt für Bauwesen und Raumordnung\r\n\r\n### Tabellen\r\n\r\nsind etwas komplizierter: einzelne Tabellenzellen werden durch | getrennt, jede Tabelle benötigt einen Tabellenkopf (wichtig auch für die Barrierefreiheit)\r\n\r\n  Tabellenbeispiel:\r\n\r\n	Jahr    | Ereignis \r\n	------- | ------------------\r\n	1969    | Mondlandung\r\n	1989    | Mauerfall \r\n\r\n### Markdown innerhalb von HTML-Blöcken\r\n\r\nfunktioniert mit &lt;div markdown=\"1\"> ... &lt;/div> - so kann man z. B. einfach Klassen auf Markdown-Bereiche anwenden und den Bereich darüber formatieren.\r\n\r\nDazu kommen weitere Formatierungsmöglichkeiten für Fußnoten, Definitionslisten (in HTML: DL, DT, DD) und Linkanker bei Überschriften.\r\n\r\n***\r\n\r\n* [Komplette Referenz Markdown-Extra, Original auf Englisch](http://michelf.com/projects/php-markdown/extra/)\r\n',	'/hilfe/markdown',	'none',	9,	2,	'yes',	NULL,	NULL,	NOW()),
(7,	'Maintenance',	'%%% request maintenance %%%',	'/db/maintenance',	'/',	7,	2,	'yes',	NULL,	'&edit=admin',	NOW()),
(8,	'Adminer',	'%%% request adminer %%%',	'/db/adminer',	'/',	7,	2,	'yes',	NULL,	'&edit=admin',	NOW()),
(9,	'Website Settings',	'%%% forms settings-website %%%',	'/db/settings',	'none',	10,	2,	'yes',	NULL,	'&edit=admin',	NOW()),
(10,	'Files',	'%%% request medium * %%%',	'/files*',	'/',	10,	1,	'yes',	NULL,	'&edit=admin',	NOW()),
(11,	'Media',	'%%% forms media * %%%',	'/db/media',	'/',	9,	2,	'yes',	NULL,	'&edit=admin',	NOW()),
(12,	'Media',	'%%% forms media * %%%',	'/db/media*',	'/',	1,	11,	'yes',	NULL,	'&edit=admin',	NOW()),
(13,	'Robots', '%%% set content_type=txt %%%\n# robots.txt', '/robots.txt', 'none', 40, 1, 'yes', NULL, '&edit=admin', NOW());


-- webpages_media --
CREATE TABLE `webpages_media` (
  `page_medium_id` int unsigned NOT NULL AUTO_INCREMENT,
  `page_id` int unsigned NOT NULL,
  `medium_id` int unsigned NOT NULL,
  `sequence` tinyint NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`page_medium_id`),
  UNIQUE KEY `page_id` (`page_id`,`sequence`),
  UNIQUE KEY `medium_id` (`medium_id`,`page_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'media', 'medium_id', (SELECT DATABASE()), 'webpages_media', 'page_medium_id', 'medium_id', 'no-delete');
INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'webpages', 'page_id', (SELECT DATABASE()), 'webpages_media', 'page_medium_id', 'page_id', 'delete');


-- websites --
CREATE TABLE `websites` (
  `website_id` int unsigned NOT NULL AUTO_INCREMENT,
  `website` varchar(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `domain` varchar(63) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`website_id`),
  UNIQUE KEY `website` (`website`),
  UNIQUE KEY `domainname` (`domain`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `websites` (`website_id`, `website`, `domain`) VALUES
(1,	'All Websites',	'*');

INSERT INTO _relations (`master_db`, `master_table`, `master_field`, `detail_db`, `detail_table`, `detail_id_field`, `detail_field`, `delete`) VALUES ((SELECT DATABASE()), 'websites', 'website_id', (SELECT DATABASE()), 'webpages', 'page_id', 'website_id', 'no-delete');
